### DISCUSSION TITLE
Backups are taking GBs of space

### DISCUSSION THREAD

**Discussion by kalgurn** [mbround18/valheim-docker#110] [Help!] [answered]
Hi, I guess there is something wrong with the backup script.
The server is started for only a few hours ago and backups are already taking 200+ Gbs 
![image](https://user-images.githubusercontent.com/38934525/108063655-37320e80-7064-11eb-908a-5eba3f87c6f5.png)

The setup is - Win 10 Home Build 18363.1379 -> WSL Ubuntu for Docker installation -> Server running in a docker container
![image](https://user-images.githubusercontent.com/38934525/108063930-a0198680-7064-11eb-87dc-ef2dbed6033e.png)

Here is my compose file
```yaml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="world"
      - WORLD="world"
      - PASSWORD="password"
      - TZ=Europe/Kiev
      - PUBLIC=0
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
    volumes:
      - /mnt/c/Users/kalgurn/Valheim/valheim/:/home/steam/.config/unity3d/IronGate/Valheim
      - /mnt/c/Users/kalgurn/Valheim/valheim/server:/home/steam/valheim
      - /mnt/c/Users/kalgurn/Valheim/valheim/backups:/home/steam/backups
```
