### DISCUSSION TITLE
When starting container for the first time as non-1000 uid user, get `mkdir: cannot create directory ‘/home/steam’: Permission denied`

### DISCUSSION THREAD

**Discussion by halb** [mbround18/valheim-docker#1163] [Help!] [answered]
## System Information

Operating System:  Ubuntu 24.04.2 LTS
Docker Version: Docker version 28.2.2, build e6534b4
Docker Compose Version:  docker-compose version 1.29.2, build unknown
User & Group On Host: 1002:1003
Are you running with BepInEx? No

## Issue Description
Running into permission issues starting image for the first time.  It's trying to create /home/steam, gets permission denied, then exits out.

```
steam@rhumba:~$ docker-compose down ; docker-compose up
Removing network steam_default
WARNING: Network steam_default not found.
Creating network "steam_default" with the default driver
Creating steam_valheim_1 ... done
Attaching to steam_valheim_1
valheim_1  | Sat Jun 14 07:06:54 PM America 2025 - Valheim Server - Sat Jun 14 07:06:54 PM America 2025
valheim_1  | Sat Jun 14 07:06:54 PM America 2025 - Initializing your container...
valheim_1  | steam
valheim_1  | 111
valheim_1  | 1000
valheim_1  | America/New York
valheim_1  | (standard_in) 1: syntax error
valheim_1  | 2025-06-14 19:06:54 - [Valheim][INFO]: Total memory: 12i GB
valheim_1  | 2025-06-14 19:06:54 - [Valheim][INFO]: Setting up file systems
valheim_1  | mkdir: cannot create directory ‘/home/steam’: Permission denied
steam_valheim_1 exited with code 1
```

docker-compose.yaml
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PUID: "1002"
      PGID: "1003"
      PORT: 2456
      NAME: "X"
      WORLD: "Y"
      PASSWORD: "Z"
      TZ: "America/New York"
      PUBLIC: 0
      UPDATE_ON_STARTUP: 0
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
```

Directories exist and have these owners and permissions
```
steam@rhumba:~$ ls -ladn /home/steam /home/steam/.config /home/steam/valheim
drwxrwx--- 11 1002 1003 4096 Jun 14 19:15 /home/steam
drwxrwx---  6 1002 1003 4096 Nov 27  2024 /home/steam/.config
drwxrwx---  4 1002 1003 4096 Jun 14 19:03 /home/steam/valheim
```

Steam is in the docker group
```
steam@rhumba:~$ cat /etc/group | grep docker
docker:x:999:steam,valheim
```

Using latest
```
steam@rhumba:~$ docker pull mbround18/valheim
Using default tag: latest
latest: Pulling from mbround18/valheim
Digest: sha256:44c2ab93f34c63765b0fbab8f5ec5f67a35f315d995760bf8d4af6ba2f766860
Status: Image is up to date for mbround18/valheim:latest
docker.io/mbround18/valheim:latest
```

### Also tried
Also tried running this as a different "valheim" user (in the docker and steam groups) with both steam and valheim PUID/GUIDs.
Also tried numeric values for PUID, PGID
Also tried `docker-compose rm -svf valheim` before starting

**Comment by mbround18** [comment, marked as answer]
PUID is a deprecated option, please try with the following user flag

```yaml

services:
  valheim:
    image: mbround18/valheim:latest
    user: "1000:1000"
    
```


On your host chown -R 1000:1000 ./valheim
