### DISCUSSION TITLE
Failed to find Server Executable Error

### DISCUSSION THREAD

**Discussion by samcat116** [mbround18/valheim-docker#118] [Help!] [answered]
Seeing this following the basic getting started guide on a fresh DO droplet

```
valheim_1  | Password: (REDACTED)
valheim_1  |
valheim_1  | [Valheim][steam]: Running Install...
valheim_1  | [ODIN][INFO]  - Installing 896660 to /home/steam/valheim
valheim_1  | [ODIN][ERROR] - Failed to find steamcmd in path
valheim_1  | [ODIN][ERROR] - Checking for script under steam user.
valheim_1  | [ODIN][INFO]  - Executing: /home/steam/steamcmd/steamcmd.sh .....
valheim_1  | [ODIN][INFO]  - Using steamcmd script at /home/steam/steamcmd/steamcmd.sh
valheim_1  | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
valheim_1  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
valheim_1  | [  0%] Checking for available updates...
valheim_1  | [----] Downloading update (151 of 16258 KB)...
valheim_1  | [  0%] Downloading update (2638 of 16258 KB)...
valheim_1  | [ 16%] Downloading update (4360 of 16258 KB)...
valheim_1  | [ 26%] Downloading update (5609 of 16258 KB)...
valheim_1  | [ 34%] Downloading update (6770 of 16258 KB)...
valheim_1  | [ 41%] Downloading update (8152 of 16258 KB)...
valheim_1  | [ 50%] Downloading update (9405 of 16258 KB)...
valheim_1  | [ 57%] Downloading update (10677 of 16258 KB)...
valheim_1  | [ 65%] Downloading update (11889 of 16258 KB)...
valheim_1  | [ 73%] Downloading update (13160 of 16258 KB)...
valheim_1  | [ 80%] Downloading update (14443 of 16258 KB)...
valheim_1  | [ 88%] Downloading update (15703 of 16258 KB)...
valheim_1  | [ 96%] Downloading update (16258 of 16258 KB)...
valheim_1  | [100%] Download complete.
valheim_1  | [----] Installing update...
valheim_1  | [----] Extracting package...
valheim_1  | [----] Extracting package...
valheim_1  | [----] Extracting package...
valheim_1  | [----] Extracting package...
valheim_1  | [----] Installing update...
valheim_1  | [----] Installing update...
valheim_1  | [----] Installing update...
valheim_1  | [----] Installing update...
valheim_1  | [----] Installing update...
valheim_1  | [----] Installing update...
valheim_1  | [----] Installing update...
valheim_1  | [----] Installing update...
valheim_1  | [----] Cleaning up...
valheim_1  | [----] Update complete, launching Steamcmd...
valheim_1  | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
valheim_1  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
valheim_1  | [  0%] Checking for available updates...
valheim_1  | [----] Verifying installation...
valheim_1  | Steam Console Client (c) Valve Corporation
valheim_1  | -- type 'quit' to exit --
valheim_1  | Loading Steam API...OK.
valheim_1  |
valheim_1  | Connecting anonymously to Steam Public...Logged in OK
valheim_1  | Waiting for user info...[ODIN][INFO]  - Exited with status code: 137
valheim_1  | [Valheim][steam]: Initializing Variables....
valheim_1  | [ODIN][ERROR] - Failed to find server executable! Please run `odin install`
valheim_1  | /home/steam/steamcmd/steamcmd.sh: line 38:    66 Killed                  $DEBUGGER "$STEAMEXE" "$@"
sam_valheim_1 exited with code 1
```

**Comment by mbround18** [comment, marked as answer]
- What does your compose look like? 
- Is your users id 1000? or are you running under a different user id? did you supply the user id?

**Reply by samcat116** [reply]
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="2edgy"
      - WORLD="Dedicated"
      - PASSWORD="hidden"
      - TZ=America/Chicago
      - PUBLIC=1
      - AUTO_UPDATE=0
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
 ```

I am running this as root since this is a brand new droplet, so I've run `export PUID=1000` and `export PGID=1000`
