### DISCUSSION TITLE
Failed to find server executable

### DISCUSSION THREAD

**Discussion by Uraxii** [mbround18/valheim-docker#134] [Help!] [answered]
Hello! It appears Odin is not being installed when I run the `docker-compose up` command. My machine is an Ubuntu box with 8GB of RAM and I am able to run a server normally on the host. Does anyone else know what might be causing this issue?
The output is below.
Thanks!

**docker-compose.yml**
```
serveruser@valheim:~/Valheim$ cat docker-compose.yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="RaxiiServer"
      - WORLD="001-Dedicated"
      - PASSWORD="gwAfVa33d"
      - TZ=America/Chicago
      - PUBLIC=1
      - AUTO_UPDATE=0
      - PUID=1002
      - PGID=1002
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
```

**`docker-compose up` Output**
```
serveruser@valheim:~/Valheim$ docker-compose up
Starting valheim_valheim_1 ... done
Attaching to valheim_valheim_1
valheim_1  | [Valheim][root] : ###########################################################################
valheim_1  | [Valheim][root] : Valheim Server - Wed Feb 17 22:23:28 CST 2021
valheim_1  | [Valheim][root] : Initializing your container...
valheim_1  | [Valheim][root] : You must be in development. Good luck!
valheim_1  | [Valheim][root] : ###########################################################################
valheim_1  | [Valheim][root] : Switching UID and GID
valheim_1  | usermod: no changes
valheim_1  | [Valheim][root] :
valheim_1  | [Valheim][root] :
valheim_1  | [Valheim][root] : Setting up file systems
valheim_1  | [Valheim][root] : Launching as steam...
valheim_1  | [Valheim][steam]: ###########################################################################
valheim_1  | [Valheim][steam]: Valheim Server - Wed Feb 17 22:25:39 CST 2021
valheim_1  | [Valheim][steam]: STEAM_UID 1002 - STEAM_GUID 1002
valheim_1  | [Valheim][steam]: Installing Valheim via Odin...
valheim_1  | [Valheim][steam]: ###########################################################################
valheim_1  | [Valheim][steam]: Variables loaded.....
valheim_1  | [Valheim][steam]:
valheim_1  | Port: 2456
valheim_1  | Name: RaxiiServer
valheim_1  | World: 001-Dedicated
valheim_1  | Public: 1
valheim_1  | Password: (REDACTED)
valheim_1  |
valheim_1  | [Valheim][steam]: Running Install...
valheim_1  | [ODIN][INFO]  - Installing 896660 to /home/steam/valheim
valheim_1  | [ODIN][ERROR] - Failed to find steamcmd in path
valheim_1  | [ODIN][ERROR] - Checking for script under steam user.
valheim_1  | [ODIN][INFO]  - Executing: /home/steam/steamcmd/steamcmd.sh .....
valheim_1  | [ODIN][INFO]  - Using steamcmd script at /home/steam/steamcmd/steamcmd.sh
valheim_1  | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
valheim_1  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
valheim_1  | /tmp/dumps is not owned by us - delete and recreate
valheim_1  | Unable to delete /tmp/dumps. Continuing anyway.
valheim_1  | [  0%] Checking for available updates...
valheim_1  | [----] Verifying installation...
valheim_1  | [  0%] Downloading update...
valheim_1  | [  0%] Checking for available updates...
valheim_1  | [----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
valheim_1  | src/tier0/threadtools.cpp (3553) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x57b0a8f0/0x0xf7bd3b'
valheim_1  | [ODIN][INFO]  - Exited with status code: 254
valheim_1  | [Valheim][steam]: Initializing Variables....
valheim_1  | [ODIN][ERROR] - Failed to find server executable! Please run `odin install`
valheim_valheim_1 exited with code 1
```
