### DISCUSSION TITLE
The server doesn't start.

### DISCUSSION THREAD

**Discussion by Neil2222** [mbround18/valheim-docker#137] [Help!] [answered]
Followed all the steps. Used the comment from JeffMings to test it. When running `docker-compose up` it stops here. 

![image](https://user-images.githubusercontent.com/10209462/108384538-21128280-720b-11eb-92ff-73c92a650737.png)

When checking for open ports with 'nmap -sU -p 2455-2459  127.0.0.1' it shows the ports are open. When I close the server I see the ports close again, so something is happening.

What can I do?

**Comment by mbround18** [comment, marked as answer]
For debugging, please 
- Post your `docker-compose.yml`
- What your users ID and group ID are: `echo "$(id -u):$(id -g)"`

**Reply by Neil2222** [reply]
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="SpelerKamer"
      - WORLD="SpelerKamer"
      - PASSWORD="pwd123"
      - TZ=Europe/Amsterdam
      - PUBLIC=1
      - AUTO_UPDATE=0
      - PUID=1003
      - PGID=1003
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim


```

![image](https://user-images.githubusercontent.com/10209462/108491556-5b7c2e00-72a4-11eb-8dff-aee8896aa50b.png)
