### DISCUSSION TITLE
Backups folder remains empty

### DISCUSSION THREAD

**Discussion by enzobes** [mbround18/valheim-docker#139] [Help!] [answered]
Hello I use the docket-compose.yml example on GitHub for the auto backup but my backups folder remains empty after 1 days

Here my docker-compose.yml
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    environment:
      - PORT=2456
      - NAME="Name"
      - PASSWORD="xxxxxxxx"
      - TZ=Europe/Paris
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1

    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
    - ./saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./server:/home/steam/valheim
    - ./backups:/home/steam/backups


```

Thanks
