### DISCUSSION TITLE
Server keeps reconnecting

### DISCUSSION THREAD

**Discussion by danielvancamp** [mbround18/valheim-docker#174] [Q&A] [answered]
First of all, thanks for the docker container and your effort in maintaining this! I'll try my best to explain the issue with all information needed. If i missed anything let me know! 

### System Information
Operating System: **Server Rack with 128RAM and Xeon Processor**
Docker Version: **Docker version 20.10.2, build 2291f61**
Docker Compose Version: **docker-compose version 1.25.0, build unknown**
User & Group On Host: **1000:1000, user has correct permissions**
BepInEx? **No** (i think, haven't installed it myself)

### Docker Compose
```
version: "3"
services:
  valheim:
    container_name: valheim
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    networks:
      default:
        ipv4_address: 192.168.1.36
    environment:
      - PORT=2456
      - NAME="VikingUnicorns"
      - WORLD="Dedicated"
      - PASSWORD="somepasswordwhichijustedchanged"
      - TZ=Europa/Brussels
      - PUBLIC=0
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 5 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/30 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
    volumes:
      - /data/docker/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /data/docker/valheim/server:/home/steam/valheim
      - /data/docker/valheim/backups:/home/steam/backups

networks:
  default:
    external:
      name: someMACVLANnetwork
```            

### Issue Description
- Docker containers startup without problem
- Server starts running
- After a few seconds the server disconnects
- After a few more seconds server reconnects again
- And so on and on and on and on 

Port forwarding is setup and working
I've run the server outside the docker container as well to test and this seems to work. No disconnects happening.

### Logs
![image](https://user-images.githubusercontent.com/8830345/109083768-ce533200-7706-11eb-9f7b-2bbe0d858231.png)
