### DISCUSSION TITLE
Cannot connect via direct IP outside of LAN, but friends can join via steam

### DISCUSSION THREAD

**Discussion by BenjaFriend** [mbround18/valheim-docker#193] [Help!]
I've set up the server and can successfully connect via LAN with direct IP, but even after port forwarding all necessary ports (2456-2458) I cannot connect to the server outside of my on home network. 

The weird thing is that you can join the server if you join via steam, and hit "Join Friend" instead of doing direct connect. 

I've tried forwarding the "Steam Server" ports that I have seen in a few places of `27015-27030`, but that didn't resolve the issue.

I know that my public IP is accessible because I can access a ton of other services like SSH, Minecraft, plex, etc. all perfectly fine. 

Has anyone else run into this issue? It's got me totally stumped... 

Thanks for any help/advice!

**Comment by mbround18** [comment]
Is your home network port forwarded to that server?

**Reply by BenjaFriend** [reply]
Yes it is :) You can connect to the server from outside of my LAN via the steam menu by joining a player already on the server, but you cannot access it via direct IP connection.

**Reply by mbround18** [reply]
Hmmm, if you are looking to access the server Via in game by clicking join by ip make sure to use the `:2456` port. However, if you are using the favorites method you will have to use port `:2457`. (unless you changed the env var, then its what ever you put in the env var is the game connection port and the +1 port is the steam favorites port.) 

Have you tried those connection methods?

**Reply by BenjaFriend** [reply]
Yes I have tried connecting via  the different ports (2456-2458) to no avail :( I have also tried changing the bound ports on the container to something else to check if my ISP or something was blocking those ports, but that didn't work either. 

Just for the record, here ismy docker-compose.yml:

```yml
version: "3"
services:
  odin:
    image: mbround18/valheim-odin:latest
    build:
      context: .
      dockerfile: ./Dockerfile.odin
    volumes:
    - odin-output:/data/odin/target/release
  valheim:
    depends_on:
      - odin
    image: mbround18/valheim:latest
    environment:
      - PORT=2456
      - NAME="My Valheim Server"
      - WORLD="MyServerName"
      - PASSWORD="StrongPassword123"
      - TZ=America/New_York
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
      - "27015-27030:27015-27030"
    volumes:
    - ./data/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./data/server:/home/steam/valheim
    - ./data/backups:/home/steam/backups
    - odin-output:/home/steam/.odin
    restart: unless-stopped

volumes:
  odin-output:
```

As you can see I've left it on the default port of `2456` and can connect via that port successfully locally. I can also confirm that the ports are successfully bound to `0.0.0.0` on the host machine.

The container is running on a ubuntu box: 
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

I can confirm that the UFW settings on the box are correct as well and allowing incoming connections. 

The problem comes when accessing via a public IP. I can confirm that my port forwarding setup is correct and valid (as I mentioned I have no trouble connecting via SSH or to a minecraft server running on the same box)

My next debugging steps are to run a `tcpdump` on the ports and see if I can capture what is going on more depth, but it is really odd to me how this is the only service I'm running with this issue.

**Reply by mbround18** [reply]
It looks like your compose is running an older version of the original compose, heres an updated one:
```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    environment:
      - PORT=2456
      - NAME="My Valheim Server"
      - WORLD="MyServerName"
      - PASSWORD="StrongPassword123"
      - TZ=America/New_York
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
      - "27015-27030:27015-27030"
    volumes:
    - ./data/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./data/server:/home/steam/valheim
    - ./data/backups:/home/steam/backups
    restart: unless-stopped
```
Try pulling the latest image as well, `docker-compose pull` this should help resolve some issues based on when your compose was constructed. 

As for the connection, would you mind doing a tcp dump or having your friend do a tcp dump? It should allow connection based on that config provided but I am unsure about your network infrastructure.
