### DISCUSSION TITLE
Port, +1 or not?

### DISCUSSION THREAD

**Discussion by kieron** [mbround18/valheim-docker#199] [Help!] [answered]
Hi there, I notice the instructions that says to add +1 to your port, to get what you should input to steam etc, but Im a bit stuck.

I am running 2 servers, this one, 

```
ports:
      - 2459:2459/udp
      - 2460:2460/udp
      - 2461:2461/udp
    environment:
      - PORT=2459
```

and this one
```
ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
```

Those ports are reflected in portainer too, so I'm sure its all mapped correctly- but what I'm finding is that take that top one, I have `2459` in the docker compose, so +1, I should be adding `2460` right? But if I click Find games in steam using `ip:2460` it finds the server, correct name, then I click save this, and I view the server info, now it says `ip:2459` so I'm not sure which I am supposed to tell people to use?

Also, are there any other issues with running 2 at once? Anything else I should change to avoid a crossover, except ports & directories obviously.

Thanks!

**Comment by mbround18** [comment, marked as answer]
if you are looking to access the server Via in game by clicking join by ip make sure to use the :2456 port. However, if you are using the favorites method you will have to use port :2457. (unless you changed the env var, then its what ever you put in the env var is the game connection port and the +1 port is the steam favorites port.)


The whole +1 schema is accurate, I run ~10-15 servers right now on my cluster with escalating port numbers. (ex 30010-30013, 30014-30016, etc) The steam connection port for steam related is based off the query port which is +1 of what you set in the env variable but the connection port for in game is the env variable port.

**Reply by slayer1551** [reply]
Im running it on AWS LightSail Ubnutu 20 4gb 2cpu and it runs fine and I can connect, however I cant seem to get it to show up in the server favourites. Its running the default port 2456 so I added 2457 to the port in steam but it just shows not responding all the time. I've opened up all the correct ports 

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
      - 27015-27030:27015-27030
    environment:
      - PORT=2456
      - NAME="Boople"
      - WORLD="Boople"
      - PASSWORD="ready1"
      - TZ=Europe/London
      - PUBLIC=0
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/30 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=7
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP=0
      - WEBHOOK_URL=https://discord.com/api/webhooks/snowflake/secret
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
    restart: unless-stopped
```
![Screenshot 2021-03-05 at 10 18 54](https://user-images.githubusercontent.com/875752/110102150-520ebd80-7d9c-11eb-8c8a-638b990e0fa9.png)
