### DISCUSSION TITLE
Advanced configuration for Kubernetes Deploy

### DISCUSSION THREAD

**Discussion by mbround18** [mbround18/valheim-docker#20] [Instructions]
# [K3s] Deployment of Valheim

## Requirements
- A dedicated/failover IP to publish the game to. 
- VSCode or someting to edit code
- a [K3s] cluster

## Setup

1. Create a project directory
2. Create the `kustomization.yml` file
3. Create two directories called `base` and `server` (this is for separation of concern)
4. Create a folder called `secrets`

### `kustomization.yml`

```yml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization  
namespace: valheim-server

resources:
- base/00-namespace.yml
- base/01-persisted-volumn-claim.yml
- server/01-deployment.yml
- server/02-backend-service.yml


secretGenerator:
- name: valheim-server-env
  # env is a path to a file to read lines of key=val
  # you can only specify one env file per secret.   
  env: secrets/env.txt
  type: Opaque
```

#### `base/00-namespace.yml`

```yml
---
apiVersion: v1
kind: Namespace
metadata: 
  name: valheim-server
  labels: 
    name: valheim-server
```

#### `base/01-persisted-volume-claim.yml`

```yml 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-server-pv-claim
  namespace: valheim-server
spec:
  # Change this based on the storage class you use. 
  # In the example I have a longhorn system setup.
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
```

#### `secrets/env.txt`

```txt
PASSWORD=SomethingSecret
```

#### `server/01-deployment.yml`

```yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim-server
  labels:
    app: valheim-server
    designation: server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: valheim-server
      designation: server
  template:
    metadata:
      namespace: valheim-server
      labels:
        app: valheim-server
        designation: server
    spec:
      containers:
        - name: valheim-server
          image: mbround18/valheim:latest
          imagePullPolicy: Always
          env:
            - name: NAME
              value: "Valheim Server"
            - name: WORLD
              value: "Dedicated"
            - name: PORT
              value: "30016"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valheim-server-env
                  key: PASSWORD
            - name: AUTO_UPDATE
              value: "1"
          ports:
            - name: join-1
              containerPort: 30016
              protocol: UDP 
            - name: join-2
              containerPort: 30017
              protocol: UDP 
            - name: join-3
              containerPort: 30018
              protocol: UDP 
          volumeMounts:
            - name: valheim-server-persistent-storage
              mountPath: /home/steam/.config/unity3d/IronGate/Valheim
              subPath: saves
            - name: valheim-server-persistent-storage
              mountPath: /home/steam/valheim
      volumes:
        - name: valheim-server-persistent-storage
          persistentVolumeClaim:
            claimName: valheim-server-pv-claim
```

#### `server/02-backend-service.yml`

```yml
---
apiVersion: v1
kind: Service
metadata:
  name: valheim-server-udp-service
  namespace: valheim-server
  labels:
    name: valheim-server
    designation: server
spec:
  type: LoadBalancer
  # Your External IP
  loadBalancerIP: xx.xx.xx.xx
  ports:
    - port: 30016
      name: join-udp-1
      targetPort: join-1
      protocol: UDP
      nodePort: 30016
    - port: 30017
      name: join-udp-2
      targetPort: join-2
      protocol: UDP
      nodePort: 30017
    - port: 30018
      name: join-udp-3
      targetPort: join-3
      protocol: UDP
      nodePort: 30018

  selector:
    app: valheim-server
    designation: server
```

### Creation

```sh
kubectl apply -k . 
```

### Destruction

```sh
kubectl delete -k . 
```

[K3s]: https://k3s.io/
