### DISCUSSION TITLE
Auto backup doesn't delete files

### DISCUSSION THREAD

**Discussion by ottobaer** [mbround18/valheim-docker#225] [Help!] [answered]
Hi, 

I've got auto-backup and removal after 3 days enabled, but the cronjob doen't delete the old backups. It creates them just fine and I have the entry in the /etc/cron.d/ 

```
steam@b10e80ecd557:/etc/cron.d$ cat auto-backup
*/45 * * * * AUTO_BACKUP_REMOVE_OLD=1 AUTO_BACKUP_DAYS_TO_LIVE=3 /usr/sbin/gosu steam /bin/bash /home/steam/scripts/auto_backup.sh >> /home/steam/valheim/logs/auto-backup.out 2>&1
```

I tried running the script manually from the  scripts directory and it creates a backup but won't delete them. 
The owner is the user steam (id 1000) which corresponds to a user on the system, not named steam - is that the problem? 

```
steam@b10e80ecd557:~/backups$ id
uid=1000(steam) gid=1000(steam) groups=1000(steam)
```

```
root@server /opt/valheim-mods # id 1000
uid=1000(chb) gid=1000(chb) groups=1000(chb)
```

Here is my docker-compose.yml 

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 3456:3456/udp
      - 3457:3457/udp
      - 3458:3458/udp
    environment:
      - PORT=3456
      - NAME="Valserver"
      - WORLD="Greenland"
      - PASSWORD="password"
      - TZ=Europe/Paris
      - PUBLIC=0
      - AUTO_UPDATE=0
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/45 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP=1
    volumes:
    - ./valheim-mods/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim-mods/server:/home/steam/valheim
    - ./valheim-mods/backups:/home/steam/backups
```
