### DISCUSSION TITLE
Can I run multiple instances on one server?

### DISCUSSION THREAD

**Discussion by devsi** [mbround18/valheim-docker#238] [Q&A] [answered]
I have some friends itching to play, and right now I have a dedicated server hosting 4 of us. I was hoping to set up a second docker instance (or maybe a second config?) and run it on the same hardware but with a different static IP.

a) What's the ideal way to go about doing this?
b) Would my existing AWS Lightsail instance : `4 GB RAM, 2 vCPUs, 80 GB SSD` be good enough for this? Right now the CPU utilization is really low, and RAM is keeping under 2GB so I feel like it would run, but might get close to its limits. Anyone experienced this set up before?

Thanks friends!

**Comment by mbround18** [comment, marked as answer]
Should be able to run two instances, though you will have to do some docker magic with the second IP address 

https://docs.docker.com/config/containers/container-networking/

**Reply by CosmicHorrorDev** [reply]
4GB may be pushing the limits for two instances depending on how active each of them are. My best advice would be to try it out and be prepared to up the hardware if needed.

**Reply by coreyaboy** [reply]
So I am looking to do similar, but I have a very specific question.

I realize that I can run a second docker instance. That's just a matter of paying attention to port assignments in each config file so nothing overlaps and making sure your router or firewall is configured to co-operate with that. No biggie.

What I'd like is if it were possible to run multiple Worlds in one Docker instance.

The dedicated server on windows appears to almost support such. On the Windows dedicated server you can edit Start_Valheim_Server.bat, duplicating the last line and adjusting the parts that specify the world name, port, password and such and end up with two concurrent Worlds running off of one installation of the dedicated server.

**Reply by mbround18** [reply]
You can do the same with this docker image, I run ~20 servers off this container and all have different port ranges.

**Reply by meg5** [reply]
Can you share an example docker-compose.yml file with more then one instances? I am having trouble getting two to start but I am thinking its a resource issue? Thank you!

**Reply by mbround18** [reply]
@meg5 I can throw one together for you in a day or so, did you want to reduce space requirements? or just run two instances? 

(Reducing space requirements would result in not being able to install mods on the servers without installing it on both servers)

**Reply by coreyaboy** [reply]
I'm also interested in an example docker-compose file for running more than one instance. I can't speak for meg5, but in my use case, the amount of extra space that duplicating the game data a few times really isn't an issue. The flexibility to install different mods on each instance might also give me room to be 'clever' with a thing or two.

In fact, I would so appreciate it that I'm guna go find your tip jar.

**Reply by mbround18** [reply]
Thank you @coreyaboy <3 

## Running Multiple Instances on one Server

```yaml
version: "3"
services:
  valheim-01:
    image: mbround18/valheim:1.3.4
    environment:
      PORT: 2456
      NAME: "Server 01"
      PASSWORD: "Password 01"
      TZ: "America/Los_Angeles"
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      TYPE: Vanilla
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
      - ./server-01/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./server-01/server:/home/steam/valheim
      - ./server-01/backups:/home/steam/backups
  valheim-02:
    image: mbround18/valheim:1.3.4
    environment:
      PORT: 2456
      NAME: "Server 02"
      PASSWORD: "Password 02"
      TZ: "America/Los_Angeles"
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      TYPE: ValheimPlus
    ports:
      - "2459:2456/udp"
      - "2460:2457/udp"
      - "2461:2458/udp"
    volumes:
      - ./server-02/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./server-02/server:/home/steam/valheim
      - ./server-02/backups:/home/steam/backups
  valheim-03:
    image: mbround18/valheim:1.3.4
    environment:
      PORT: 2456
      NAME: "Server 03"
      PASSWORD: "Password 03"
      TZ: "America/Los_Angeles"
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      TYPE: BepInExFull
    ports:
      - "2462:2456/udp"
      - "2463:2457/udp"
      - "2464:2458/udp"
    volumes:
      - ./server-03/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./server-03/server:/home/steam/valheim
      - ./server-03/backups:/home/steam/backups


```
