### DISCUSSION TITLE
Failed to run process!

### DISCUSSION THREAD

**Discussion by yutroc** [mbround18/valheim-docker#240] [Help!]
This is the first time I try with this repo, I am getting this error:
```
[Valheim][root] : ###########################################################################
[Valheim][root] : Valheim Server - Tue Mar  2 14:47:26 -03 2021
[Valheim][root] : Initializing your container...
[Valheim][root] : ###########################################################################
[Valheim][root] : Switching UID and GID
usermod: no changes
[Valheim][root] : 
[Valheim][root] : 
[Valheim][root] : Auto Update Enabled...
[Valheim][root] : Auto Update Schedule: "0 7 * * *"
rm: cannot remove '/home/steam/valheim/logs/auto-update.out': No such file or directory
[Valheim][root] : Auto Backup Enabled...
[Valheim][root] : Auto Backup Schedule: "0 */1 * * *"
rm: cannot remove '/home/steam/valheim/logs/auto-backup.out': No such file or directory
[Valheim][root] : Setting up file systems
[Valheim][root] : Launching as steam...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Valheim Server - Tue Mar  2 14:47:29 -03 2021
[Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000
[Valheim][steam]: Installing Valheim via odin 1.2.0...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Variables loaded.....
[Valheim][steam]: Port: 2456
[Valheim][steam]: Name: ***
[Valheim][steam]: World: ***
[Valheim][steam]: Public: 1
[Valheim][steam]: Password: (REDACTED)
[Valheim][steam]: Running Install...
[ODIN][DEBUG] - Debugging set to true
[ODIN][DEBUG] - Debug mode enabled!
[ODIN][DEBUG] - Launching install command...
[ODIN][DEBUG] - Using default env var 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][DEBUG] - Found env var 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][INFO]  - Installing 896660 to /home/steam/valheim
[ODIN][DEBUG] - Argument set: +login anonymous
[ODIN][DEBUG] - Using default env var 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][DEBUG] - Found env var 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][DEBUG] - Argument set: +force_install_dir /home/steam/valheim
[ODIN][DEBUG] - Argument set: +app_update 896660
[ODIN][ERROR] - Failed to find steamcmd in path
[ODIN][ERROR] - Checking for script under steam user.
[ODIN][INFO]  - Executing: /home/steam/steamcmd/steamcmd.sh .....
[ODIN][INFO]  - Using steamcmd script at /home/steam/steamcmd/steamcmd.sh
[ODIN][DEBUG] - Setting up install command...
[ODIN][DEBUG] - Launching up install command...
[ODIN][ERROR] - Failed to run process!
```
This is my docker compose file that I'm using to start it up:
```
  valheim2:
    image: mbround18/valheim:latest
    container_name: valheim2
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="***"
      - WORLD="***"
      - PASSWORD="***"
      - TZ=America/Santiago
      - PUBLIC=1
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 7 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="0 */1 * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP=1
      - DEBUG_MODE=1
    volumes:
      - /.../valheim2/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /.../valheim2/server:/home/steam/valheim
      - /.../valheim2/backups:/home/steam/backups
```

Am I missing something?
