### DISCUSSION TITLE
Server "not responding" in Steam Servers Favorites

### DISCUSSION THREAD

**Discussion by pbek** [mbround18/valheim-docker#268] [Q&A]
Thank you for this great container! I was playing via the Steam Servers Favorites for some weeks. But somewhere around this week my server was listed "not responding" in the Steam Servers Favorites (port + 1, I also tried port + 0 later in case something changed there). After some debugging I finally found out that I can still connect (and play) when joining the server directly from within the game (port + 0).

Does anyone else have this issue?

```yml
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 31457:31457/udp
      - 31458:31458/udp
      - 31459:31459/udp
    environment:
      - PORT=31457
      - NAME="My Realm"
      - WORLD="My Name"
      - TZ=Europe/Vienna
      - PUBLIC=0
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP=1
    env_file:
      # just for the password
      - ./valheim/variables.env
    volumes:
      - valheim-saves:/home/steam/.config/unity3d/IronGate/Valheim
      - valheim-server:/home/steam/valheim
      - valheim-backups:/home/steam/backups
```
