### DISCUSSION TITLE
adding admins is not working

### DISCUSSION THREAD

**Discussion by ghost** [mbround18/valheim-docker#275] [Help!] [answered]
Heya 

I noticed, that adding an steamID64 to the adminlist.txt does not have any effect.

my adminlist.txt:
```
// List admin players ID  ONE per line
MYSECRETSTEAMID_GOESHERE
```

I did the following:

1. `docker-compose up -d` to install everything (first boot) 
2. login, then hit F2 and go me steamID64 
3. `docker-compose down` to stop the server
4. added my steamID64 to the adminlist.txt in the mounted save dir
5. `docker-compose up -d` 

my docker-compose file:
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PORT: 2456
      NAME: MYSECRET_SERVERNAME
      WORLD: "Dedicated"
      PASSWORD: MYSECRET_SERVERPASSWORD
      TZ:  MYSECRET_SERVERTZ
      PUBLIC: 1
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 2 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      WEBHOOK_URL: MYSECRET_DISCORDSERVER_WEBHOOK
      UPDATE_ON_STARTUP: 0
    volumes:
      - mysupersecretpathtogamedata/valheimserver/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - mysupersecretpathtogamedata/valheimserver/serverfiles:/home/steam/valheim
      - mysupersecretpathtogamedata/valheimserver/backups:/home/steam/backups
```

server is working fine but not recognizing that I should be an admin :/
