### DISCUSSION TITLE
Getting Started? Click Here! How to setup a Valheim Docker server!

### DISCUSSION THREAD

**Discussion by mbround18** [mbround18/valheim-docker#28] [Instructions]
# How to setup a Valheim Docker server

## Prerequisites

- A Linux based server with minimum 2GB of RAM and 10+GB of hard drive space. 
- [Docker installed (Debian-based)](https://docs.docker.com/engine/install/ubuntu/)
- [Docker Compose installed](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-20-04)
- Some knowledge of shell
- SSH Access to your server

## Steps

1. SSH into the server as a non-root user or `su` into non-root user. ([How to create a linux user](https://linuxize.com/post/how-to-create-users-in-linux-using-the-useradd-command/))
2. Make sure they have access to docker `usermod -aG docker ${USER}`
3. Create a new directory `mkdir -p ./valheim`
4. Create a new file called `docker-compose.yml`. See Below.
5. Copy the contents below from the `docker-compose.yml` into your favorite text editor. 
6. Make changes to the docker-compose as necessary.
7. Run the command `docker-compose up --detach`

### `docker-compose.yml`

> You connection port will be +1 of what you supply in the port field. For example, the port the file below is setting up uses port `2456` which means the port you will connect to is `2457`.

> Run the command `id -u`, if your user ID does not equal `1000` you will need to add an environment variable called `PUID` and `PGID` which match your current user. 

```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Created With Valheim Docker"
      - WORLD="Dedicated"
      - PASSWORD="Banana Phone"
      - TZ=America/Chicago
      - PUBLIC=1
      - AUTO_UPDATE=0
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
```

# *Having issues? STOP! DO NOT CREATE A NEW THREAD ON THIS DOCUSSION. Please submit a new discussion in `Q&A` or `Help!`.*

New threads on this discussion where you need help are hard to track and it makes it difficult for others who are running into the same issue to find a solution. 

1. [Click here to start a new discussion](https://github.com/mbround18/valheim-docker/discussions/new)
2. Select the category on the left hand side of the title field to match either `Q&A` or `Help!`. Whichever best describes your issue. 
3. Give it a meaningful title that summarizes your issue in less than 25 words.
4. For the body of the discussion question, give as much details as possible or use the templates below: 

## Help! 

Help discussions are for if your server will not start no matter what you do. Common issues for this are:

*Make sure to click the check mark on the thread that answered your question so that others can easily find the solution*

----

- Wrong `PUID` or `GUID`,
  - Are you running as root? If so you should *NOT* be! Create a new user or log into a non-root user to run the docker-compose. (NOTE: They must be in the `docker` group on linux.)
  - Check your user and group id by running `echo "$(id -u):$(id -g)"`. If this does not return `1000:1000`, then you need to change `PUID` and `GUID` variables  to match. 
- New features aren't working! If you are just running the container, try running `docker-compose pull` and restarting the docker-compose. 
- Container will not start properly! Check the logs, if you see network issues from steam or any other service than you might need to run `docker-compose down` and then run `docker-compose up`. Sometimes the way you have docker and docker-compose configured causes weird network states. 
- Write issues! My container says it has permissions issues writing to specific directories or files! You might have spun the docker-compose up as the wrong user which would cause the volume mounts to be wrong. A simple fix for this is, log into the user you run docker-compose through, then create the directories on your host where you are mounting all the Valheim folders to. Then `docker-compose down && docker-compose up`

### Help Discussion Template

```md
## System Information

Operating System: [What OS you are running this on]
Docker Version: [What docker version, can be found with `docker --version`]
Docker Compose Version: [What docker-compose version you are running, can be found with `docker-compose --version`]
User & Group On Host: `echo "$(id -u):$(id -g)". If`
Are you running with BepInEx? Yes | No

## Issue Description

1. Write up what is the issue you are experiencing. 
2. Provide screenshots as needed. 
3. Always include a log from the server.
```

## Q&A

This is used for general discussion and if you have curious questions about anything going on inside the container; this is a good area to ask that question. 

*Make sure to click the check mark on the thread that answered your question so that others can easily find the solution*

### Q&ADiscussion Template

```md
## Question

Free range to ask pretty much anything <3 
```

**Comment by ragingdave** [comment]
"Make content included"? Can you elaborate on what that means?

**Reply by ghost** [reply]
> "Make content included"? Can you elaborate on what that means?

nano docker-compose.yml

then copy below and paste

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    environment:
      - PORT=2456
      - NAME="Created With Valheim Docker"
      - PASSWORD="Banana Phone"
      - TZ=America/Chicago
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
    - ./saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./server:/home/steam/valheim
```

then save

**Reply by AtroposOrbis** [reply]
Odin is failing to write....
![image](https://user-images.githubusercontent.com/8618455/107669288-94425480-6c5f-11eb-9de1-acdad29f82f8.png)

**CONTENTS OF DOCKER-COMPOSE**
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2460:2462/udp
    environment:
      TZ: "America/New_York"
      NAME: "New Abyssia"
      WORLD: "New Abyssia"
      PORT: "2460"
      PUBLIC: "1"
      PASSWORD: "REDACTED"
      AUTO_UPDATE: "1"
      PUID: "1000"
      PGID: "1000" 
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim

**Reply by mbround18** [reply]
@AtroposOrbis This looks like your user id and group id do not match the dockers user & group id. Are you on windows? or linux? 

If on linux when you run `id -u` the number it spits out should be the number you supply as an environment variable called `PUID`

**Reply by mbround18** [reply]
> "Make content included"? Can you elaborate on what that means?

Hey I have updated it to be more descriptive <3

**Reply by AtroposOrbis** [reply]
> @AtroposOrbis This looks like your user id and group id do not match the dockers user & group id. Are you on windows? or linux?
> 
> If on linux when you run `id -u` the number it spits out should be the number you supply as an environment variable called `PUID`

When I updated the compose file and attempted another run, the same error occurred...
![image](https://user-images.githubusercontent.com/8618455/107672151-9a860000-6c62-11eb-828f-27b1c06e01c9.png)

![image](https://user-images.githubusercontent.com/8618455/107671983-67dc0780-6c62-11eb-930a-be8295df67c2.png)

**Comment by pasisavolainen** [comment]
It would be convenient to have `restart: always` (on the `image` level) included in the yml

**Reply by AtroposOrbis** [reply]
That would be excellent indeed. +1

**Reply by magenbrot** [reply]
I have ```restart: unless-stopped``` in all my docker-compose services

**Comment by carrascodev** [comment]
@mbround18 what is the difference to use Odin over docker-compose. Would it use the same container / volumes, if I already have world within docker-compose? I am asking this because I am very confuse on how to use Odin haha

**Reply by CosmicHorrorDev** [reply]
Odin is used internally by the docker container. There's no need to interact with it directly if that's what you're asking.

**Reply by mbround18** [reply]
As @LovecraftianHorror said, Odin is purely there for internal use. If you need it, you can use it to stop/start/update your server manually but there are many provided ways to handle that. Including simply starting, stopping, and restarting the container itself.

**Comment by TheDakk** [comment]
Apologies, new the whole docker/automation arena. When you make updates to the docker image and we do a pull, does it wipe or reset the contents of Valheim server inside? Or is it all separated? 

Also, does the Auto Update feature cleanly shutdown the server? I know there’s a world wipe bug out there. Automated backups?

 Thanks!

**Reply by mbround18** [reply]
It is all separate :) the content you are saving, provided you followed the guide, saves only the data you are using. When you pull a new version of the image it includes a swath of features as you can see from the readme content. Each PR we do gets tested thoroughly in automated tests and manually by myself with my staging servers. 


Each pull should be backwards compatible with the prior release and each added feature needs to be in an acceptable state before it gets merged in. 

For the auto update function, you should be good to go <3 as for automated backups, thats a feature I wont bake into the docker container as its best practices to handle that on your own and keep the docker container light.

**Reply by mbround18** [reply]
The only thing to watch out for, is if you see a patch pull request come up from me which means something did not go right in the latest push when it got pushed up to docker hub. Although, when this happens I am right on top of it as I never deploy to production and go away from my desk even if its super early morning. (ex rn :P being 12 am with my latest changes failing in CI.  Should have that fixed in a moment.) 

I try to make sure this image is clean, always working, and resilient to failure <3

**Reply by TheDakk** [reply]
Thanks for this information, much appreciated. How would you suggested we back just the world DB file then? There’s another image out there that has something implemented:
```
https://github.com/lloesche/valheim-server-docker 
```

**Reply by mbround18** [reply]
> Thanks for this information, much appreciated. How would you suggested we back just the world DB file then? There’s another image out there that has something implemented:
> 
> https://github.com/lloesche/valheim-server-docker

Backup discussion is over at #96 <3 and I am implementing the feature atm

**Comment by JeffMings** [comment]
This Docker image really makes it easy to run a Valheim dedicated server.  The docs are good, but I would like to suggest a more detailed list.  Here's what I did  (This is from my notes and recollection, there may be errors) :

- Prepped a host/"containing" server.  I used Ubuntu 20.04.2 and installed all of the updates.
I installed Docker and then docker-compose.  Straight from Ubuntu repos.
- Setup SSH into the Ubuntu box
- As root, created a user as a member of the Docker group.  Something like:
useradd -g docker -c "Docker Guy" -s /bin/bash -m dockerguy   and set a pass-  passwd dockerguy
- Became the new user-   su - dockerguy
- Created the folder for the Docker container to interact with-  mkdir ./valheim
- Got uid for user:
```sh
id -u     >  1010
```
- Created the Yaml file for docker-compose to create/update the container:
```sh
nano -w docker-compose.yml  #  with contents to reflect uid of dockerguy:
```
```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="ValenHeimsDay"
      - WORLD="ValenHeimsDay"
      - PASSWORD="1234567890"
      - TZ=Pacific/Honolulu
      - PUBLIC=1
      - AUTO_UPDATE=0
      - PUID=1010
      - PGID=1010
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
```
- Started container as dockerguy WITHOUT detach command to watch the image output:
```sh
docker-compose up  
```
(worked, saw the server connect message)

- Started with detach param `docker-compose up --detach` and then checked to see if it I could see it running on my internal lan:
```sh
nmap -sU -p 2455-2459  10.0.0.123
```
(returns something like)

| PORT       |  STATE             | SERVICE |
|-----------|---------------|---------|
| 2455/udp | filtered           | unknown |
| 2456/udp | closed            | unknown |
| 2457/udp | open\|filtered | rapido-ip |
| 2458/udp | closed            | unknown |
| 2459/udp | filtered           | unknown |


- Used  docker stats command to check resource utilization and get container "handle":

| CONTAINER ID |  NAME | CPU % | MEM USAGE / LIMIT | MEM % | NET I/O | BLOCK I/O | PIDS |
|-----------------|--------|--------|-----------------------|---------|----------|------------|------|
|11302844c3b3  |  dockerguy_valheim_1 | 113.79% | 1.587GiB / 7.455GiB | 21.29% | 1.15GB / 665MB | 156kB / 3.55MB | 38

- Connected to container with command   docker container exec -it dockerguy_valheim_1 /bin/bash
- Checked environment variables to make sure all was there with  env command  - all looks good.
- Set up port forwarding of UDP packets to ports 2456-2458 to host server.
- Checked from one of my external servers with nmap to see if it port forwarding was working.  Still got:

```txt
2457/udp open|filtered rapido-ip   from outside IP - working.
```

- Ran Valheim - name didn't show up in server list, so I used  Steam's View > Server to add my external IP as a favorite and connect to it.

Works!  Wasted many hours with friend  :D

**Reply by mbround18** [reply]
@JeffMings formatted your comment <3 thanks for the write up <3

**Reply by joryirving** [reply]
Does this mean that if I want to run it on port 2456, I need to set the port to 2455 in the docker compose? nmap shows the proper rapido-ip internal to my network, but I'm struggling to have someone connect to my instance.

**Reply by mbround18** [reply]
> Does this mean that if I want to run it on port 2456, I need to set the port to 2455 in the docker compose? nmap shows the proper rapido-ip internal to my network, but I'm struggling to have someone connect to my instance.

No, if you set the port to 2456 in the environment variable then if you connect via the favorites listhttps://github.com/mbround18/valheim-docker/discussions/51 you will connect to 2457. However, if you use the in game function of join by IP you will use 2456.

**Reply by Napitok1987** [reply]
Hello!
Please, help me. After executing on my local machine:
`nmap -sU -p 2455-2459 mydedicatedserveipaddress`
I've got:
```
2455/udp open|filtered wago-io-system
2456/udp closed        altav-remmgt
2457/udp closed        rapido-ip
2458/udp closed        griffin
2459/udp open|filtered community
```
It looks like something went wrong and 2457/udp closed rapido-ip should be open, but it's closed. Am I right? And what should I do in this case?

**Comment by ghost** [comment]
I'm stucked here https://i.imgur.com/fZqjqo9.png

1 GB Memory / 25 GB Disk / SGP1 - Docker 19.03.12 on Ubuntu 20.04

But my 4 GB Memory / 80 GB Disk / SGP1 - Docker 19.03.12 on Ubuntu 20.04 Worked fine.

**Reply by CosmicHorrorDev** [reply]
1GB will be too little to run the server. Mine is using a bit over 2GB currently

**Reply by JeffMings** [reply]
If you want to stop the output of the docker container, hit Ctrl-C.  Then restart it with the --detach parameter.

**Reply by TheDakk** [reply]
Should be running "docker-compose up --detach" every time reboot the server? If so, anyway to auto start when the Linux server reboots? I assume Odin is used once you detach to interact with the Valheim server? Apologies again for the n00b questions :)

**Reply by mbround18** [reply]
You are spot on with Odin, it handles all interactions with the valheim server inside the container and you dont need to interact with it :) 

As for the docker-compose, you can add 
```yml 
restart: always
```
under the valheim service which should restart the server once your system reboots.

**Reply by pbek** [reply]
For me even 2GB were too little... And I never got an error message, which made debugging a lot harder...

**Comment by CosmicHorrorDev** [comment]
Allocating too little RAM seems to be a very common problem. Do you think its worth adding a changing "A Linux based server" to "A Linux based server with at least 2GB of spare RAM" or something along those lines?

It might also be worth setting up a common troubleshooting discussion as well so that people can check there if they are having problems.

**Reply by mbround18** [reply]
I added a memcheck to the containers entrypoint 
https://github.com/mbround18/valheim-docker/pull/121

**Reply by pbek** [reply]
For me even 2GB were too little... And I never got an error message, which made debugging a lot harder...
I just never got a `Game server connected`. After moving to a server with more RAM everything worked fine.

**Comment by kevintrankt** [comment]
Working great on my end (Ubuntu 18.04 GCP) - thank you for this!

**Comment by ScottKane** [comment]
My server just bombs out after about a minute with nothing special in the output and no log created on my mounted volume.

![valheim server](https://user-images.githubusercontent.com/17254944/108435978-79b14200-7242-11eb-96e1-1eda1dbc5117.png)

``` yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="GSL Valheim"
      - WORLD="Dedicated"
      - PASSWORD="PASSWORD"
      - TZ=Europe/London
      - PUBLIC=1
      - AUTO_UPDATE=0
      - PUID=1001
      - PGID=1001
    volumes:
    - /opt/valheim:/home/steam/.config/unity3d/IronGate/Valheim
    - /opt/valheim:/home/steam/valheim
```

Any ideas?

**Reply by CosmicHorrorDev** [reply]
Does `docker ps` say the container is unhealthy?

**Reply by ScottKane** [reply]
This is what happens in docker ps

![1](https://user-images.githubusercontent.com/17254944/108438718-c3505b80-7247-11eb-9f42-44fbab7e1b55.png)
![2](https://user-images.githubusercontent.com/17254944/108438725-c5b2b580-7247-11eb-9498-ea066323e28e.png)

**Reply by TheDakk** [reply]
What OS and version are you using?

**Reply by ScottKane** [reply]
Ubuntu 18.04.2

**Reply by TheDakk** [reply]
I’m using 20.x with no issues. May be try running OS updates?

sudo apt update && sudo apt upgrade

**Reply by ScottKane** [reply]
I think I have gotten it working, I just deleted the image and reran the compose and it seems to have worked

**Reply by ScottKane** [reply]
But yeah I should run some updates, it's just an old dev box

**Reply by CosmicHorrorDev** [reply]
I wasn't able to reproduce with essentially the same config. It looks like its failing around the time where it's downloading the server. Is `/opt/valheim` full or is anything downloaded there? It should be roughly 1GB

**Reply by TheDakk** [reply]
Wondering if he was running into this issue with the older OS:

https://github.com/ValveSoftware/steam-for-linux/issues/6692

**Reply by mbround18** [reply]
@ScottKane if this is still an issue, can you move this to a new discussion please?

**Comment by PiotrZadka** [comment]


**Reply by PiotrZadka** [reply]
Server doesn't start or appear on the list

**Reply by mbround18** [reply]
This needs to go under a new discussion. Please create a new discussion not a new thread.

**Comment by uttambharadwaj** [comment]
I am unable to pull in save files for some reason. Any older save file seems to get run over. Is there any specific way to do this?

**Reply by mbround18** [reply]
Please follow directions and open a `help!` discussion <3

**Comment by lafrad** [comment]
I'm curious to know if this would support *multiple* dedicated servers, so we could host worlds for different groups of friends or adventures...  Is there anything here that would stop that?

**Reply by CosmicHorrorDev** [reply]
You can manage this by running multiple containers from this image and using different mounts and ports for the different servers.

**Reply by lafrad** [reply]
I'd imagine tweaking the compose to have a "valheim-1" and "valheim-2" with different critical info would do the trick....

**Reply by lafrad** [reply]
Looks like docker is fine with it, but the Valheim server is not.....     the quest continues,,,,

**Reply by CosmicHorrorDev** [reply]
As long as the ports are different (say start one at the normal 2456 and the other at 3456) and the mount points are different you should be able to directly connect to either one. I've run two servers simultaneously when testing and didn't have any issues

**Comment by kpenfound** [comment]
Thanks for all the hard work!

I've been using this project with my [terraform module](https://github.com/kpenfound/valheim-server) to run my Valheim server  on AWS since the beginning! Introspection into the server with Odin is really cool

**Reply by mbround18** [reply]
Hey @kpenfound amazing work!!

**Comment by mikart143** [comment]
Hi!
Great work!
I am having small trouble with running this on Oracle Ampere Free server.
When I start server all I receive is :
```
ln: failed to create symbolic link '/home/steam/.steam/root': No such file or directory
ln: failed to create symbolic link '/home/steam/.steam/steam': No such file or directory
```

My docker-compose.yaml
```yaml
version: "3"
services:
  valheim:
    privileged: true
    image: mbround18/valheim:latest
    platform: linux/amd64

    stop_signal: SIGINT
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      NAME: "XXXXX"
      WORLD: "Dedicated"
      PASSWORD: "XXXXX"
      TZ: "Europe/Warsaw"
      PUBLIC: 0
      ENABLE_CROSSPLAY: 1
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      UPDATE_ON_STARTUP: 1
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
```

Full log:
```
[Valheim][root] : Navigating to steam home...
[Valheim][root] : Launching as steam...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Valheim Server - Sun Apr  2 07:38:00 PM Europe 2023
[Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000
[Valheim][steam]: Installing Valheim via odin 1.5.3...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Variables loaded.....
[Valheim][steam]: Port: 2456
[Valheim][steam]: Name: Pierdolnik na ARM
[Valheim][steam]: World: Dedicated
[Valheim][steam]: Public: 0
[Valheim][steam]: With Crossplay: 1
[Valheim][steam]: Password: (REDACTED)
[Valheim][steam]: Running Install...
[ODIN][INFO]  - Installing 896660 to /home/steam/valheim
[ODIN][INFO]  - steamcmd found in path
ln: failed to create symbolic link '/home/steam/.steam/root': No such file or directory
ln: failed to create symbolic link '/home/steam/.steam/steam': No such file or directory
[ODIN][ERROR] - Exited with http code: 1
```
