### DISCUSSION TITLE
Trouble importing world from previous docker install

### DISCUSSION THREAD

**Discussion by Aigis** [mbround18/valheim-docker#280] [Help!] [answered]
So I'm having some problems migrating my world from a previous docker server to this one (The other docker image doesn't have mod support). No matter what I seem to do it just does not pull my existing world, and I was hoping someone could help point out if I have something wrong. So my host OS is Debian and it doesn't matter if I use this through docker compose or through Portainer stacks, same situation. I have downloaded my world files to my PC, created a new user in the docker group named "valheim" (PUID and PGID are 1001) and then run this docker compose (a few fields edited of course, the fields with xs)

```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PORT: 2456
      NAME: "x"
      WORLD: "x"
      PASSWORD: "x"
      TZ: "America/New_York"
      PUBLIC: 0
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      WEBHOOK_URL: "x"
      UPDATE_ON_STARTUP: 1
      PGID: 1001
      PUID: 1001
    volumes:
      - /home/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /home/valheim/server:/home/steam/valheim
      - /home/valheim/backups:/home/steam/backups
```

I then check the start_server.sh to make sure it reflects the name, world and password (world name is absolutely correct, as a sanity check I have copy and pasted it's name), restart the docker container, log in (It takes the password I set, so I figure my settings should be correct) and the world it spawns me in is not the one from my old/existing server. The world files were uploaded via sftp with the valheim user, so I don't imagine permissions should be a problem. Am I missing something silly here?

**Comment by mbround18** [comment]
When you log into the new world, does it create files on your system with a different world name or just overwrite your existing world?

**Reply by Aigis** [reply]
So I just re-spun a new stack with the same steps as before, with the same results. The container can absolutely write to the /home/valheim/saves folder because the prefs file and worlds directory show as last edited two minutes ago, but the fwl and db files from my existing world are last edited 30 or so minutes ago. It did create a new db and fwl file without everything being in all caps, which is interesting because nowhere have I referenced that world or name. Existing files are untouched. 
[logs.txt](https://github.com/mbround18/valheim-docker/files/6119613/logs.txt)
Here's the start of the log file if that helps

**Reply by CosmicHorrorDev** [reply]
Hm, so what I'm hearing is that it's creating a new world with the same name but different capitalization?

What happens if you remove the new files it created and rename your old files to match its format?

**Reply by Aigis** [reply]
So, the existing world is "SCATMANSWORLD", the fwl and db created by this container were "ScatmansWorld", replacing these files with the previous world still spawns me in on the newly created world, it has not written a to the newly replaced files since I dropped them on my server.

**Reply by CosmicHorrorDev** [reply]
I'm really not sure what the issue would be as long as `WORLD` in your compose file is actually set to `SCATMANSWORLD` (can't check since it's redacted).

Just to be sure there wasn't some weirdly specific case I ran a test server with the same world name and it created all the world files that I expected

```txt
❯ ls saves/worlds
SCATMANSWORLD.db  SCATMANSWORLD.fwl  SCATMANSWORLD.fwl.old
```

**Reply by Aigis** [reply]
Yeah, I'm at a loss too, I'm half tempted to just dump the existing world at this point, sadly
```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PORT: 2456
      NAME: "SCATMANSWORLD"
      WORLD: "SCATMANSWORLD"
      PASSWORD: "x"
      TZ: "America/New_York"
      PUBLIC: 0
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      WEBHOOK_URL: "x"
      UPDATE_ON_STARTUP: 1
      PGID: 1002
      PUID: 1002
    volumes:
      - /home/valdock/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /home/valdock/valheim/server:/home/steam/valheim
```

This is the entirety of my compose file, with the password and webhook x'd out naturally.
