### DISCUSSION TITLE
Lag Lag Lag

### DISCUSSION THREAD

**Discussion by JohnKreese** [mbround18/valheim-docker#317] [Help!] [answered]
Has anyone noticed worse lag since the last 2 updates?  It is virtually unplayable in our small village at the moment. Low frame rates, birds just hanging in midair, animals glitching etc.

Is there any way to increase the recv rate without editing any .dll files? How are you guys combatting this issue?

Thanks for any tips.

**Comment by mbround18** [comment, marked as answer]
I am using ValheimPlus to combat the issue currently.

**Reply by JohnKreese** [reply]
> I am using ValheimPlus to combat the issue currently.

I was hoping not to install any mods (had bad experiences with Ark), but as the devs aren't saying much I might have to.

**Reply by mbround18** [reply]
Luckily, its fairly straight forward with this repo :P Just add an ENV variable called TYPE and set the value to ValheimPlus. Than start your server. After it downloads all the needed files, change the config as you need in the `/home/steam/valheim/BepInEx/config` folder to what youd like and give it a restart :)

**Reply by JohnKreese** [reply]
I don't seem to ever get a BepInEx folder. I started server (docker-compose up --detach) with the following config:

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="***"
      - WORLD="***"
      - PASSWORD="***"
      - TZ=Europe/London
      - PUBLIC=1
      - AUTO_UPDATE=1
      - TYPE=ValheimPlus
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
```

Did I miss something?
