### DISCUSSION TITLE
Status HTTP-Server

### DISCUSSION THREAD

**Discussion by TheMBeat** [mbround18/valheim-docker#318] [Q&A] [answered]
How can I make a request to the server to get the status as json?

**Comment by Marcus-Rise** [comment, marked as answer]
A few days ago I dig in this question too.
You need to define env var `HTTP_PORT`, make server public via env var `PUBLIC: 1`, map selected tcp port 
Then you can ping to public ip address of your server with path `/status`

`docker-compose.yml`

```yaml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2459:2459/tcp
      ...
    env:
      - HTTP_PORT: 2459
      - PUBLIC: 1
      ...
```

```bash
$ curl {PUBLIC_SERVER_IP_ADDRESS}:2459/status
```

Additionally you can try to extract port number to env var in `.env`
