### DISCUSSION TITLE
Using CAdvisor, Prometheus, and Grafana To Build A Valheim Dashboard

### DISCUSSION THREAD

**Discussion by bforbis** [mbround18/valheim-docker#330] [Instructions]
I would like to share some information on how to setup a Grafana dashboard to track information about your running Valheim server. This Grafana dashboard keeps track of the following information:

- CPU Usage
- Memory Usage
- Server Online Status
- Player Online Count

You can download the Grafana dashboard at https://grafana.com/grafana/dashboards/14123

**Docker Compose**
The first step is to setup your Valheim docker compose to include CAdvisor, Prometheus, and Grafana

```yaml
version: "2.4"
services:
  valheim:
    image: mbround18/valheim:latest
    container_name: valheim
    restart: unless-stopped
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
      - 2459:2459/tcp
    environment:
      PORT: 2456
      HTTP_PORT: 2459
      PUBLIC: 1
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090/tcp
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000/tcp
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    volumes:
      - grafana-provisioning:/etc/grafana/provisioning:ro
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - 8080:8080/tcp
    privileged: true
    command:
      # Defaults to 1s interval, 5s interval for reduced cpu
      - "-housekeeping_interval=5s"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
```
**Prometheus Config**

You should also have a `prometheus.yml` config file bind mounted to your prometheus container. This will be setup to scrape both your CAdvisor container and your Valheim HTTP Status server `/metrics` endpoint served at your `HTTP_PORT`

```yaml
scrape_configs:
  - job_name: cadvisor
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: valheim
    static_configs:
    - targets: ['valheim:2459']
```

**Grafana Datasource Provisioning**
You should also setup Grafana to automatically setup your prometheus server as a datasource. You can do this by creating a datasource provisioning file
```yaml
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    editable: false
    url: http://prometheus:9090
```
