### DISCUSSION TITLE
Auto-update and shutdown broken on Linux systems

### DISCUSSION THREAD

**Discussion by Finomnis** [mbround18/valheim-docker#443] [Help!] [answered]
I realized that server auto-updates do not work for me.
I found out that the 'shutdown' step of odin does nothing in my docker.

After a little digging, I found out that many linux based systems have trouble handling process names with more than 15 characters.
Reducing the process search to 15 characters fixed the problem for me.

I created a pull request as a change suggestion to fix this problem: https://github.com/mbround18/valheim-docker/pull/441
I had a little trouble naming stuff so be very welcome to rework this fix suggestion.

**Comment by mbround18** [comment, marked as answer]
Huh, weird, I can look into the auto update function and thank you for adding an update for #441 ! :)

**Reply by Finomnis** [reply]
The update itself works, just to clarify. It tries to shut down the server, *thinks* the server is shut down, runs the update and starts the server again. But because the server never shut down properly, 'starting it' does nothing. Odin reports a successful update, and the new version is on the disk, but in RAM the old process is still running.

Happens consistently on my system.:
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

$ uname -a
Linux docker 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I'm running portainer, but it should work with normal docker-compose just as consistently:
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:1.4.3
    container_name: valheim
    restart: always
    stop_grace_period: 1m
    ports:
      - "2456-2458:2456-2458/udp"
    environment:
      - PORT=2456
      - NAME="<...>"
      - WORLD="<...>"
      - PASSWORD="<...>"
      - TZ=Europe/Berlin
      - PUBLIC=1
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="15 * * * *"
      - WEBHOOK_URL="https://discord.com/api/webhooks/<...>"
    volumes:
      - config:/home/steam/.config/unity3d/IronGate/Valheim
      - server:/home/steam/valheim
      - steamcmd:/home/steam/steamcmd
volumes:
  steamcmd:
  server:
  config:
```
