### DISCUSSION TITLE
Unable to locate odin after makers command

### DISCUSSION THREAD

**Discussion by secretsoup** [mbround18/valheim-docker#468] [Help!] [answered]
Trying to install odin on my ubuntu home server. The install itself seemed to go OK, however doing the copy of the odin debug file doesn't work because it can't find the executable. Using locate to search for odin shows nothing there either. No errors on previous step, so at a loss as to where Im messing up:

  Compiling cargo-make v0.35.1
    Finished release [optimized] target(s) in 1m 52s
  Installing /home/bo/.cargo/bin/cargo-make
  Installing /home/bo/.cargo/bin/makers
   Installed package `cargo-make v0.35.1` (executables `cargo-make`, `makers`)
bo@homeserver:~/valheim/valheim-docker$ makers -e production release
[cargo-make] INFO - makers 0.35.1
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: release
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Build Done in 3.37 seconds.
bo@homeserver:~/valheim/valheim-docker$ chmod +x ./target/debug/odin
chmod: cannot access './target/debug/odin': No such file or directory
bo@homeserver:~/valheim/valheim-docker$ locate -i odin

SteamCMD is installed.

**Comment by mbround18** [comment, marked as answer]
@shubinsb is ` /home/bo/.cargo/bin/` in your path? you might need to edit your bashrc and add it to your path variable.

**Reply by secretsoup** [reply]
Yea it's already in the path

```
bo@homeserver:~$ echo $PATH
/home/bo/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Reply by mbround18** [reply]
@shubinsb have you tried executing `cargo make build` ? in the root of the project dir?

**Reply by samtietze** [reply]
I'm running into this issue as well. I attempted to reduce the CPU cores I was providing to Docker (from 3 to 2), and upon restarting the server encountered an error where steamcmd couldn't figure out my CPU speed (i've seen some various posts about this, `export CPUMHZ=2500` etc etc, but _anyway_). So I deleted everything except my `docker-compose.yml` and my tmp/backups and tmp/saves folders, then re-cloned this repo and went for a reinstall. I also deleted all listed images in Docker Desktop, though I don't know if that was needed.

When I reinstall (with `docker-compose up --build`), I see the following eventually:

```
valheim_1  | [Valheim][steam]: Valheim Server - Sun 24 Oct 2021 03:13:07 PM CDT
valheim_1  | [Valheim][steam]: STEAM_UID 501 - STEAM_GUID 501
valheim_1  | [Valheim][steam]: Installing Valheim via odin 1.4.3...
valheim_1  | [Valheim][steam]: ###########################################################################
valheim_1  | [Valheim][steam]: Variables loaded.....
valheim_1  | [Valheim][steam]: Port: 2456
valheim_1  | [Valheim][steam]: Name: 
valheim_1  | [Valheim][steam]: World:
valheim_1  | [Valheim][steam]: Public: 1
valheim_1  | [Valheim][steam]: Password: (REDACTED)
valheim_1  | [Valheim][steam]: Running Install...
valheim_1  | [ODIN][INFO]  - Installing 896660 to /home/steam/valheim
valheim_1  | [ODIN][INFO]  - steamcmd found in path
valheim_1  | [ODIN][INFO]  - Exited with http code: 1
valheim_1  | cp: cannot stat '/home/steam/steamcmd/linux64/steamclient.so': No such file or directory
valheim_1  | [Valheim][steam]: Initializing Variables....
valheim_1  | [ODIN][ERROR] - Failed to find server executable! Please run `odin install`
tv-mac:valheim-docker sam$ docker-compose ps
       Name                 Command             State               Ports       
--------------------------------------------------------------------------------
valheim-              /apps/odin            Exit 0                              
docker_odin_1         --version                                                 
valheim-              /bin/bash             Up (unhealthy)   0.0.0.0:2456->2456/
docker_valheim_1      /entrypoint.sh /                       udp, 0.0.0.0:2457->
                      ...                                    2457/udp, 0.0.0.0:2
                                                             458->2458/udp      
```

I might be ignorant of some PATH stuff. This is a macOS install using Docker. PATH is as follows:
```
sam$ echo $PATH
/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Here's the docker-compose:

```
version: "3"
services:
  odin:
    image: mbround18/odin:latest
    build:
      context: .
      dockerfile: ./Dockerfile.odin
    volumes:
      - odin-output:/data/odin/target/release
  valheim:
    depends_on:
      - odin
    image: mbround18/valheim:latest
    environment:
      - PORT=2456
      - NAME="xxx"
      - PASSWORD="xxx"
      - WORLD="xxx"
      - PUBLIC=1
      - PUID=501
      - PGID=501
      - TZ=America/Chicago
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 4 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS=1
      - AUTO_UPDATE_PAUSE_WITH_PLAYERS=1
      - TYPE=Vanilla
    build:
      context: .
      dockerfile: ./Dockerfile.valheim
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
      - ./tmp/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./tmp/server:/home/steam/valheim
      - ./tmp/backups:/home/steam/backups
      - odin-output:/home/steam/.odin
    restart: always
volumes:
  odin-output:
```

Hope this helps to learn what might be wrong. Everything worked perfectly before bringing the server down and up.
