### DISCUSSION TITLE
The server appears to hang

### DISCUSSION THREAD

**Discussion by Richi2293** [mbround18/valheim-docker#47] [Q&A] [answered]
Hi,

i am trying to start the server on Dokku (via Github docker repository), and i have these final logs:

![image](https://user-images.githubusercontent.com/5848941/107638131-754bbe80-6c6f-11eb-8ca3-cd362f98b318.png)

Basically it seems like it stays that way forever.
What could it be?

Thanks

-----------

Server:
Digitalocean 1 GB Memory / 25 GB Disk

-----------

My docker-compose:

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      # PUID: 0
      # PGID: 0
      - TZ="Europe/Rome"
      - NAME="La Stamberga Del Disagio"
      - WORLD="Dedicated"
      - PORT="2456"
      # PUBLIC: "1"
      - PASSWORD="mypassword"
      # AUTO_UPDATE: "0"
    volumes:
      - ./saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./server:/home/steam/valheim
```

-------------

I also tried to boot locally (via docker-compose) and it gives me this error in the output.log:

```
Found path: /home/steam/valheim/valheim_server.x86_64
Mono path[0] = '/home/steam/valheim/valheim_server_Data/Managed'
Mono config path = '/home/steam/valheim/valheim_server_Data/MonoBleedingEdge/etc'
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/home/steam/valheim/valheim_server_Data/Managed/mono/4.5/mscorlib.dll' directory.
```
