### DISCUSSION TITLE
[ODIN][ERROR] - Failed to find server executable! Please run `odin install`

### DISCUSSION THREAD

**Discussion by mike-jewell** [mbround18/valheim-docker#495] [Help!]
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PORT: 2456
      NAME: "Created With Valheim Docker"
      WORLD: "Dedicated"
      PASSWORD: "Banana Phone"
      TZ: "America/Chicago"
      PUBLIC: 1
    volumes:
      - /volume1/docker/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /volume1/docker/valheim/server:/home/steam/valheim
```

Hi there

I had been running this image for a while but turned it off for a month or so.  When I've come back to using it again I am now seeing the following:

```
valheim_1  | [Valheim][root] : ###########################################################################
valheim_1  | [Valheim][root] : Valheim Server - Sun 12 Dec 2021 03:33:31 PM CST
valheim_1  | [Valheim][root] : Initializing your container...
valheim_1  | [Valheim][root] : You must be in development. Good luck!
valheim_1  | [Valheim][root] : ###########################################################################
valheim_1  | [Valheim][root] : Switching UID and GID
valheim_1  | [Valheim][root] : usermod: no changes
valheim_1  | [Valheim][root] :
valheim_1  | [Valheim][root] : Setting up file systems
valheim_1  | [Valheim][root] : Navigating to steam home...
valheim_1  | [Valheim][root] : Launching as steam...
valheim_1  | [Valheim][steam]: ###########################################################################
valheim_1  | [Valheim][steam]: Valheim Server - Sun 12 Dec 2021 03:33:34 PM CST
valheim_1  | [Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000
valheim_1  | [Valheim][steam]: Installing Valheim via odin 1.4.3...
valheim_1  | [Valheim][steam]: ###########################################################################
valheim_1  | [Valheim][steam]: Variables loaded.....
valheim_1  | [Valheim][steam]: Port: 2456
valheim_1  | [Valheim][steam]: Name: Created With Valheim Docker
valheim_1  | [Valheim][steam]: World: Dedicated
valheim_1  | [Valheim][steam]: Public: 1
valheim_1  | [Valheim][steam]: Password: (REDACTED)
valheim_1  | [Valheim][steam]: Running Install...
valheim_1  | [ODIN][INFO]  - Installing 896660 to /home/steam/valheim
valheim_1  | [ODIN][INFO]  - steamcmd found in path
valheim_1  | [ODIN][INFO]  - Exited with http code: 1
valheim_1  | cp: cannot stat '/home/steam/steamcmd/linux64/steamclient.so': No such file or directory
valheim_1  | [Valheim][steam]: Initializing Variables....
valheim_1  | [ODIN][ERROR] - Failed to find server executable! Please run `odin install`
```

I'm running this on my synology x86, with docker version 20.10.3.  I have tried to enter the container but it crashes out before I can attempt to do the steps mentioned in this discussion:

https://github.com/mbround18/valheim-docker/discussions/481

I have tried this against my old volumes, and new volumes.  I have also ensured that it is the latest docker image with a docker pull.  Any help would be greatly appreciated.  Thanks
