### DISCUSSION TITLE
Can't see your server in the server list? Click Here!

### DISCUSSION THREAD

**Discussion by mbround18** [mbround18/valheim-docker#51] [Instructions]
# So you can not see your server in the server list? 

Fear not my friend! You can direct connect to your server by following the steps below:

## Open Steam, click View, then click Servers

![View Servers](https://i.imgur.com/TJ66lO7.png)

## Click Favorites and Add A Server

![Add A Server](https://i.imgur.com/rrZuxnN.png)

## Enter the `ip:port` of your server and click Add This Address To Favorites

> Note: in this example the environment port is set to `2456` which means the port you should be connecting to is `2457`. The port you always connect to will be +1 of the port you set. 

![Add to Favorites](https://user-images.githubusercontent.com/12646562/107899446-1c8c5800-6ef3-11eb-9e48-affe72d4addc.png)

## Finally, click refresh and double click on your server

![image](https://user-images.githubusercontent.com/12646562/107712666-0a0de680-6c87-11eb-8d33-c61005c95a92.png)

>NOTE: If you have a password on your server it will prompt you twice for it!

**Comment by surister** [comment]
This is great but, any chance it'll appear in the server list?

**Reply by mbround18** [reply]
It technically should but it depends on your networking, NAT, and other configurations.

**Reply by surister** [reply]
I fixed it, one of the three ports wasn't correctly open.

**Comment by Erwyn** [comment]
I have set PUBLIC=1 in my docker-compose.yml file, I have:

```
    valheim:
        image: mbround18/valheim:latest
        container_name: valheim
        ports:
            - "2456:2456/udp"
            - "2457:2457/udp"
            - "2458:2458/udp"
        environment:
            - NAME=Iprogon Empire
            - WORLD=Dedicated
            - PORT=2456
            - PUBLIC=1
            - PASSWORD=REDACTED
            - TZ=Europe/Paris
            - AUTO_UPDATE=0
        volumes:
            - valheim-saves:/home/steam/.config/unity3d/IronGate/Valheim
            - valheim-data:/home/steam/valheim
```

Those are the ports given by `docker ps`
```
0.0.0.0:2456-2458->2456-2458/udp
```

and ufw:
```
2456                       ALLOW       Anywhere
2457                       ALLOW       Anywhere
2458                       ALLOW       Anywhere
```

But still, cannot see my server in the list. What I don’t get is when I first spawned this server (the 2nd of February) it was listed but not anymore. Something changed ? I checked the source code and the `-public 1` seems to be effectively passed, so I’m kinda out of ideas.

**Comment by zupd** [comment]
Remember to add the server using port 2457, (1 above the port in docker-compose) and not 2456 as stated above in the screenshots :)

**Reply by zupd** [reply]
hmm never mind. I tried it because 2456 did not work. but then I just tried all 3 ports again, and it seems 2456 actually worked now

**Reply by mbround18** [reply]
ill grab a new screenshot  :P

**Comment by Hi-ImKyle** [comment]
Either way, I'm sure we'd all prefer it to show up in the server browser in-game, yet mine is still not showing up? I checked ports, everything is open, including my NAT. Here's my compose file.

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    network_mode: bridge # I added this, I prefer if it's on the bridge network. This can be ignored.
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Sheffield Valheim Server"
      - WORLD="Dedicated"
      - PASSWORD="REDACTED"
      - TZ=Europe/London
      - PUBLIC=1
      - AUTO_UPDATE=0
    volumes:
    - ./saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./server:/home/steam/valheim
```
