### DISCUSSION TITLE
Unable to start container

### DISCUSSION THREAD

**Discussion by Wundark** [mbround18/valheim-docker#548] [Help!] [answered]
Unable to start docker container using the following docker-compose. I have checked file permissions and free RAM and they don't seem to show any issue.

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Server"
      - WORLD="Dedicated"
      - PASSWORD="password"
      - TZ=Etc/GMT
      - PUBLIC=1
      - AUTO_UPDATE=0
    volumes:
    - /mnt/user/appdata/docker/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - /mnt/user/appdata/docker/valheim/server:/home/steam/valheim
```

When I run this, I get the following log ending with the container crashing.

```
[Valheim][root] : ###########################################################################
[Valheim][root] : Valheim Server - Tue 08 Mar 2022 08:22:04 PM GMT
[Valheim][root] : Initializing your container...
[Valheim][root] : You must be in development. Good luck!
[Valheim][root] : ###########################################################################
[Valheim][root] : Switching UID and GID
[Valheim][root] : usermod: no changes
[Valheim][root] : 
[Valheim][root] : Setting up file systems
[Valheim][root] : Navigating to steam home...
[Valheim][root] : Launching as steam...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Valheim Server - Tue 08 Mar 2022 08:22:04 PM GMT
[Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000
[Valheim][steam]: Installing Valheim via odin 1.5.1...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Variables loaded.....
[Valheim][steam]: Port: 2456
[Valheim][steam]: Name: Gaming Group
[Valheim][steam]: World: Dedicated
[Valheim][steam]: Public: 1
[Valheim][steam]: Password: (REDACTED)
[Valheim][steam]: Running Install...
[Valheim][steam]: Attempting to update before launching the server!
[Valheim][steam]: Installing Updates...
[ODIN][INFO]  - Installing 896660 to /home/steam/valheim
[ODIN][INFO]  - steamcmd found in path
Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1646446107
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...Connectivity test: result=Connected, in progress=0
OK
Waiting for client config...OK
/home/steam/.steam/steamcmd/steamcmd.sh: line 39:    58 Killed                  $DEBUGGER "$STEAMEXE" "$@"
Waiting for user info...[ODIN][ERROR] - Exited with http code: 137
```

**Comment by lyk4ndna** [comment]
Where is your docker-compose file located at? I think you need to create a new directory folder named Valheim and run the docker-compose file in there then have your volumes like this in the compose file:

volumes:
- ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
- ./valheim/server:/home/steam/valheim
- ./valheim/backups:/home/steam/backups

**Reply by spannerman79** [reply]
> Where is your docker-compose file located at? I think you need to create a new directory folder named Valheim and run the docker-compose file in there then have your volumes like this in the compose file:

N/A

All that is needed to be added to te `docker-compose.yml` is the following;

```yaml
container_name: valheim
```

Doesn't have to be named `valheim` but you get the general idea.

"Updated" `docker-compose.yml`

```yaml
version: '3'
services:
  valheim:
    image: mbround18/valheim:latest
    container_name: valheim
    ports:
      - '2456:2456/udp'
      - '2457:2457/udp'
      - '2458:2458/udp'
    environment:
      - PORT=2456
      - NAME="Server"
      - WORLD="Dedicated"
      - PASSWORD="password"
      - TZ=Etc/GMT
      - PUBLIC=1
      - AUTO_UPDATE=0
    volumes:
      - '/mnt/user/appdata/docker/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim'
      - '/mnt/user/appdata/docker/valheim/server:/home/steam/valheim'

```
