### DISCUSSION TITLE
Command Too Long - Errors In Crontab File, Can't Install

### DISCUSSION THREAD

**Discussion by nevrending** [mbround18/valheim-docker#565] [Help!] [answered]
Hi, thanks for this great image!

I noticed the log said `"-":1: command too long errors in crontab file, can't install.` and it seems like the crontab did indeed not get installed (i.e autoupdate not running). I noticed this today when Valheim gets updated a couple of days ago, the Valheim server did not autoupdate.

```
[Valheim][root] : ###########################################################################
[Valheim][root] : Valheim Server - Wed 13 Apr 2022 11:08:45 PM AEST
[Valheim][root] : Initializing your container...
[Valheim][root] : You must be in development. Good luck!
[Valheim][root] : ###########################################################################
[Valheim][root] : Switching UID and GID
[Valheim][root] : usermod: no changes
[Valheim][root] : 
[Valheim][root] : Auto Update Enabled...
[Valheim][root] : Auto Update Schedule: 0 * * * *
[Valheim][root] : Auto Backup Enabled...
[Valheim][root] : Auto Backup Schedule: */15 * * * *
"-":1: command too long
errors in crontab file, can't install.
[Valheim][root] : Setting up file systems
[Valheim][root] : Navigating to steam home...
[Valheim][root] : Launching as steam...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Valheim Server - Wed 13 Apr 2022 11:08:45 PM AEST
[Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000
[Valheim][steam]: Installing Valheim via odin 1.5.3...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Variables loaded.....
[Valheim][steam]: Port: 2456
[Valheim][steam]: Name: Something
[Valheim][steam]: World: Some Thing
[Valheim][steam]: Public: 1
[Valheim][steam]: Password: (REDACTED)
[Valheim][steam]: Running Install...
[Valheim][steam]: Attempting to update before launching the server!
[Valheim][steam]: Starting auto backup process...
[Valheim][steam]: Removing old backups...
[Valheim][steam]: Creating backup...
[Valheim][steam]: Backup process complete! Created 20220413-230845-pre-update-backup.tar.gz
[Valheim][steam]: Installing Updates...
[ODIN][INFO]  - Installing 896660 to /home/steam/valheim
[ODIN][INFO]  - steamcmd found in path
Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
```

This is my compose file
```yaml
version: "3.8"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      NAME: "Something"
      WORLD: "Some Thing"
      PUBLIC: 1
      PASSWORD: "(REDACTED)"
      WEBHOOK_URL: "(REDACTED)"
      WEBHOOK_INCLUDE_PUBLIC_IP: 0
      UPDATE_ON_STARTUP: 1
      TZ: "Australia/Melbourne"
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 * * * *"
      AUTO_UPDATE_PAUSE_WITH_PLAYERS: 1
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
    volumes:
      - /home/ubuntu/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /home/ubuntu/valheim/server:/home/steam/valheim
      - /home/ubuntu/valheim/backups:/home/steam/backups
```

Are there any issues with my compose file or any ideas how to fix this?
Thanks in advance.
