### DISCUSSION TITLE
Error when running docker-compose up: no space left on device

### DISCUSSION THREAD

**Discussion by silasjmatson** [mbround18/valheim-docker#620] [Help!] [answered]
I've had an installation that's been working for quite a while, but recently the autorestart shut the server down and failed to boot it back up.

I opened up an ssh session and discovered the following issue when running `docker-compose up`:

```
~$ sudo docker-compose up
Pulling valheim (mbround18/valheim:latest)...
latest: Pulling from mbround18/valheim
675920708c8b: Pull complete
f9336ee7df7c: Pull complete
47f71c84286e: Pull complete
99e1ec0a76e3: Pull complete
51b663e2962e: Pull complete
eb70e92f19b7: Pull complete
cb4f4cee8f8a: Pull complete
d811b73cc41b: Extracting [==================================================>]  151.7MB/151.7MB
a22ad3cda8b4: Download complete
4eb43900381e: Download complete
7ee05f6f0175: Download complete
b8a6cb082045: Download complete
6ca064a723a3: Download complete
c148f307db6f: Download complete
0d811a3f99a3: Download complete
ERROR: failed to register layer: Error processing tar file(exit status 1): write /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8: no space left on device
```

I tried running `docker system prune` and `docker system prune --all`, but that didn't resolve the issue. `docker system df` returns the following:

```
$ sudo docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          0         0         0B        0B
Containers      0         0         0B        0B
Local Volumes   9         0         2.548GB   2.548GB (100%)
Build Cache     0         0         0B        0B
```

My `docker-compose.yml` is as follows:

```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="<REDACTED>"
      - WORLD="funworld3"
      - PASSWORD="<REDACTED>"
      - TZ=America/Chicago
      - PUBLIC=1
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - WEBHOOK_URL="<REDACTED>"
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
```

This is a lightsail installation with an 80GB disk, so my intuition is that the limitation is a docker config of some sort, but I don't have in-depth experience with docker to debug it myself. Anyone have any thoughts or next steps to try? My friends and I aren't actively playing on this world, but once the mistlands update comes out we plan to restart, so if I can't resolve by then I'll probably just do a completely fresh install, but I'd like to learn what's going wrong here and how to fix it.
