### DISCUSSION TITLE
[ODIN][ERROR] - Exited with http code: 1 (Docker version 20.10.17, build 100c701)

### DISCUSSION THREAD

**Discussion by hyunjaekim** [mbround18/valheim-docker#623] [Help!] [answered]
I tried to deploy vahheil-docker image on my m1 mac mini, then faced this error.

Here are my yml and logs.

```
version: "3"
services:
  valheim:
    platform: linux/amd64
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME=MookBAB
      - WORLD=World-second
      - PASSWORD=789654
      - TZ=Asia/Seoul
      - PUBLIC=1
      - AUTO_UPDATE=0
      - PUID=1000
      - PGID=1000
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
```

```
valheim % docker-compose up    
[+] Running 1/1
 ⠿ Container valheim-valheim-1  Recreated                                                                                                0.1s
Attaching to valheim-valheim-1
valheim-valheim-1  | [Valheim][root] : ###########################################################################
valheim-valheim-1  | [Valheim][root] : Valheim Server - Sun 23 Oct 2022 09:28:44 PM KST
valheim-valheim-1  | [Valheim][root] : Initializing your container...
valheim-valheim-1  | [Valheim][root] : You must be in development. Good luck!
valheim-valheim-1  | [Valheim][root] : ###########################################################################
valheim-valheim-1  | [Valheim][root] : Switching UID and GID
valheim-valheim-1  | [Valheim][root] : usermod: no changes
valheim-valheim-1  | [Valheim][root] : 
valheim-valheim-1  | Configuring Preset Env
valheim-valheim-1  | Preset Env Configured
valheim-valheim-1  | [Valheim][root] : Setting up file systems
valheim-valheim-1  | [Valheim][root] : Navigating to steam home...
valheim-valheim-1  | [Valheim][root] : Launching as steam...
valheim-valheim-1  | [Valheim][steam]: ###########################################################################
valheim-valheim-1  | [Valheim][steam]: Valheim Server - Sun 23 Oct 2022 09:28:46 PM KST
valheim-valheim-1  | [Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000
valheim-valheim-1  | [Valheim][steam]: Installing Valheim via odin 1.5.3...
valheim-valheim-1  | [Valheim][steam]: ###########################################################################
valheim-valheim-1  | [Valheim][steam]: Variables loaded.....
valheim-valheim-1  | [Valheim][steam]: Port: 2456
valheim-valheim-1  | [Valheim][steam]: Name: MookBAB
valheim-valheim-1  | [Valheim][steam]: World: World-second
valheim-valheim-1  | [Valheim][steam]: Public: 1
valheim-valheim-1  | [Valheim][steam]: With Crossplay: 
valheim-valheim-1  | [Valheim][steam]: Password: (REDACTED)
valheim-valheim-1  | [Valheim][steam]: Running Install...
valheim-valheim-1  | [ODIN][INFO]  - Installing 896660 to /home/steam/valheim
valheim-valheim-1  | [ODIN][INFO]  - steamcmd found in path
**valheim-valheim-1  | [ODIN][ERROR] - Exited with http code: 1
valheim-valheim-1 exited with code 1**

```
