### DISCUSSION TITLE
Failed to connect huginn http server

### DISCUSSION THREAD

**Discussion by piutranq** [mbround18/valheim-docker#626] [Help!] [answered]
Connecting to game and playing is no problem, but http server is no responsing correctly.
I have read a similar discussion (https://github.com/mbround18/valheim-docker/discussions/540) but no helpful for me.
What shoud I do?

# Environments
- e2-medium instance of GCP
- Ubuntu 20.04 LTS

# Error
## http responses
`/`
```
hamgaserver is offline
```

`/status`
```
{"name":"hamgaserver","version":"Unknown","players":0,"max_players":0,"map":"hamgaserver","online":false,"bepinex":{"enabled":false,"mods":[]},"jobs":[]}%
```

`/metrics`
```
valheim_online{name="hamgaserver", version="Unknown", map="hamgaserver"} 0
valheim_current_player_count{name="hamgaserver", version="Unknown", map="hamgaserver"} 0
valheim_max_player_count{name="hamgaserver", version="Unknown", map="hamgaserver"} 0
valheim_bepinex_installed{name="hamgaserver", version="Unknown", map="hamgaserver"} 0
```

## docker logs 
the logs are parts of `docker compose logs`

when the container is launching. I think this part is related.
```
...
...
valheim-docker-valheim-1  | [ODIN][INFO]  - ##########################################################################################################################
valheim-docker-valheim-1  | [ODIN][INFO]  - Server has been started and Daemonized. It should be online shortly!
valheim-docker-valheim-1  | [ODIN][INFO]  - Keep an eye out for 'Game server connected' in the log!
valheim-docker-valheim-1  | [ODIN][INFO]  - (this indicates its online without any errors.)
valheim-docker-valheim-1  | [ODIN][INFO]  - Starting web server....
valheim-docker-valheim-1  | [ODIN][INFO]  - Navigate to http://127.0.0.1:2459/status to view the server status.
valheim-docker-valheim-1  | [ODIN][INFO]  - Server::run; addr=0.0.0.0:2459
valheim-docker-valheim-1  | [ODIN][INFO]  - listening on http://0.0.0.0:2459
valheim-docker-valheim-1  | [Valheim][steam]: Herding Graydwarfs...
valheim-docker-valheim-1  | ==> /home/steam/valheim/logs/valheim_server.log <==
...
...
```

for each http request, this error is added on the logs.
```
valheim-docker-valheim-1  | [ODIN][ERROR] - Failed to request server information!
```

the process of containers. (`docker compose top`) `huginn` is running.
```
valheim-docker-valheim-1
UID      PID     PPID    C    STIME   TTY   TIME       CMD
ubuntu   11664   11644   0    12:28   ?     00:00:00   /bin/bash /home/steam/scripts/start_valheim.sh                                                                                                                                                                          
root     11789   11664   0    12:28   ?     00:00:00   /usr/sbin/cron -f                                                                                                                                                                                                       
ubuntu   11881   11664   0    12:28   ?     00:00:00   huginn                                                                                                                                                                                                                  
ubuntu   11886   11664   27   12:28   ?     00:08:30   /home/steam/valheim/valheim_server.x86_64 -nographics -batchmode -port 2456 -name hamgaserver -world hamgaheim -public 0 -password hamgap@ssword4786 -savedir /home/steam/.config/unity3d/IronGate/Valheim              
ubuntu   11891   11664   0    12:28   ?     00:00:00   tail -F /home/steam/valheim/logs/valheim_server.log /home/steam/valheim/logs/valheim_server.err /home/steam/valheim/logs/output.log /home/steam/valheim/logs/auto-update.out /home/steam/valheim/logs/auto-backup.out   
```

#  Configurations

my `docker-compose.yaml`
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
      - 2459:2459/tcp
    environment:
      - PORT=2456
      - HTTP_PORT=2459
      - NAME="hamgaserver"
      - WORLD="hamgaheim"
      - PASSWORD="...."
      - TZ=Asia/Seoul
      - PUBLIC=0
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 7 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="0 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=7
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP=1
      - ENABLE_CROSSPLAY=0
      - TYPE=BepInEx
      - "MODS=
          https://cdn.thunderstore.io/live/repository/packages/GemHunter1-NoAFKEvents-1.0.1.zip
        "
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
```
