### DISCUSSION TITLE
`BepInEx` and `BepInExFull` server type startup behavior is strange

### DISCUSSION THREAD

**Discussion by lafrad** [mbround18/valheim-docker#686] [Help!] [answered]
I'm running into an issue getting my server started with plain `BepInEx`.
I'm trying to start the server with just `BepInEx`, and load in a few simple mods (trying to keep it reasonably vanilla), but the `BepInEx` and `BepInExFull` types aren't doing what I'm expecting.

Creating this new topic, was originally asked here: https://github.com/mbround18/valheim-docker/discussions/637

Operating System: Ubuntu 22.04.1-Ubuntu SMP
Docker Version: 23.0.2, build 569dd73
User & Group On Host: 1000:1000
Are you running with BepInEx? Yes (BepInEx)

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    stop_signal: SIGINT
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME=<redacted>
      - WORLD=<redacted>
      - PASSWORD=<redacted>
      - TZ=America/Los_Angeles
      - TYPE=BepInEx
      - PUBLIC=0
      - AUTO_UPDATE=0
      - AUTO_UPDATE_SCHEDULE="0 4 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="4 */4 * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=2
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
        # The Mods variable is a comma and newline separated string.
        # It MUST be a link with a command and a new line at the end to be valid.
      - "MODS=
        https://thunderstore.io/package/download/ValheimModding/Jotunn/2.11.2/,
        "
      - WEBHOOK_URL=<redacted>
      - WEBHOOK_INCLUDE_PUBLIC_IP=1
      - ENABLE_CROSSPLAY=0
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
```

However I've got a slightly different experience... with `BepInEx` being "ignored" and `BepInExFull` crashing on startup.
Everything should be running as a normal user.    Serve

* `- TYPE=BepInEx` does NOT start Valheim with Mods... the server starts up Vanilla.   It DOES download mods.
`docker compose up`
```
valheim_1  | [ODIN][INFO]  - Successfully written /home/steam/valheim/discord.json
valheim_1  | [Valheim][steam]: Checking for TYPE flag
valheim_1  | [Valheim][steam]: Found Type BepInEx
valheim_1  | [Valheim][steam]: Running with BepInEx Valheim <3
valheim_1  | [Valheim][steam]: Installing BepInEx
valheim_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
valheim_1  |                                  Dload  Upload   Total   Spent    Left  Speed
100  1078  100  1078    0     0   3644      0 --:--:-- --:--:-- --:--:--  3641
valheim_1  | [Valheim][steam]: Pulling BepInEx from https://thunderstore.io/package/download/denikson/BepInExPack_Valheim/5.4.2102/
valheim_1  | [ODIN][INFO]  - Installing https://thunderstore.io/package/download/denikson/BepInExPack_Valheim/5.4.2102/
valheim_1  | [ODIN][INFO]  - Installing Mod...
valheim_1  | [ODIN][INFO]  - Successfully installed https://gcdn.thunderstore.io/live/repository/packages/denikson-BepInExPack_Valheim-5.4.2102.zip
valheim_1  | [Valheim][steam]: Installing Mod  https://thunderstore.io/package/download/ValheimModding/Jotunn/2.11.2/
valheim_1  | [ODIN][INFO]  - Installing  https://thunderstore.io/package/download/ValheimModding/Jotunn/2.11.2/
valheim_1  | [ODIN][INFO]  - Installing Mod...
valheim_1  | [ODIN][INFO]  - Successfully installed https://gcdn.thunderstore.io/live/repository/packages/ValheimModding-Jotunn-2.11.2.zip
valheim_1  | [Valheim][steam]: Installing Mod
valheim_1  | [ODIN][INFO]  - Installing
valheim_1  | [ODIN][ERROR] - Failed to download mod with invalid url:
valheim_1  | [Valheim][steam]: Starting server...
valheim_1  | [ODIN][INFO]  - Setting up start scripts...
valheim_1  | [ODIN][INFO]  - Looking for burial mounds...
valheim_1  | [ODIN][INFO]  - Server has been started and Daemonized. It should be online shortly!
valheim_1  | [ODIN][INFO]  - Keep an eye out for 'Game server connected' in the log!
valheim_1  | [ODIN][INFO]  - Sending discord notification <3
valheim_1  | [ODIN][INFO]  - [Start Successful]: Webhook message sent successfully!
valheim_1  | [ODIN][INFO]  - (this indicates its online without any errors.)
valheim_1  | [Valheim][steam]: Herding Graydwarfs...
valheim_1  | ==> /home/steam/valheim/logs/valheim_server.log <==
valheim_1  | Unloading 6 Unused Serialized files (Serialized files now loaded: 1)
valheim_1  | UnloadTime: 11.490765 ms
valheim_1  | HDR Render Texture not supported, disabling HDR on reflection probe.
valheim_1  | HDR Render Texture not supported, disabling HDR on reflection probe.
valheim_1  | 04/02/2023 20:30:03: Using default prefs
valheim_1  | 04/02/2023 20:30:03: isModded: False
valheim_1  | 04/02/2023 20:30:03: Zonesystem Awake 234
valheim_1  | 04/02/2023 20:30:03: DungeonDB Awake 234
valheim_1  | 04/02/2023 20:30:03: Registering lobby
valheim_1  | 04/02/2023 20:30:03: Worldgenerator version setup:2
```
* `Type=BepInExFull` Crashes out with library loading issues... (Assuming its just too old, as looking at the version on ThunderStore seems... old)
`docker compose up`
```
valheim_1  | [ODIN][INFO]  - Successfully written /home/steam/valheim/config.json
valheim_1  | [ODIN][INFO]  - Successfully written /home/steam/valheim/discord.json
valheim_1  | [Valheim][steam]: Checking for TYPE flag
valheim_1  | [Valheim][steam]: Found Type BepInExFull
valheim_1  | [Valheim][steam]: Running with BepInExFull Valheim <3
valheim_1  | [Valheim][steam]: Installing BepInEx Full
valheim_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
valheim_1  |                                  Dload  Upload   Total   Spent    Left  Speed
100  1007  100  1007    0     0   2475      0 --:--:-- --:--:-- --:--:--  2480
valheim_1  | [Valheim][steam]: Pulling BepInEx Full from https://thunderstore.io/package/download/1F31A/BepInEx_Valheim_Full/1.0.5/
valheim_1  | [ODIN][INFO]  - Installing https://thunderstore.io/package/download/1F31A/BepInEx_Valheim_Full/1.0.5/
valheim_1  | [ODIN][INFO]  - Installing Framework...
valheim_1  | [ODIN][INFO]  - Successfully installed https://gcdn.thunderstore.io/live/repository/packages/1F31A-BepInEx_Valheim_Full-1.0.5.zip
valheim_1  | [Valheim][steam]: Installing Mod  https://thunderstore.io/package/download/ValheimModding/Jotunn/2.11.2/
valheim_1  | [ODIN][INFO]  - Installing  https://thunderstore.io/package/download/ValheimModding/Jotunn/2.11.2/
valheim_1  | [ODIN][INFO]  - Installing Mod...
valheim_1  | [ODIN][INFO]  - Successfully installed https://gcdn.thunderstore.io/live/repository/packages/ValheimModding-Jotunn-2.11.2.zip
valheim_1  | [Valheim][steam]: Installing Mod
valheim_1  | [ODIN][INFO]  - Installing
valheim_1  | [ODIN][ERROR] - Failed to download mod with invalid url:
valheim_1  | [Valheim][steam]: Starting server...
valheim_1  | [ODIN][INFO]  - Setting up start scripts...
valheim_1  | [ODIN][INFO]  - Looking for burial mounds...
valheim_1  | [ODIN][INFO]  - Server has been started with BepInEx! Keep in mind this may cause errors!!
valheim_1  | [ODIN][INFO]  - ##########################################################################################################################
valheim_1  | [ODIN][INFO]  - DISCLAIMER! Modding your server can cause a lot of errors.
valheim_1  | [ODIN][INFO]  - Please do NOT post issue on the valheim-docker repo based on mod issues.
valheim_1  | [ODIN][INFO]  - By installing mods, you agree that you will do a root cause analysis to why your server is failing before you make a post.
valheim_1  | [ODIN][INFO]  - Modding is currently unsupported by the Valheim developers and limited support by the valheim-docker repo.
valheim_1  | [ODIN][INFO]  - If you have issues please contact the MOD developer FIRST based on the output logs.
valheim_1  | [ODIN][INFO]  - ##########################################################################################################################
valheim_1  | [ODIN][INFO]  - Server has been started and Daemonized. It should be online shortly!
valheim_1  | [ODIN][INFO]  - Keep an eye out for 'Game server connected' in the log!
valheim_1  | [ODIN][INFO]  - Sending discord notification <3
valheim_1  | [ODIN][INFO]  - [Start Successful]: Webhook message sent successfully!
valheim_1  | [ODIN][INFO]  - (this indicates its online without any errors.)
valheim_1  | [Valheim][steam]: Herding Graydwarfs...
valheim_1  | ==> /home/steam/valheim/logs/valheim_server.log <==
valheim_1  | #10 0x007f30ec911b37 in AwakeFromLoadQueue::InvokePersistentManagerAwake(AwakeFromLoadQueue::Item*, unsigned int, AwakeFromLoadMode, bool)
valheim_1  | #11 0x007f30ec9113c5 in AwakeFromLoadQueue::PersistentManagerAwakeFromLoad(ErrorsAndWarningsCapture*, bool)
valheim_1  | #12 0x007f30ec8fd747 in PersistentManager::LoadAndIntegrateAllPreallocatedObjects(PersistentManager::LockFlags)
valheim_1  | #13 0x007f30ec8fdcfb in PersistentManager::ReadObject(int, AwakeFromLoadMode)
valheim_1  | #14 0x007f30ec51efb4 in PlayerLoadGlobalManagers(char const*, char const*, unsigned int)
valheim_1  | #15 0x007f30ec751c49 in PlayerInitEngineGraphics(bool)
valheim_1  | #16 0x007f30ec91f9b3 in PlayerMain(int, char**)
valheim_1  | #17 0x007f30eb7dad90 in __libc_init_first
valheim_1  | #18 0x007f30eb7dae40 in __libc_start_main
valheim_1  | #19 0x0055d8c0fe8029 in _start
```

Why does the base `BepInEx` download the mods and never get wired in?    
I've tried this by fully backing up my `~/valheim/` folder so it can create it completely fresh/clean, and its still failing in the same way.
