### DISCUSSION TITLE
[ODIN][ERROR] - Failed to run process!

### DISCUSSION THREAD

**Discussion by illuminatedwax** [mbround18/valheim-docker#688] [Help!] [answered]
When running docker-compose up, I get the following error:

```valheim_1  | Configuring Preset Env
valheim_1  | Preset Env Configured
valheim_1  | [Valheim][root] : Auto Update Enabled...
valheim_1  | [Valheim][root] : Auto Update Schedule: "0 1 * * *"
valheim_1  | [Valheim][root] : Auto Backup Enabled...
valheim_1  | [Valheim][root] : Auto Backup Schedule: "*/15 * * * *"
valheim_1  | [Valheim][root] : Setting up file systems
valheim_1  | [Valheim][root] : Navigating to steam home...
valheim_1  | [Valheim][root] : Launching as steam...
valheim_1  | [Valheim][steam]: ###########################################################################
valheim_1  | [Valheim][steam]: Valheim Server - Mon Apr  3 02:41:44 AM America 2023
valheim_1  | [Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000
valheim_1  | [Valheim][steam]: Installing Valheim via odin 1.5.3...
valheim_1  | [Valheim][steam]: ###########################################################################
valheim_1  | [Valheim][steam]: Variables loaded.....
valheim_1  | [Valheim][steam]: Port: 2456
valheim_1  | [Valheim][steam]: Name: Saint Basil Valheim
valheim_1  | [Valheim][steam]: World: Dedicated
valheim_1  | [Valheim][steam]: Public: 0
valheim_1  | [Valheim][steam]: With Crossplay: 
valheim_1  | [Valheim][steam]: Password: (REDACTED)
valheim_1  | [Valheim][steam]: Running Install...
valheim_1  | [Valheim][steam]: Attempting to update before launching the server!
valheim_1  | [Valheim][steam]: Starting auto backup process...
valheim_1  | [Valheim][steam]: Removing old backups...
valheim_1  | [Valheim][steam]: Creating backup...
valheim_1  | [Valheim][steam]: Backup process complete! Created 20230403-024144-pre-update-backup.tar.gz
valheim_1  | [Valheim][steam]: Installing Updates...
valheim_1  | [ODIN][INFO]  - Installing 896660 to /home/steam/valheim
valheim_1  | [ODIN][INFO]  - steamcmd found in path
valheim_1  | [ODIN][ERROR] - Failed to run process!
ubuntu_valheim_1 exited with code 1
```

Here is my docker-compose.yml:
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Saint Basil Valheim"
      - WORLD="Dedicated"
      - PASSWORD=[REDACTED]
      - TZ=America/Chicago
      - PUBLIC=0
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
```

Thank you for helping!

**Comment by mbround18** [comment]
@illuminatedwax on your host for the user you are running this docker container on whats your user ID? 

```sh
 id -u username
```

**Reply by illuminatedwax** [reply]
```
$ id -u ubuntu
1000
```

**Reply by mbround18** [reply]
Have you tried deleting your server directory and letting it reinstall?

**Comment by illuminatedwax** [comment, marked as answer]
Seems to be the same problem. Here's the directory it reinstalled:
```
$ ls valheim/server/ -l
total 4
drwxr-xr-x 2 ubuntu ubuntu 4096 Apr  3 12:21 logs
```

Logs again:
```
$ docker-compose up
Starting ubuntu_valheim_1 ... done
Attaching to ubuntu_valheim_1
valheim_1  | [Valheim][root] : ###########################################################################
valheim_1  | [Valheim][root] : Valheim Server - Mon Apr  3 12:22:33 PM America 2023
valheim_1  | [Valheim][root] : Initializing your container...
valheim_1  | [Valheim][root] : You must be in development. Good luck!
valheim_1  | [Valheim][root] : ###########################################################################
valheim_1  | [Valheim][root] : Switching UID and GID
valheim_1  | [Valheim][root] : usermod: no changes
valheim_1  | [Valheim][root] : 
valheim_1  | Configuring Preset Env
valheim_1  | Preset Env Configured
valheim_1  | [Valheim][root] : Auto Update Enabled...
valheim_1  | [Valheim][root] : Auto Update Schedule: "0 1 * * *"
valheim_1  | [Valheim][root] : Auto Backup Enabled...
valheim_1  | [Valheim][root] : Auto Backup Schedule: "*/15 * * * *"
valheim_1  | [Valheim][root] : Setting up file systems
valheim_1  | [Valheim][root] : Navigating to steam home...
valheim_1  | [Valheim][root] : Launching as steam...
valheim_1  | [Valheim][steam]: ###########################################################################
valheim_1  | [Valheim][steam]: Valheim Server - Mon Apr  3 12:22:33 PM America 2023
valheim_1  | [Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000
valheim_1  | [Valheim][steam]: Installing Valheim via odin 1.5.3...
valheim_1  | [Valheim][steam]: ###########################################################################
valheim_1  | [Valheim][steam]: Variables loaded.....
valheim_1  | [Valheim][steam]: Port: 2456
valheim_1  | [Valheim][steam]: Name: Saint Basil Valheim
valheim_1  | [Valheim][steam]: World: Dedicated
valheim_1  | [Valheim][steam]: Public: 0
valheim_1  | [Valheim][steam]: With Crossplay: 
valheim_1  | [Valheim][steam]: Password: (REDACTED)
valheim_1  | [Valheim][steam]: Running Install...
valheim_1  | [ODIN][INFO]  - Installing 896660 to /home/steam/valheim
valheim_1  | [ODIN][INFO]  - steamcmd found in path
valheim_1  | [ODIN][ERROR] - Failed to run process!
ubuntu_valheim_1 exited with code 1
```

**Reply by mbround18** [reply]
By chance are you running on an arm system?

**Reply by illuminatedwax** [reply]
I am not:
```
$ cat /proc/cpuinfo | grep model
model: 79
model name: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
model: 79
model name: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
```

**Reply by mbround18** [reply]
could you drop a copy of your compose? (minus sensitive data)

**Reply by mbround18** [reply]
additionally, can you send me your docker and compose versions?

**Reply by illuminatedwax** [reply]
docker-compose.yml:
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Saint Basil Valheim"
      - WORLD="Dedicated"
      - PASSWORD=[REDACTED]
      - TZ=America/Chicago
      - PUBLIC=0
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
```
docker version:
```
$ docker --version
Docker version 20.10.5, build 55c4c88
```
docker-compose version:
```
$ docker-compose --version
docker-compose version 1.25.0, build unknown
```
