### DISCUSSION TITLE
QEMU: Failed to create symbolic link .... No such directory or file

### DISCUSSION THREAD

**Discussion by mikart143** [mbround18/valheim-docker#689] [Help!]
Hi!
Great work!
I am having small trouble with running this on Oracle Ampere Free server.
My setup is based on docker compose and QEMU with emulators from: https://hub.docker.com/r/tonistiigi/binfmt
When I start server I receive error:
```
ln: failed to create symbolic link '/home/steam/.steam/root': No such file or directory
ln: failed to create symbolic link '/home/steam/.steam/steam': No such file or directory
```
My docker-compose.yaml
```yaml
version: "3"
services:
  valheim:
    privileged: true
    image: mbround18/valheim:latest
    platform: linux/amd64

    stop_signal: SIGINT
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      NAME: "XXXXX"
      WORLD: "Dedicated"
      PASSWORD: "XXXXX"
      TZ: "Europe/Warsaw"
      PUBLIC: 0
      ENABLE_CROSSPLAY: 1
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      UPDATE_ON_STARTUP: 1
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
```
Full log:
```
[Valheim][root] : Navigating to steam home...
[Valheim][root] : Launching as steam...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Valheim Server - Sun Apr  2 07:38:00 PM Europe 2023
[Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000
[Valheim][steam]: Installing Valheim via odin 1.5.3...
[Valheim][steam]: ###########################################################################
[Valheim][steam]: Variables loaded.....
[Valheim][steam]: Port: 2456
[Valheim][steam]: Name: Pierdolnik na ARM
[Valheim][steam]: World: Dedicated
[Valheim][steam]: Public: 0
[Valheim][steam]: With Crossplay: 1
[Valheim][steam]: Password: (REDACTED)
[Valheim][steam]: Running Install...
[ODIN][INFO]  - Installing 896660 to /home/steam/valheim
[ODIN][INFO]  - steamcmd found in path
ln: failed to create symbolic link '/home/steam/.steam/root': No such file or directory
ln: failed to create symbolic link '/home/steam/.steam/steam': No such file or directory
[ODIN][ERROR] - Exited with http code: 1
```
