### DISCUSSION TITLE
Cannot Run Multiple Valheim Instances on Same Server

### DISCUSSION THREAD

**Discussion by action3** [mbround18/valheim-docker#697] [Help!]
**Hello! I cannot seem to create multiple instances. When I bring the containers up, only one server shows as healthy:**

![docker-ps](https://user-images.githubusercontent.com/58885620/236471024-995ff42f-f359-482f-b5a1-d08229985d6d.png)

**Here is my docker-compose.yml file, with some slight omissions for server details:**

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME=name
      - WORLD=world
      - PASSWORD=password
      - TYPE=BepInEx
      - UPDATE_ON_STARTUP=1
      - TZ=America/New_York
      - PUBLIC=0
      - ENABLE_CROSSPLAY=1
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE=0 1 * * *
      - AUTO_UPDATE_PAUSE_WITH_PLAYERS=1
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE=*/15 * * * *
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS=1
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
  valheimplus:
    image: mbround18/valheim:latest
    ports:
      - 2459:2456/udp
      - 2460:2457/udp
      - 2461:2458/udp
    environment:
      - PORT=2456
      - NAME=name
      - WORLD=world
      - PASSWORD=password
      - TYPE=ValheimPlus
      - UPDATE_ON_STARTUP=1
      - TZ=America/New_York
      - PUBLIC=0
      - ENABLE_CROSSPLAY=1
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE=0 1 * * *
      - AUTO_UPDATE_PAUSE_WITH_PLAYERS=1
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE=*/15 * * * *
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS=1
    volumes:
      - ./valheimplus/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheimplus/server:/home/steam/valheim
      - ./valheimplus/backups:/home/steam/backups
  bepinexfull:
    image: mbround18/valheim:latest
    ports:
      - 2462:2456/udp
      - 2463:2457/udp
      - 2464:2458/udp
    environment:
      - PORT=2456
      - NAME=name
      - WORLD=world
      - PASSWORD=password
      - TYPE=BepInExFull
      - UPDATE_ON_STARTUP=1
      - TZ=America/New_York
      - PUBLIC=0
      - ENABLE_CROSSPLAY=1
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE=0 1 * * *
      - AUTO_UPDATE_PAUSE_WITH_PLAYERS=1
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE=*/15 * * * *
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS=1
    volumes:
      - ./bepinexfull/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./bepinexfull/server:/home/steam/valheim
      - ./bepinexfull/backups:/home/steam/backups
``` 

**Here is some output from valheim_server.log (valheim_server.err did not seem to catch anything out of the ordinary):**

```
05/05/2023 13:12:55: Get create world Yggdrasil
05/05/2023 13:12:55:   failed to load Yggdrasil
05/05/2023 13:12:55:  creating
05/05/2023 13:12:55: Considering autobackup. World time: 0, short time: 7200, long time: 43200, backup count: 4
05/05/2023 13:12:55: Creating first autobackup
05/05/2023 13:12:55: Saving backup at: /home/steam/.config/unity3d/IronGate/Valheim/worlds_local/Yggdrasil_backup_auto-20230505131255.fwl
05/05/2023 13:12:55: Using environment steamid 892970
05/05/2023 13:12:55: Using steam APPID:892970
dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
05/05/2023 13:12:55: Server ID 90071992547409920
05/05/2023 13:12:55: Authentication:k_ESteamNetworkingAvailability_Waiting
05/05/2023 13:12:55: Steam game server initialized
05/05/2023 13:12:55: Using default prefs
05/05/2023 13:12:55: Valheim version: 0.215.2 (network version 1)
05/05/2023 13:12:55: Worldgenerator version setup:2
ERROR: Shader TextMeshPro/Sprite shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
05/05/2023 13:12:55: Render threading mode:SingleThreaded
05/05/2023 13:12:55: Missing audio clip in music respawn
05/05/2023 13:12:55: Builder started
GetPixel called on an undefined mip (valid values are 0 - 6
Caught fatal signal - signo:11 code:1 errno:0 addr:0x3fb
Obtained 3 stack frames.
#0  0x007f1fb301a520 in __sigaction
#1  0x007f1fb41792c3 in Texture2D_CUSTOM_GetPixelImpl_Injected(ScriptingBackendNativeObjectPtrOpaque*, int, int, int, int, ColorRGBAf&)
#2  0x000000411efe75 in (wrapper managed-to-native) UnityEngine.Texture2D:GetPixelImpl_Injected (UnityEngine.Texture2D,int,int,int,UnityEngine.Color&)
``` 

**Is there something special I need to do with multiple NICs (I only have a single NIC)? I was assuming since different ports were mapped to each server that this would not be the case. Please let me know what I am doing wrong. Thanks for all of your work you have done on this. It is a great solution!**
