### DISCUSSION TITLE
Webhooks don't use discord.json formatting

### DISCUSSION THREAD

**Discussion by RickDT** [mbround18/valheim-docker#700] [Help!] [answered]
Hi. Amazing project here! I have a server up and running on Digital Ocean. Works beautifully. 🙏

When I put in a `WEBHOOK_URL`, it posts the wrong format for Discord. It posts the format that's on the [Webhooks README](https://github.com/mbround18/valheim-docker/blob/main/docs/webhooks.md#post-body-example)*, but that's not the format Discord wants. I checked my discord.json file and it looks fine (I didn't modify it).

Here's my `docker-compose.yml` below. What am I missing?

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    container_name: valheim
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
      - 3000:3000/tcp
    environment:
      - PORT=2456
      - NAME=Rickserve
      - WORLD=Rixverse
      - PASSWORD=...
      - "TZ=America/Chicago"
      - PUBLIC=1
      - ENABLE_CROSSPLAY=1
      - "WEBHOOK_URL=https://my_hook_echo_url"
      - WEBHOOK_INCLUDE_PUBLIC_IP=1
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
```

*A sample of what's being POSTed:
```
{
  "author": "Notification: Rickserve",
  "event_type": {
    "name": "Start",
    "status": "Successful"
  },
  "event_message": "Server Status: Start Successful",
  "timestamp": "2023-05-09T02:02:11.751336192+00:00"
}
```

**Comment by mbround18** [comment]
Hey @RickDT  my apologies was moving cross country, i can take a look at this!

**Reply by mbround18** [reply, marked as answer]
@RickDT, so looking over the logic and catching myself back up. We ingest the webhook url and see if its a discord one:

![image](https://github.com/mbround18/valheim-docker/assets/12646562/ce789ca2-81cd-4265-adfa-27110059421b)

If its a discord looking url we pass it over to the discord webhook manager structure. This structure converts it over to what discords looking for:

![image](https://github.com/mbround18/valheim-docker/assets/12646562/2afa9abc-3868-4fef-a6c8-7dd81360f224)

When it posts it follows the discord API spec found here:

https://discord.com/developers/docs/resources/channel#embed-object

As an action item, i should explain this better in the documentation <3 ill create a task for myself to upgrade that doc section :) hope this helps!

**Reply by RickDT** [reply]
Nice, thanks @mbround18! I hope the move went well and welcome to your new place :)

**Comment by zazuts** [comment]
I'm using a bashscript, running outside of the container, using like this:

```
chmod +x discord.sh
screen (enter twice)
./discord.sh
```


Im using this to send the information using webhooks (discord.sh):


```
#!/bin/bash

# Name or ID of the container
nome_ou_id_do_container=""

# Keywords to monitor in the logs (til 5)
palavras_chave=("Backup process complete" "Got character ZDOID" "received local Platform ID Steam")

# URL webhook from Discord
discord_webhook_url="Discord-webhook_link"

# Start the last lines related for each keyword
declare -A ultimas_linhas_correspondentes
for palavra in "${palavras_chave[@]}"; do
  ultimas_linhas_correspondentes["$palavra"]=""
done

# Function to send the msg to the webhook on discord
enviar_mensagem_discord() {
  mensagem="$1"
  curl -H "Content-Type: application/json" -d "{\"content\":\"$mensagem\"}" "$discord_webhook_url"
}

# Function to verify the logs and send the last line
monitorar_logs() {
  while true; do
    for palavra in "${palavras_chave[@]}"; do
      # Capture the last 100 lines from container logs and verify the keyword 
      ultima_linha=$(docker logs --tail 100 "$nome_ou_id_do_container" 2>/dev/null | grep "$palavra" | tail -n 1)

      if [ -n "$ultima_linha" ] && [ "$ultima_linha" != "${ultimas_linhas_correspondentes["$palavra"]}" ]; then
        echo "Last Line with the keyword '$palavra': $ultima_linha"

        # Sending the last line to discord
        enviar_mensagem_discord "$ultima_linha"

        # Atualizar a última linha correspondente para a palavra-chave
        ultimas_linhas_correspondentes["$palavra"]=$ultima_linha
      fi
    done

    # Wait 1 second to verify again
    sleep 1
  done
}

# Start function of monitoring
monitorar_logs

```

To access the bashscript in execution again is just:
`screen -x`

**Reply by mbround18** [reply]
That's pretty neat! Why not use the web hook env variable?

**Comment by zazuts** [comment]
I am using this to run my container today:
(And i think i've done something wrong coz the webhook wasnt working at all).

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PORT: 2456
      NAME: "Look2themoon"
      WORLD: "hardmode"
      PASSWORD: "morethan6digits"
      TZ: "America/Sao_Paulo"
      PUBLIC: 1
      AUTO_UPDATE: 1
      ENABLE_CROSSPLAY: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 2
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      WEBHOOK_URL: "https://discord.com/api/webhooks/lalala/lerolero"
      WEBHOOK_INCLUDE_PUBLIC_IP: 1
      UPDATE_ON_STARTUP: 0
      
    volumes:
      - ./valheimHARD/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheimHARD/server:/home/steam/valheim
      - ./valheimHARD/backups:/home/steam/backups
```


And today i found this:
https://github.com/mbround18/valheim-docker/blob/main/docker-compose.yml
And im planning to use to see if something changes.

Can you point me some directions?
