### DISCUSSION TITLE
Server starts without mods, wont start with mods.

### DISCUSSION THREAD

**Discussion by shesk** [mbround18/valheim-docker#701] [Help!] [answered]
Running Linux server with docker compose. Port forwarding enabled for 2457-2460. Am able to connect to my server running ghcr.io/lloesche/valheim-server image but couldn't get ValheimPlus to work so I decided to try this image. Added for context of port forwarding working, docker working, etc. However, with the Vanilla version of this image, I can't connect to the server. Any ideas why? How I can troubleshoot this issue?

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PUID: "1000"
      PGID: "1000"
      PORT: 2456
      NAME: "Valheim Docker"
      WORLD: "MyDedicated"
      PASSWORD: "[MASKED]"
      TYPE: "ValheimPlus"
      TZ: "America/Denver"
      PUBLIC: 1
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      UPDATE_ON_STARTUP: 0
    volumes:
      - /home/steam/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /home/steam/valheim/server:/home/steam/valheim
      - /home/steam/valheim/backups:/home/steam/backups
    restart: unless-stopped
```

EDIT: modified volumes directory. I'm running docker as another user, not one labeled 'steam'.
EDIT2: I got Vanilla working, I was missing PUID and PGID. But when add TYPE: "ValheimPlus" the server seems to hang. Takes forever while watching the logs. I also added a 'steam' user and modified group permissions so that my main user that runs docker has access to steam's home directory.
EDIT3: Tailed the docker logs, I think it has to do with the below error, but my googling didn't result in anything helpful.

```
Caught fatal signal - signo:11 code:1 errno:0 addr:0x3fb
Obtained 3 stack frames.
#0  0x007f6cc32b8520 in __sigaction
#1  0x007f6cc452a2c3 in Texture2D_CUSTOM_GetPixelImpl_Injected(ScriptingBackendNativeObjectPtrOpaque*, int, int, int, int, ColorRGBAf&)
#2  0x00000041a08465 in (wrapper managed-to-native) UnityEngine.Texture2D:GetPixelImpl_Injected (UnityEngine.Texture2D,int,int,int,UnityEngine.Color&)
```

EDIT4: With some testing, I get inconsistent server starts now with the simple docker compose sample on the docker hub page for mbround18/valheim. It ran successfully twice (2) out of fifteen (15) 'docker compose up -d' commands, the rest failed with this error:

```
==> /home/steam/valheim/logs/valheim_server.log <==
dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
05/14/2023 07:20:15: Server ID 90071992547409920
05/14/2023 07:20:15: Authentication:k_ESteamNetworkingAvailability_Waiting
05/14/2023 07:20:15: Steam game server initialized
05/14/2023 07:20:15: Using default prefs
05/14/2023 07:20:15: Valheim version: 0.215.2 (network version 1)
05/14/2023 07:20:15: Worldgenerator version setup:2
ERROR: Shader TextMeshPro/Sprite shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
05/14/2023 07:20:15: Render threading mode:SingleThreaded
05/14/2023 07:20:15: Missing audio clip in music respawn
05/14/2023 07:20:15: Builder started
GetPixel called on an undefined mip (valid values are 0 - 6
Caught fatal signal - signo:11 code:1 errno:0 addr:0x3fb
Obtained 3 stack frames.
#0  0x007f90a2fbf520 in __sigaction
#1  0x007f90a42312c3 in Texture2D_CUSTOM_GetPixelImpl_Injected(ScriptingBackendNativeObjectPtrOpaque*, int, int, int, int, ColorRGBAf&)
#2  0x00000041daf605 in (wrapper managed-to-native) UnityEngine.Texture2D:GetPixelImpl_Injected (UnityEngine.Texture2D,int,int,int,UnityEngine.Color&)
```
