### DISCUSSION TITLE
The world isn't saved when docker stops

### DISCUSSION THREAD

**Discussion by koksario** [mbround18/valheim-docker#719] [Help!]
Hello!
First of all thank you for the opportunity to run my own server

I have a problem with saving my world when I stop container. I use docker compose
I would like to save my world via any command cause I'm gonna restart a whole server each X hours
I brought files of the world from my local PC to the server
```
root@valheim:~# docker stop coi-valheim-1
coi-valheim-1
root@valheim:~# docker logs coi-valheim-1 | tail -4
ln: failed to create symbolic link '/home/steam/.steam/root': No such file or directory
ln: failed to create symbolic link '/home/steam/.steam/steam': No such file or directory
[Valheim][steam]: Halting server! Received interrupt!
[ODIN][INFO]  - Stopping server /home/steam/valheim
[ODIN][INFO]  - Scanning for Valheim process
[ODIN][INFO]  - Process NOT found!
root@valheim:~# ls -lt /config/worlds_local/ | head -7
total 50744
-rw-r----- 1 ubuntu netdev   46 Sep  6 15:34 PENA1.fwl
-rw-r----- 1 ubuntu netdev 7.9M Sep  6 15:34 PENA1.db
-rw-r----- 1 ubuntu netdev 7.9M Sep  6 15:34 PENA1_backup_auto-20230906153428.db
-rw-r----- 1 ubuntu netdev   46 Sep  6 15:34 PENA1_backup_auto-20230906153428.fwl
-rw-r----- 1 ubuntu netdev   46 Sep  6 14:17 PENA1.fwl.old
-rw-r----- 1 ubuntu netdev 7.9M Sep  6 14:17 PENA1.db.old
root@valheim:~# date
Wed 06 Sep 2023 04:03:02 PM UTC
root@valheim:~#
```

My docker compose yaml:
```
version: "3"
services:
  valheim:
    image: ghcr.io/mbround18/valheim
    stop_signal: SIGINT
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PORT: 2456
      NAME: "..."
      WORLD: "PENA1"
      PASSWORD: "..."
      PUBLIC: 1
      ENABLE_CROSSPLAY: 1
    volumes:
      - /config:/home/steam/.config/unity3d/IronGate/Valheim
      - /opt/valheim/:/home/steam/valheim
      - /backup/:/home/steam/backups
```
Additional info:
```
root@valheim:~# docker exec -it coi-valheim-1 bash
root@8b72462293bb:~# odin status
[ODIN][INFO]  - Name: AAAAAA
[ODIN][INFO]  - Players: 0/64#That's not true cause at least I'm online
[ODIN][INFO]  - Map: AAAAAA
[ODIN][INFO]  - BepInEx Enabled: false
root@8b72462293bb:~#
```
