### DISCUSSION TITLE
With the new update a fresh server won't start up with Bepinex.

### DISCUSSION THREAD

**Discussion by JohanVlugt** [mbround18/valheim-docker#756] [Help!] [answered]
I can see in the logs that Bepinex and the Mods are installed. But the server never starts up with the mods and there is no Bepinex log created.

Anyone else have this issue?

**Comment by mbround18** [comment]
@JohanVlugt  can you give us an out put from your sever? logs always should be created in the logs folder.

**Reply by JohanVlugt** [reply]
The logs look totally normal like an un-modded server. Server starts but without Bepinex.
Bepinex and Mods are installed by the server but never started. No chainloader, no output log of Bepinex.

```
[Valheim][steam]: Checking for TYPE flag
[Valheim][steam]: Found Type BepInEx
[Valheim][steam]: Running with BepInEx Valheim <3
[Valheim][steam]: Installing Mod  https://thunderstore.io/package/download/RandyKnapp/EpicLoot/0.9.34/
[ODIN][INFO]  - Installing  https://thunderstore.io/package/download/RandyKnapp/EpicLoot/0.9.34/
etc
Installing all my other mods
etc
```
```
[ODIN][ERROR] - Error: unable to set group, errno 1
==> /home/steam/valheim/logs/valheim_server.err <==
==> /home/steam/valheim/logs/output.log <==
==> /home/steam/valheim/logs/auto-update.out <==
==> /home/steam/valheim/logs/auto-backup.out <==
```
```
Game server connected
```
Everything works but without any mod loaded.

**Reply by mbround18** [reply]
Can you drop your docker compose without the password or sensitive data?

**Reply by JohanVlugt** [reply]
Sure:

```yaml
version: "3"
services:
  valheim:
    image: mbround18/valheim:2.3.1 
    stop_signal: SIGINT
    stop_grace_period: 1m
    container_name: valheim-server
    restart: unless-stopped
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PUID: 1000
      PGID: 1000
      # Server
      PORT: 2456
      NAME: "something1"
      WORLD: "something2"
      PASSWORD: "something3"
      TZ: "Europe/Warsaw"
      ENABLE_CROSSPLAY: 0
      PUBLIC: 1
      MODIFIERS: "resources=most, portals=casual, raids=more"
      # Mods
      TYPE: "BepInEx"
      MODS: "
        https://thunderstore.io/package/download/RandyKnapp/EpicLoot/0.9.34/,
        https://thunderstore.io/package/download/Smoothbrain/PassivePowers/1.0.12/,
        https://thunderstore.io/package/download/Smoothbrain/CreatureLevelAndLootControl/4.5.16/,
        https://thunderstore.io/package/download/Azumatt/AzuCraftyBoxes/1.2.4/,
        https://thunderstore.io/package/download/Azumatt/AzuContainerSizes/1.0.2/,
        https://thunderstore.io/package/download/Azumatt/AzuAutoStore/2.1.4/,
        https://thunderstore.io/package/download/MadBuffoon/TurretTweaks/2.0.0/,
        https://thunderstore.io/package/download/Advize/PlantEverything/1.15.2/,
        https://thunderstore.io/package/download/TastyChickenLegs/NoSmokeStayLit/2.3.1/,
        https://thunderstore.io/package/download/Vapok/AutoFeedRedux/1.0.3/,
        https://thunderstore.io/package/download/Mydayyy/ServerSideMap/1.3.10/
        "
      # Updates
      AUTO_UPDATE: 0
      AUTO_UPDATE_SCHEDULE: "0 2 * * *"
      UPDATE_ON_STARTUP: 0
      # Backups
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 7
      AUTO_BACKUP_ON_UPDATE: 0
      AUTO_BACKUP_ON_SHUTDOWN: 0
      AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS: 1
      # Restarts
      SCHEDULED_RESTART: 0
      SCHEDULED_RESTART_SCHEDULE: "0 3 * * *"
      # Discord
      # WEBHOOK_URL: "url"
      # WEBHOOK_INCLUDE_PUBLIC_IP: 0
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
```

**Reply by mbround18** [reply]
Have you tried removing plugins one at a time to see if ones a bad actor?

**Reply by JohanVlugt** [reply]
I also tried to run it without any mods:
```yaml
      TYPE: "BepInEx"
      MODS: ''
```
Same outcome as my original problem.

For reference I can run this exact mod pack without problem on the `lloesche` docker container, but I rather not use that container for other reasons.

My old backup of the server before the update runs normal with mods. After this update Bepinex doesn't load.

**Reply by andjo** [reply]
I'm having the same issue.
Yesterday the server was crashing on startup after the update, and today BepInEx does not appear to be loading at all.
Here is a startup from a clean slate:
```yaml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    container_name: valheim-test
    stop_signal: SIGINT
    ports:
      - "2476:2456/udp"
      - "2477:2457/udp"
      - "2478:2458/udp"
    environment:
      PORT: 2456
      NAME: "Test"
      WORLD: "Test"
      PASSWORD: "password"
      TZ: "Europe/Stockholm"
      PUBLIC: 0
      TYPE: "BepInEx"
      MODS: "https://gcdn.thunderstore.io/live/repository/packages/ValheimModding-Jotunn-2.14.6.zip"
      AUTO_UPDATE: 0
      UPDATE_ON_STARTUP: 0
      PUID: 1000
      PGID: 1000

    volumes:
      - /opt/valheim/test/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /opt/valheim/test/server:/home/steam/valheim
      - /opt/valheim/test/backups:/home/steam/backups

```
Log: https://gist.github.com/andjo/d7f023a506a98fee0c6aa02442a9ed7c

There are reports at https://github.com/BepInEx/BepInEx/issues that there is a problem with "BepInExPack_Valheim" after the update.
