### DISCUSSION TITLE
Metrics and status are incorrect

### DISCUSSION THREAD

**Discussion by mateuszkozakiewicz** [mbround18/valheim-docker#764] [Help!]
Hello,
I'm running a following setup:
```
image:
  repository: mbround18/valheim
  pullPolicy: Always
  tag: 2.3.2
container:
  env:
    - name: PUBLIC
      value: "1"
    - name: ENABLE_CROSSPLAY
      value: "1"
    - name: TYPE
      value: "BepInEx"
    - name: MODS
      value: |
        https://gcdn.thunderstore.io/live/repository/packages/Grantapher-ValheimPlus_Grantapher_Temporary-9.12.0.zip
    - name: AUTO_UPDATE
      value: "1"
    - name: AUTO_UPDATE_SCHEDULE
      value: "0 * * * *"
    - name: AUTO_UPDATE_PAUSE_WITH_PLAYERS
      value: "1"
    - name: AUTO_BACKUP
      value: "1"
    - name: AUTO_BACKUP_SCHEDULE
      value: "*/30 * * * *"
    - name: AUTO_BACKUP_DAYS_TO_LIVE
      value: "7"
    - name: AUTO_BACKUP_ON_UPDATE
      value: "1"
    - name: AUTO_BACKUP_ON_SHUTDOWN
      value: "1"
    - name: AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS
      value: "1"
    - name: SCHEDULED_RESTART
      value: "1"
    - name: SCHEDULED_RESTART_SCHEDULE
      value: "0 6 * * *"
    - name: HTTP_PORT
      value: "8080"
```

The `/status` and `/metrics` endpoint report incorrect information about player count, this is with 2 players connected:

```
odin --debug status

[ODIN][DEBUG] - Logger initialized
[ODIN][DEBUG] - Debug mode enabled!
[ODIN][DEBUG] - Env var found 'PORT': '2456'
[ODIN][DEBUG] - starting new connection: https://api.ipify.org/
[ODIN][DEBUG] - resolving host="api.ipify.org"
[ODIN][DEBUG] - connecting to REDACTED
[ODIN][DEBUG] - connected to REDACTED
[ODIN][DEBUG] - No cached session for DnsName("api.ipify.org")
[ODIN][DEBUG] - Not resuming any session
[ODIN][DEBUG] - Using ciphersuite TLS13_AES_256_GCM_SHA384
[ODIN][DEBUG] - Not resuming
[ODIN][DEBUG] - TLS1.3 encrypted extensions: [ServerNameAck, Protocols([ProtocolName(687474702f312e31)])]
[ODIN][DEBUG] - ALPN protocol is Some(b"http/1.1")
[ODIN][DEBUG] - flushed 52 bytes
[ODIN][DEBUG] - parsed 6 headers
[ODIN][DEBUG] - incoming body is content-length (12 bytes)
[ODIN][DEBUG] - incoming body completed
[ODIN][DEBUG] - pooling idle connection for ("https", api.ipify.org)
[ODIN][ERROR] - Failed to request server information!
[ODIN][DEBUG] - Env var found 'NAME': 'server name'
[ODIN][DEBUG] - Env var found 'NAME': 'server name'
[ODIN][INFO]  - Name: server name
[ODIN][INFO]  - Players: 0/0
[ODIN][INFO]  - Map: server name
[ODIN][INFO]  - BepInEx Enabled: false

 curl localhost:8080/status

{"name":"server name","version":"g=0.217.38,n=20,m=","players":0,"max_players":64,"map":"server name","online":true,"bepinex":{"enabled":true,"mods":[{"name":"Valheim.DisplayBepInExInfo.dll","location":"/home/steam/valheim/BepInEx/plugins/Valheim.DisplayBepInExInfo.dll"},{"name":"ValheimPlus.dll","location":"/home/steam/valheim/BepInEx/plugins/ValheimPlus_Grantapher_Temporary/BepInEx/plugins/ValheimPlus.dll"}]},"jobs":[{"name":"AUTO_UPDATE","enabled":true,"schedule":"0 * * * 

 curl localhost:8080/metrics

valheim_online{name="server name", version="g=0.217.38,n=20,m=", map="server name"} 1
valheim_current_player_count{name="server name", version="g=0.217.38,n=20,m=", map="server name"} 0
valheim_max_player_count{name="server name", version="g=0.217.38,n=20,m=", map="server name"} 64
valheim_bepinex_installed{name="server name", version="g=0.217.38,n=20,m=", map="server name"} 1
```

any advice?
This causes backups to never happen.
