### DISCUSSION TITLE
Can't use Odin at all in otherwise working container

### DISCUSSION THREAD

**Discussion by TheDenast** [mbround18/valheim-docker#771] [Q&A] [answered]
I've got docker image set up with docker-compose, and the server itself runs and we're able to connect, but I cannot control it with Odin at all, looking for any advice!

```bash
denast@denastServer ~/D/Valheim> docker exec valheim_valheim_1 odin status
[ODIN][ERROR] - Failed to request server information!
[ODIN][INFO]  - Name: servername
[ODIN][INFO]  - Players: 0/0
[ODIN][INFO]  - Map: servername
[ODIN][INFO]  - BepInEx Enabled: false
denast@denastServer ~/D/Valheim> docker exec valheim_valheim_1 odin stop
[ODIN][INFO]  - Stopping server /root
[ODIN][INFO]  - Scanning for Valheim process
[ODIN][INFO]  - Process NOT found!
denast@denastServer ~/D/Valheim> docker exec valheim_valheim_1 odin update
[ODIN][INFO]  - Checking for updates
[ODIN][INFO]  - steamcmd found in path
thread 'main' panicked at src/odin/server/update.rs:157:3:
Invalid app info
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Even if I run Odin from within, I get the same error:
```bash
denast@denastServer ~/D/Valheim [101]> docker exec -it valheim_valheim_1 gosu steam bash
steam@70fabb9a8965:~/valheim$ odin status
[ODIN][ERROR] - Failed to request server information!
[ODIN][INFO]  - Name: servername
[ODIN][INFO]  - Players: 0/0
[ODIN][INFO]  - Map: servername
[ODIN][INFO]  - BepInEx Enabled: false
steam@70fabb9a8965:~/valheim$ 
```

Here is my docker-compose.yml:
```
denast@denastServer ~/D/Valheim> cat docker-compose.yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    stop_signal: SIGINT
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      NAME: "servername"
      WORLD: "worldname"
      PASSWORD: "serverpass"
      TZ: "America/New_York"
      PUBLIC: 0
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
```
