### DISCUSSION TITLE
New error since updating container :( - thread 'main' panicked at src/odin/notifications/enums/notification_event.rs:67:49:

### DISCUSSION THREAD

**Discussion by auk5** [mbround18/valheim-docker#781] [Help!] [answered]
Hi, so I recently did the DySpy / Assembly_valheim.dll "fix" for my server. However after testing it I noticed my server was disconnecting after playing for 3-4minutes consistently. I couldn't figure out why, the logs just said user disconnected. I decided to delete my valheim folder entirely and start fresh (as I foolishly didn't backup the original assembly file!). 

Since then, I can't it to ever start the container again without failing. I'll post the full log below. I assumed this would take 2minutes just to re-create but I've spent 2 hours on it now and can't get it to do anything different.

Please help :( thank you!

**Snippet of error at the end of the log:**
```
[ODIN][INFO]  - Setting up start scripts...
[ODIN][INFO]  - Sending discord notification <3
thread 'main' panicked at src/odin/notifications/enums/notification_event.rs:67:49:
called `Result::unwrap()` on an `Err` value: AddrParseError(SocketV4)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Full log below:**
```
2024-01-26 12:59:56 - [Valheim][INFO]: Navigating to steam home...
2024-01-26 12:59:56 - [Valheim][INFO]: Launching as server...
2024-01-26 12:59:56 - #[INFO]: ###########################################################################
2024-01-26 12:59:56 - [Valheim][INFO]: Valheim Server - Fri Jan 26 12:59:56 PM GMT 2024
2024-01-26 12:59:56 - [Valheim][INFO]: STEAM_UID 1000 - STEAM_GUID 100
2024-01-26 12:59:56 - [Valheim][INFO]: Installing Valheim via odin 2.1.0...
2024-01-26 12:59:56 - #[INFO]: ###########################################################################
2024-01-26 12:59:56 - [Valheim][INFO]: Variables loaded.....
2024-01-26 12:59:56 - [Valheim][INFO]: Port: 2456
2024-01-26 12:59:56 - [Valheim][INFO]: Name: (REDACTED)
2024-01-26 12:59:56 - [Valheim][INFO]: World: (REDACTED)
2024-01-26 12:59:56 - [Valheim][INFO]: Public: 1
2024-01-26 12:59:56 - [Valheim][INFO]: With Crossplay: 0
2024-01-26 12:59:56 - [Valheim][INFO]: Password: (REDACTED)
2024-01-26 12:59:56 - [Valheim][INFO]: Preset: 
2024-01-26 12:59:56 - [Valheim][INFO]: Modifiers: 
2024-01-26 12:59:56 - [Valheim][INFO]: Set Key: 
2024-01-26 12:59:56 - [Valheim][INFO]: Has Webhook: true
2024-01-26 12:59:56 - [Valheim][INFO]: Auto Update: 1
2024-01-26 12:59:56 - [Valheim][INFO]: Auto Backup: 1
2024-01-26 12:59:56 - [Valheim][INFO]: Auto Backup On Update: 1
2024-01-26 12:59:56 - [Valheim][INFO]: Auto Backup On Shutdown: 1
2024-01-26 12:59:56 - [Valheim][INFO]: Auto Backup Pause With No Players: 1
2024-01-26 12:59:56 - [Valheim][INFO]: Auto Backup Pause With Players: 
2024-01-26 12:59:56 - [Valheim][INFO]: Auto Backup Remove Old: 1
2024-01-26 12:59:56 - [Valheim][INFO]: Auto Backup Days To Live: 1
2024-01-26 12:59:56 - [Valheim][INFO]: Auto Backup Nice Level: 
2024-01-26 12:59:56 - [Valheim][INFO]: Update On Startup: 0
2024-01-26 12:59:56 - [Valheim][INFO]: Mods: 
2024-01-26 12:59:56 - #[INFO]: ###########################################################################
2024-01-26 12:59:56 - [Valheim][INFO]: Running Install...
[ODIN][INFO]  - Installing 896660 to /home/steam/valheim
[ODIN][INFO]  - steamcmd found in path
ln: failed to create symbolic link '/home/steam/.steam/root': No such file or directory
ln: failed to create symbolic link '/home/steam/.steam/steam': No such file or directory
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 59,782 KB)...
[  0%] Downloading update (0 of 59,782 KB)...
[  0%] Downloading update (0 of 59,782 KB)...
[  0%] Downloading update (3,096 of 59,782 KB)...
[  5%] Downloading update (6,816 of 59,782 KB)...
[ 11%] Downloading update (9,355 of 59,782 KB)...
[ 15%] Downloading update (12,081 of 59,782 KB)...
[ 20%] Downloading update (14,549 of 59,782 KB)...
[ 24%] Downloading update (17,014 of 59,782 KB)...
[ 28%] Downloading update (19,485 of 59,782 KB)...
[ 32%] Downloading update (22,204 of 59,782 KB)...
[ 37%] Downloading update (24,692 of 59,782 KB)...
[ 41%] Downloading update (27,167 of 59,782 KB)...
[ 45%] Downloading update (29,649 of 59,782 KB)...
[ 49%] Downloading update (32,104 of 59,782 KB)...
[ 53%] Downloading update (34,561 of 59,782 KB)...
[ 57%] Downloading update (37,019 of 59,782 KB)...
[ 61%] Downloading update (39,483 of 59,782 KB)...
[ 66%] Downloading update (41,725 of 59,782 KB)...
[ 69%] Downloading update (42,959 of 59,782 KB)...
[ 71%] Downloading update (44,321 of 59,782 KB)...
[ 74%] Downloading update (45,560 of 59,782 KB)...
[ 76%] Downloading update (46,792 of 59,782 KB)...
[ 78%] Downloading update (48,141 of 59,782 KB)...
[ 80%] Downloading update (49,379 of 59,782 KB)...
[ 82%] Downloading update (50,616 of 59,782 KB)...
[ 84%] Downloading update (51,966 of 59,782 KB)...
[ 86%] Downloading update (53,206 of 59,782 KB)...
[ 88%] Downloading update (54,443 of 59,782 KB)...
[ 91%] Downloading update (55,800 of 59,782 KB)...
[ 93%] Downloading update (57,027 of 59,782 KB)...
[ 95%] Downloading update (58,265 of 59,782 KB)...
[ 97%] Downloading update (59,622 of 59,782 KB)...
[ 99%] Downloading update (59,782 of 59,782 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
tid(292) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
tid(304) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x1) running, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 5.43 (75878776 / 1396527811)
 Update state (0x61) downloading, progress: 17.94 (250534164 / 1396527811)
 Update state (0x61) downloading, progress: 36.07 (503713813 / 1396527811)
 Update state (0x61) downloading, progress: 42.83 (598102670 / 1396527811)
 Update state (0x61) downloading, progress: 49.96 (697725350 / 1396527811)
 Update state (0x61) downloading, progress: 57.15 (798066710 / 1396527811)
 Update state (0x61) downloading, progress: 60.62 (846599894 / 1396527811)
 Update state (0x61) downloading, progress: 64.62 (902376822 / 1396527811)
 Update state (0x61) downloading, progress: 68.53 (957099990 / 1396527811)
 Update state (0x61) downloading, progress: 72.30 (1009753942 / 1396527811)
 Update state (0x61) downloading, progress: 76.01 (1061523126 / 1396527811)
 Update state (0x61) downloading, progress: 79.75 (1113661846 / 1396527811)
 Update state (0x61) downloading, progress: 83.38 (1164402582 / 1396527811)
 Update state (0x61) downloading, progress: 87.48 (1221623798 / 1396527811)
 Update state (0x61) downloading, progress: 91.32 (1275377934 / 1396527811)
 Update state (0x61) downloading, progress: 95.36 (1331696662 / 1396527811)
 Update state (0x61) downloading, progress: 99.55 (1390236355 / 1396527811)
 Update state (0x81) verifying update, progress: 45.89 (640916012 / 1396527811)
 Update state (0x101) committing, progress: 100.00 (1396527811 / 1396527811)
Success! App '896660' fully installed.
[ODIN][INFO]  - Successfully installed Valheim!
2024-01-26 13:01:08 - [Valheim][INFO]: Initializing Variables....
[ODIN][INFO]  - Successfully written /home/steam/valheim/config.json
[ODIN][INFO]  - Successfully written /home/steam/valheim/discord.json
2024-01-26 13:01:08 - [Valheim][INFO]: Checking for TYPE flag
2024-01-26 13:01:08 - [Valheim][INFO]: Found Type Vanilla
2024-01-26 13:01:08 - [Valheim][INFO]: Running with Vanilla Valheim <3
2024-01-26 13:01:08 - [Valheim][INFO]: Starting server...
[ODIN][INFO]  - Setting up start scripts...
[ODIN][INFO]  - Sending discord notification <3
thread 'main' panicked at src/odin/notifications/enums/notification_event.rs:67:49:
called `Result::unwrap()` on an `Err` value: AddrParseError(SocketV4)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

END OF LINE
```

**Comment by mbround18** [comment]
Whats the address you are using for the webook? please omit anything thats private or direct message it to me on discord if its all private

**Reply by auk5** [reply]
Thanks for quick reply mbround18. I've got the server working again (after many hours and also getting it working on lloesche's docker image too) and I think it's the WEBHOOK_INCLUDE_PUBLIC_IP: 1 that is causing the error. If I comment it out the server works again as expected.

Now I don't have the IP address in the Discord message however :(

![image](https://github.com/mbround18/valheim-docker/assets/38418357/33e3c1a2-38f1-47b0-b3a6-af77946710a6)

Does it work for you I take it?

Here is my docker compose

version: "3"
services:

```
#Valheim
  valheim:
    image: mbround18/valheim:latest
    container_name: Valheim
    stop_signal: SIGINT
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      NAME: "BroWorld"
      WORLD: "BroWorld"
      PASSWORD: "REDACTED"
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/London"
      PUBLIC: 1
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 4 * * *"
      AUTO_UPDATE_PAUSE_WITH_PLAYERS: 1
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/20 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 2
      AUTO_BACKUP_DAYS_TO_LIVE: 2
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS: 1
      SCHEDULED_RESTART: 1
      SCHEDULED_RESTART_SCHEDULE: "0 5 * * *"
      WEBHOOK_URL: "https://discord.com/api/webhooks/1486984503223554397/Tw-yHP1L8HX8fA1aSuH6oyb0Jj8J_p_ErEeQE2aqvqNOgEhpcAByR1REDACTEDwixi3Z"
   #   WEBHOOK_INCLUDE_PUBLIC_IP: 1
      UPDATE_ON_STARTUP: 0
    volumes:
      - /srv/dev-disk-by-uuid-REDACTED/Valheim/valheim-mbround18/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /srv/dev-disk-by-uuid-REDACTED8/Valheim/valheim-mbround18/server:/home/steam/valheim
      - /srv/dev-disk-by-uuid-REDACTED/Valheim/valheim-mbround18/backups:/home/steam/backups
```

**Reply by mbround18** [reply]
i can give this a local test and take a gander :) looks like maybe the WEBHOOK_INCLUDE_PUBLIC_IP logic needs some tidying up

**Reply by auk5** [reply]
Thank you :). I've been using it for ages so perhaps it was the last update 4 days that broke it?

**Reply by auk5** [reply]
Did you have any chance to look into this one please? I've gone back to using version 2.3.2 now and it works fine with the public_ip bit showing up discord and no errors. If I use 2.4.0 or 2.4.1 they have the same rust error :(. If it helps I'm using OpenMediaVault fully patched.

**Reply by mbround18** [reply]
That does help yes! ive set aside some development time to dive into this over the weekend :) apologies on delay. If you would like to bypass the logic, on the container set ADDRESS to your servers public IP address. That should resolve your issue. 

```yaml
  valheim:
    image: mbround18/valheim:latest
    container_name: Valheim
    stop_signal: SIGINT
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      ADDRESS: "INSERT_PUBLIC_IP_HERE"
      
```


This is the logic that fetches ur public IP: https://github.com/mbround18/valheim-docker/blob/main/src/odin/utils/fetch_public_ip_address.rs#L7-L21

My guess is youir container cant hit `api.ipify.org`. Setting that env var `ADDRESS` should resolve it.
