### DISCUSSION TITLE
Not seeing expected content in server/logs/valheim_server.log anymore.

### DISCUSSION THREAD

**Discussion by georgedayiv** [mbround18/valheim-docker#782] [Q&A]
### Issue: 
The only content I'm seeing in my valheim_server.log file is:
```[ODIN][INFO]  - Success, daemonized```

I'd expect to see the same content or similar content to if I ran the docker container in the foreground, or ran docker-compose logs if it was daemonized. But, I'm not seeing that.

Up until 8 months ago I ran a docker instance for a small group of us playing together. I'd use that log file to parse for events and send notifications. Eventually, we finished with that world and moved on to other things. Over the past week or so, we've decided to start back up again. So I stood up another EC2 instance, provisioned it with scripts developed last time, and got things going. 

I immediately saw an issue with Odin permissions, found the discussions in the issues here, and watched it get fixed. I figured that was related to the log issue I was seeing. Then it was just ```[ODIN][ERROR] - Error: unable to set group, errno 1```. 

But, while Odin is obviously happy with the logs now based on it's message, I'm still not seeing the log output I'm looking for.
I tried to turn on DEBUG_MODE because perhaps that's what I want, but no dice.

I looked for other disussions and issues related to logs as well and didn't see anything. I thought I'd ask here in case anyone has any ideas. I'm an old server guy who loves logs and scripting, and am open to the idea that perhaps there's a different approach to solve what I'm trying to do, monitor the server for events in real-time and take action on them.

My setup is an EC2 instance running the docker image. My redacted compose file is:

```
version: "3"
services:
  valheim2:
    container_name: newgrog
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="NewGrogserverfortheGrognardMorlocks"
      - WORLD="NewGrog"
      - PASSWORD="[pw_redacted]"
      - TZ=America/Chicago
      - PUBLIC=0
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="0 6 * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=7
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - DEBUG_MODE = 1
    volumes:
      - ./newgrog/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./newgrog/server:/home/steam/valheim
      - ./newgrog/backups:/home/steam/backups
```
