### DISCUSSION TITLE
Invalid password after container has been running for an hour or so

### DISCUSSION THREAD

**Discussion by paulg087** [mbround18/valheim-docker#794] [Help!]
Hi - I have an otherwise properly working server that I can connect to on startup of the container, but after an hour or so (unsure on exact timing), anyone else trying to connect will get an invalid password response.  If a connected user logs out and tries to reconnect, they will also get an invalid password response.  

So far the only fix I have found is to restart the container.  I'm pretty new to docker, so I am not sure what the best way to troubleshoot this is.  Any advice or tips on where to look for log files, etc, would be appreciated.

Thanks!

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="name"
      - WORLD="Dedicated"
      - PASSWORD="<redacted>"
      - TZ=America/Chicago
      - PUBLIC=1
      - AUTO_UPDATE=0
      - ENABLE_CROSSPLAY=1
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS=1
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
 ```
