### DISCUSSION TITLE
Another permission PUID/PGID issue?

### DISCUSSION THREAD

**Discussion by mauvehed** [mbround18/valheim-docker#796] [Q&A] [answered]
I read through https://github.com/mbround18/valheim-docker/discussions/786 and tried some of what was there, but with no luck. I have a similar but slightly different issue.

```bash
❯ docker compose up
[+] Running 1/1
 ✔ Container valheim-mbround18-valheim-1  Recreated                                                                                              0.2s
Attaching to valheim-1
valheim-1  | America/Chicago
valheim-1  | 2024-03-06 20:00:19 - #[INFO]: ###########################################################################
valheim-1  | 2024-03-06 20:00:19 - [Valheim][INFO]: Valheim Server - Wed Mar  6 08:00:19 PM CST 2024
valheim-1  | 2024-03-06 20:00:19 - [Valheim][INFO]: Initializing your container...
valheim-1  | 2024-03-06 20:00:19 - [Valheim][INFO]: Total memory: 31GB
valheim-1  | 2024-03-06 20:00:19 - #[INFO]: ###########################################################################
valheim-1  | Configuring Preset Env
valheim-1  | export DEBUG_MODE=0
valheim-1  | export ODIN_CONFIG_FILE="/home/steam/valheim/config.json"
valheim-1  | export ODIN_DISCORD_FILE="/home/steam/valheim/discord.json"
valheim-1  | export ODIN_WORKING_DIR=""
valheim-1  | export SAVE_LOCATION="/home/steam/.config/unity3d/IronGate/Valheim"
valheim-1  | export MODS_LOCATION="/home/steam/staging/mods"
valheim-1  | export GAME_LOCATION="/home/steam/valheim"
valheim-1  | export BACKUP_LOCATION="/home/steam/backups"
valheim-1  | export NAME="Valhacka"
valheim-1  | export ADDRESS=""
valheim-1  | export PORT=2456
valheim-1  | export PUBLIC=0
valheim-1  | export ENABLE_CROSSPLAY=0
valheim-1  | export UPDATE_ON_STARTUP=1
valheim-1  | export SERVER_EXTRA_LAUNCH_ARGS=""
valheim-1  | export WEBHOOK_URL=""
valheim-1  | export WEBHOOK_STATUS_SUCCESSFUL=1
valheim-1  | export WEBHOOK_STATUS_FAILED=1
valheim-1  | export WEBHOOK_STATUS_RUNNING=1
valheim-1  | export WEBHOOK_INCLUDE_PUBLIC_IP=0
valheim-1  | export AUTO_UPDATE=0
valheim-1  | export AUTO_BACKUP=0
valheim-1  | export AUTO_BACKUP_REMOVE_OLD=1
valheim-1  | export AUTO_BACKUP_DAYS_TO_LIVE=3
valheim-1  | export AUTO_BACKUP_ON_UPDATE=0
valheim-1  | export AUTO_BACKUP_ON_SHUTDOWN=0
valheim-1  | export AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS=0
valheim-1  | export VALHEIM_PLUS_RELEASES_URL=""
valheim-1  | export VALHEIM_PLUS_DOWNLOAD_URL=""
valheim-1  | export BEPINEX_RELEASES_URL="https://valheim.thunderstore.io/api/experimental/package/denikson/BepInExPack_Valheim/"
valheim-1  | export BEPINEX_DOWNLOAD_URL=""
valheim-1  | export BEPINEX_FULL_RELEASES_URL=""
valheim-1  | Preset Env Configured
valheim-1  | 2024-03-06 20:00:19 - [Valheim][INFO]: Setting up file systems
valheim-1  | usermod: no changes
valheim-1  | /entrypoint.sh: line 151: cd: /home/steam: Permission denied
valheim-1 exited with code 0
```

```yaml
❯ cat docker-compose.yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    restart: unless-stopped
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Valhacka"
      - WORLD="ourworld"
      - PASSWORD="the password"
      - TYPE=vanilla
      - TZ=America/Chicago
      - PUBLIC=0
      - AUTO_UPDATE=0
      - PUID=1027
      - PGID=1027
    volumes:
    - /data/docker/valheim-mbround18/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - /data/docker/valheim-mbround18/valheim/server:/home/steam/valheim
    - /data/docker/valheim-mbround18/valheim/backups:/home/steam/backups
```

```bash
❯ id -u
1027
❯ pwd
/data/docker/valheim-mbround18
❯ ls -l
total 8
-rw-rw-r-- 1 nate nate 1016 Mar  6 19:58 docker-compose.yml
drwxrwxr-x 5 nate nate 4096 Mar  6 17:54 valheim
❯ ls -lR valheim
valheim:
total 12
drwxrwxr-x 2 nate nate 4096 Mar  6 17:54 backups
drwxrwxr-x 2 nate nate 4096 Mar  6 17:54 saves
drwxrwxr-x 3 nate nate 4096 Mar  6 19:43 server

valheim/backups:
total 0

valheim/saves:
total 0

valheim/server:
total 4
drwxrwxr-x 2 nate nate 4096 Mar  6 19:43 logs

valheim/server/logs:
total 0
```

You'll notice I even gave full write permissions to the group, but still I get the permission error on /home/steam
