### DISCUSSION TITLE
AUTO_UPDATE will not execute

### DISCUSSION THREAD

**Discussion by ericjgoebel** [mbround18/valheim-docker#809] [Help!] [answered]
**Steps:** 
Installed docker desktop on Windows 10 Pro
(pulled latest image)
Created docker-compose.yml
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    stop_signal: SIGINT
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      NAME: "Tacticals Realm"
      WORLD: "[mysecretworldname]"
      PASSWORD: "[mysecretpassword]"
      TZ: "America/New_York"
      PUBLIC: 1
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "*/15 * * * *"
      AUTO_UPDATE_PAUSE_WITH_PLAYERS: 1
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/5 * * * *"
      #AUTO_BACKUP_SCHEDULE: "0 */1 * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS: 0
      SCHEDULED_RESTART: 1
      SCHEDULED_RESTART_SCHEDULE: "15 4 * * *"
      UPDATE_ON_STARTUP: 1
      WEBHOOK_URL: [mysecretwebhook]
    volumes:
      - "S:\\Games\\Docker\\TacticalsRealm\\valheim\\saves:/home/steam/.config/unity3d/IronGate/Valheim"
      - "S:\\Games\\Docker\\TacticalsRealm\\valheim\\server:/home/steam/valheim"
      - "S:\\Games\\Docker\\TacticalsRealm\\valheim\\backups:/home/steam/backups"
```

Executed: `docker-compose up --detach`
Waited for auto-update time
Checked logs

**Expected**: Server is cleanly restarted (messages sent via webhook, world saved, restart, etc)

**Actual result:** A log file titled "scheduled-restart.out" is produced with the contents
`You must run this script as the steam user!`

Notes: as far as i can tell my user id is 1000 but I'm not certain I'm determining this correctly
```
docker exec tacticalsrealm-valheim-1 id -u    
1000
```
