### DISCUSSION TITLE
How to run public-test & what is the full modifier list and values or link to them

### DISCUSSION THREAD

**Discussion by acstanton515** [mbround18/valheim-docker#810] [Help!] [answered]
Can we modify docker-compose.yml file to update to public-test?

What is the right syntax?

Any link to the exact values for all modifier names and values?

Thank you.

**Comment by jojobyte** [comment, marked as answer]
Try adding `- USE_PUBLIC_BETA=1` or `USE_PUBLIC_BETA: 1` to `environment`

```yaml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    # ...
    environment:
       - USE_PUBLIC_BETA=1
       # ...
```

https://github.com/mbround18/valheim-docker/blob/5605d031001bd054820175ea7ad115059b0e1e88/src/odin/server/install.rs#L14-L35
