### DISCUSSION TITLE
Update never get complete on trying to start docker container

### DISCUSSION THREAD

**Discussion by salsa2k** [mbround18/valheim-docker#837] [Help!] [answered]
Hi,

I started a fresh container using docker-compose but for some reason, the update state never gets completed. It always goes till 99% but never completes.

![image](https://github.com/mbround18/valheim-docker/assets/4088662/d13ab8af-269f-4971-838d-1e7f6ba310c0)

here is my docker-compose:
```
version: "3"

services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Valheim Server"
      - WORLD="Dedicated"
      - PASSWORD="pass"
      - TZ=America/Toronto
      - PUBLIC=1
      - AUTO_UPDATE=0
      - PUID=1001
      - PGID=1001
    volumes:
    - /mnt/tower/appdata/valheim-server/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - /mnt/tower/appdata/valheim-server/server:/home/steam/valheim

    restart: always
    stop_grace_period: 2m
```
