### DISCUSSION TITLE
How to download a specfic branch?

### DISCUSSION THREAD

**Discussion by Oglaf** [mbround18/valheim-docker#845] [Help!] [answered]
I wish to keep my server with the last stable build before Ashlands because of mods but I can't figure out the correct command for `ADDITIONAL_STEAMCMD_ARGS`

So far I have tried:
`- ADDITIONAL_STEAMCMD_ARGS ="-beta default_preal"`
`- ADDITIONAL_STEAMCMD_ARGS ="app_update  896660 -beta default_preal"`
`- ADDITIONAL_STEAMCMD_ARGS ="+app_update  896660 -beta default_preal"`

My full docker-compose:
```yaml
valheim-reborn:
    image: mbround18/valheim:latest
    container_name: valheim-server-reborn
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      - PORT="2456"
      - TYPE=BepInEx
      - NAME=<redacted>
      - WORLD=<redacted>
      - PASSWORD=<redacted>
      - TZ=America/Sao_Paulo
      - ENABLE_CROSSPLAY=0
      - PUBLIC=0
      - PRESET="Normal"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="0 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=2
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP = 0
      - ADDITIONAL_STEAMCMD_ARGS ="-beta default_preal"
      - WEBHOOK_URL=<redacted>
      - "MODS=
        https://thunderstore.io/package/download/Advize/PlantEverything/1.16.5/,
        https://thunderstore.io/package/download/Azumatt/AzuAreaRepair/1.1.4/,
        https://thunderstore.io/package/download/Azumatt/AzuContainerSizes/1.0.3/,
        https://thunderstore.io/package/download/Azumatt/AzuCraftyBoxes/1.2.9/,
        https://thunderstore.io/package/download/Azumatt/AzuExtendedPlayerInventory/1.3.12/,
        https://thunderstore.io/package/download/Azumatt/AzuMapDetails/1.0.3/,
        https://thunderstore.io/package/download/Azumatt/AzuMiscPatches/1.2.2/,
        https://thunderstore.io/package/download/Azumatt/AzuWearNTearPatches/1.0.4/,
        https://thunderstore.io/package/download/Azumatt/AzuWorkbenchTweaks/1.0.3/,
        https://thunderstore.io/package/download/Azumatt/ProfitablePieces/1.0.3/,
        https://thunderstore.io/package/download/Azumatt/Recycle_N_Reclaim/1.3.3/,s
        https://thunderstore.io/package/download/CW_Jesse/BetterNetworking_Valheim/2.3.2/,
        https://thunderstore.io/package/download/flashybaps/BeastsOfBurdenEV/1.0.5/,
        https://thunderstore.io/package/download/Frogger/GroundReset/2.5.1/
        https://thunderstore.io/package/download/Goldenrevolver/Quick_Stack_Store_Sort_Trash_Restock/1.4.7/,
        https://thunderstore.io/package/download/ishid4/BetterArchery/1.9.5/,
        https://thunderstore.io/package/download/JereKuusela/Dungeon_Splitter/1.1.0/
        https://thunderstore.io/package/download/JewelHeim/HealthDisplay/2.0.3/,
        https://thunderstore.io/package/download/Marlthon/OdinShip/0.4.2/,
        https://thunderstore.io/package/download/MSchmoecker/MultiUserChest/0.5.10/,
        https://thunderstore.io/package/download/OdinPlus/OdinArchitect/1.2.7/,
        https://thunderstore.io/package/download/OdinPlus/TeleportEverything/2.6.1/,
        https://thunderstore.io/package/download/RandyKnapp/EpicLoot/0.9.38/,
        https://thunderstore.io/package/download/Smoothbrain/ConfigWatcher/1.0.1/,
        https://thunderstore.io/package/download/Smoothbrain/Exploration/1.0.3/,
        https://thunderstore.io/package/download/Smoothbrain/Farming/2.1.12/,
        https://thunderstore.io/package/download/Smoothbrain/Foraging/1.0.8/,
        https://thunderstore.io/package/download/Smoothbrain/Groups/1.2.7/,
        https://thunderstore.io/package/download/Smoothbrain/Lumberjacking/1.0.5/,
        https://thunderstore.io/package/download/Smoothbrain/Mining/1.1.5/,
        https://thunderstore.io/package/download/Smoothbrain/Ranching/1.1.3/,
        https://thunderstore.io/package/download/Smoothbrain/Sailing/1.1.7/,
        https://thunderstore.io/package/download/Smoothbrain/SmoothSave/1.0.5/,
        https://thunderstore.io/package/download/Smoothbrain/StartupAccelerator/1.0.2/,
        https://thunderstore.io/package/download/Smoothbrain/Tenacity/1.0.3/,
        https://thunderstore.io/package/download/Smoothbrain/Vitality/1.1.2/,
        https://thunderstore.io/package/download/SpikeHimself/XPortal/1.2.20/,
        https://thunderstore.io/package/download/TastyChickenLegs/AutomaticFuel/1.3.9/,
        https://thunderstore.io/package/download/TastyChickenLegs/NoSmokeStayLit/2.3.1/,
        https://thunderstore.io/package/download/Therzie/Armory/1.1.9/,
        https://thunderstore.io/package/download/Therzie/Monstrum/1.3.8/,
        https://thunderstore.io/package/download/Therzie/MonstrumAshlands/1.1.8/,
        https://thunderstore.io/package/download/Therzie/MonstrumDeepNorth/1.2.0/,
        https://thunderstore.io/package/download/Therzie/Warfare/1.6.8/,
        https://thunderstore.io/package/download/Therzie/WarfareFireAndIce/1.1.7/,
        https://thunderstore.io/package/download/VAG/SharedRecipeFinder/1.0.0/,
        https://thunderstore.io/package/download/ValheimModding/Jotunn/2.19.4/,
        https://thunderstore.io/package/download/VentureValheim/Venture_Floating_Items/0.2.1/,
        "
    volumes:
      - ./valheim-reborn/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim-reborn/server:/home/steam/valheim
      - ./valheim-reborn/backups:/home/steam/backups
    restart: unless-stopped
```

**Comment by mbround18** [comment]
That is the correct method, give me a few moments, i can make this accessible via an env var https://github.com/mbround18/valheim-docker/blob/79348e1c092ac0680c6d2dc88d5ec444cca7a8d2/src/odin/server/install.rs#L31C49-L32C5

**Reply by Oglaf** [reply]
Thank you!

**Reply by mbround18** [reply]
Apologies this took a little bit, i had to resolve a permissions issue introduced in the updated docker upstream container. Got an PR up for it here: https://github.com/mbround18/valheim-docker/pull/846

if youd like to test it out, try it with: 

```yaml
services:
  valheim:
    image: mbround18/valheim:sha-99d0836
    environment:
      - BETA_BRANCH=BEANCH_YOU_WANT
      - "BETA_BRANCH_PASSWORD=password-you-needf"
```

**Reply by Oglaf** [reply]
Thank you for taking the time to investigate this issue!

I tried to test on my second container, which I'm using to test Ashlands mod compatibility. My goal was to revert the client back to pre-Ashlands. However, it didn't work.

`rm: cannot remove '/home/steam/valheim/logs/auto-update.out': Permission denied`

In my second test, I deleted all files and tried to do a "clean install," but that didn't work either:
`mkdir: cannot create directory ‘/home/steam/valheim/logs’: Permission denied`

Full log:
```
Thu May 16 05:59:09 PM -03 2024 - Valheim Server - Thu May 16 05:59:09 PM -03 2024
Thu May 16 05:59:09 PM -03 2024 - Initializing your container...
steam
111
1000
America/Sao_Paulo
(standard_in) 1: syntax error
2024-05-16 17:59:09 - [Valheim][INFO]: Total memory: 15i GB
2024-05-16 17:59:09 - [Valheim][INFO]: Configuring Preset Env
export ODIN_CONFIG_FILE="/home/steam/valheim/config.json"
export ODIN_DISCORD_FILE="/home/steam/valheim/discord.json"
export SAVE_LOCATION="/home/steam/.config/unity3d/IronGate/Valheim"
export MODS_LOCATION="/home/steam/staging/mods"
export GAME_LOCATION="/home/steam/valheim"
export BACKUP_LOCATION="/home/steam/backups"
export NAME=<redacted>
export PORT=""2456""
export PUBLIC="0"
export ENABLE_CROSSPLAY="0"
export UPDATE_ON_STARTUP="1"
export PRESET=""Normal""
export WEBHOOK_URL=<redacted>
export WEBHOOK_STATUS_SUCCESSFUL="1"
export WEBHOOK_STATUS_FAILED="1"
export AUTO_UPDATE="1"
export AUTO_BACKUP="0"
export AUTO_BACKUP_REMOVE_OLD="1"
export AUTO_BACKUP_DAYS_TO_LIVE="2"
export AUTO_BACKUP_ON_UPDATE="1"
export AUTO_BACKUP_ON_SHUTDOWN="1"
export AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS="0"
export BETA_BRANCH="default_preal"
2024-05-16 17:59:09 - [Valheim][INFO]: Preset Env Configured
mkdir: cannot create directory ‘/home/steam/valheim/logs’: Permission denied
```

docker compose:
``` yaml
valheim-ashlands:
    image: mbround18/valheim:sha-99d0836
    container_name: valheim-ashlands
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      - PORT="2456"
      - TYPE=BepInEx
      - NAME=<redacted>
      - WORLD=<redacted>
      - PASSWORD=<redacted>
      - TZ=America/Sao_Paulo
      - ENABLE_CROSSPLAY=0
      - PUBLIC=0
      - PRESET="Normal"
      - AUTO_UPDATE=1
      - AUTO_BACKUP=0
      - AUTO_BACKUP_SCHEDULE="0 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=2
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP=1
      - BETA_BRANCH=default_preal
      - WEBHOOK_URL=<redacted>
      - "MODS=
        https://thunderstore.io/package/download/Advize/PlantEverything/1.17.1/,
        https://thunderstore.io/package/download/Azumatt/AzuAreaRepair/1.1.4/,
        https://thunderstore.io/package/download/Azumatt/AzuContainerSizes/1.0.3/,
        https://thunderstore.io/package/download/Azumatt/AzuCraftyBoxes/1.3.0/,
        https://thunderstore.io/package/download/Azumatt/AzuExtendedPlayerInventory/1.4.0/,
        https://thunderstore.io/package/download/Azumatt/AzuMapDetails/1.0.3/,
        https://thunderstore.io/package/download/Azumatt/AzuMiscPatches/1.2.2/,
        https://thunderstore.io/package/download/Azumatt/AzuWearNTearPatches/1.0.4/,
        https://thunderstore.io/package/download/Azumatt/AzuWorkbenchTweaks/1.0.3/,
        https://thunderstore.io/package/download/Azumatt/ProfitablePieces/1.0.3/,
        https://thunderstore.io/package/download/Azumatt/Recycle_N_Reclaim/1.3.4/,
        https://thunderstore.io/package/download/CW_Jesse/BetterNetworking_Valheim/2.3.2/,
        https://thunderstore.io/package/download/flashybaps/BeastsOfBurdenEV/1.0.5/,
        https://thunderstore.io/package/download/Goldenrevolver/Quick_Stack_Store_Sort_Trash_Restock/1.4.7/,
        https://thunderstore.io/package/download/ishid4/BetterArchery/1.9.5/,
        https://thunderstore.io/package/download/JereKuusela/Dungeon_Splitter/1.1.0/,
        https://thunderstore.io/package/download/JewelHeim/HealthDisplay/2.0.3/,
        https://thunderstore.io/package/download/Marlthon/OdinShip/0.4.3/,
        https://thunderstore.io/package/download/MSchmoecker/MultiUserChest/0.5.10/,
        https://thunderstore.io/package/download/OdinPlus/OdinArchitect/1.2.7/,
        https://thunderstore.io/package/download/OdinPlus/TeleportEverything/2.6.1/,
        https://thunderstore.io/package/download/RandyKnapp/EpicLoot/0.10.1/,
        https://thunderstore.io/package/download/Smoothbrain/Exploration/1.0.3/,
        https://thunderstore.io/package/download/Smoothbrain/Farming/2.1.12/,
        https://thunderstore.io/package/download/Smoothbrain/Foraging/1.0.9/,
        https://thunderstore.io/package/download/Smoothbrain/Groups/1.2.8/,
        https://thunderstore.io/package/download/Smoothbrain/Lumberjacking/1.0.5/,
        https://thunderstore.io/package/download/Smoothbrain/Mining/1.1.5/,
        https://thunderstore.io/package/download/Smoothbrain/Ranching/1.1.3/,
        https://thunderstore.io/package/download/Smoothbrain/Sailing/1.1.7/,
        https://thunderstore.io/package/download/Smoothbrain/SmoothSave/1.0.5/,
        https://thunderstore.io/package/download/Smoothbrain/StartupAccelerator/1.0.2/,
        https://thunderstore.io/package/download/Smoothbrain/Tenacity/1.0.3/,
        https://thunderstore.io/package/download/SpikeHimself/XPortal/1.2.20/,
        https://thunderstore.io/package/download/TastyChickenLegs/AutomaticFuel/1.4.1/,
        https://thunderstore.io/package/download/TastyChickenLegs/NoSmokeStayLit/2.3.1/,
        https://thunderstore.io/package/download/Therzie/Armory/1.2.0/,
        https://thunderstore.io/package/download/Therzie/Monstrum/1.3.9/,
        https://thunderstore.io/package/download/Therzie/Warfare/1.7.1/,
        https://thunderstore.io/package/download/Therzie/Wizardry/1.0.0/,
        https://thunderstore.io/package/download/VAG/SharedRecipeFinder/1.0.0/,
        https://thunderstore.io/package/download/ValheimModding/Jotunn/2.20.0/,
        https://thunderstore.io/package/download/VentureValheim/Venture_Floating_Items/0.2.2/
        "
    volumes:
      - ./valheim-ashlands/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim-ashlands/server:/home/steam/valheim
      - ./valheim-ashlands/backups:/home/steam/backups
    restart: unless-stopped
```

**Reply by mbround18** [reply]
could you delete the server directory contents completely and retry?

**Reply by Oglaf** [reply]
I created another container, no mods, same error.

Log:
```
Fri May 17 12:24:23 PM -03 2024 - Valheim Server - Fri May 17 12:24:23 PM -03 2024
Fri May 17 12:24:23 PM -03 2024 - Initializing your container...
steam
111
1000
America/Sao_Paulo
(standard_in) 1: syntax error
2024-05-17 12:24:23 - [Valheim][INFO]: Total memory: 15i GB
2024-05-17 12:24:23 - [Valheim][INFO]: Configuring Preset Env
export ODIN_CONFIG_FILE="/home/steam/valheim/config.json"
export ODIN_DISCORD_FILE="/home/steam/valheim/discord.json"
export SAVE_LOCATION="/home/steam/.config/unity3d/IronGate/Valheim"
export MODS_LOCATION="/home/steam/staging/mods"
export GAME_LOCATION="/home/steam/valheim"
export BACKUP_LOCATION="/home/steam/backups"
export NAME="test"
export PORT=""2456""
export PUBLIC="0"
export ENABLE_CROSSPLAY="0"
export UPDATE_ON_STARTUP="1"
export PRESET=""Normal""
export WEBHOOK_STATUS_SUCCESSFUL="1"
export WEBHOOK_STATUS_FAILED="1"
export AUTO_UPDATE="1"
export AUTO_BACKUP="0"
export AUTO_BACKUP_REMOVE_OLD="1"
export AUTO_BACKUP_DAYS_TO_LIVE="2"
export AUTO_BACKUP_ON_UPDATE="1"
export AUTO_BACKUP_ON_SHUTDOWN="1"
export AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS="0"
export BETA_BRANCH="default_preal"
2024-05-17 12:24:23 - [Valheim][INFO]: Preset Env Configured
mkdir: cannot create directory ‘/home/steam/valheim/logs’: Permission denied
```

docker compose:
```yaml
valheim-sha-99d0836:
    image: mbround18/valheim:sha-99d0836
    container_name: valheim-sha-99d0836
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      - PORT="2456"
      - TYPE=BepInEx
      - NAME=test
      - WORLD=test
      - PASSWORD=test
      - TZ=America/Sao_Paulo
      - ENABLE_CROSSPLAY=0
      - PUBLIC=0
      - PRESET="Normal"
      - AUTO_UPDATE=1
      - AUTO_BACKUP=0
      - AUTO_BACKUP_SCHEDULE="0 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=2
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP=1
      - BETA_BRANCH=default_preal
    volumes:
      - ./valheim-sha-99d0836/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim-sha-99d0836/server:/home/steam/valheim
      - ./valheim-sha-99d0836/backups:/home/steam/backups
    restart: unless-stopped
```

**Reply by mbround18** [reply]
My apologies this took a while, this should work `mbround18/valheim:sha-54d9a4a`

**Reply by Oglaf** [reply]
The permission issue is resolved, but unfortunately, it has downloaded build 14399912 (ashlands). Additionally, I had to change the TYPE from BepInEx to Vanilla because it was throwing an invalid URL exception and shutting down the server.

BepInEx error:
```
Waiting for client config...OK
Waiting for user info...OK
Success! App '896660' already up to date.
[ODIN][INFO] : Successfully installed Valheim!
2024-05-18 21:03:55 - [Valheim][INFO]: Initializing Variables....
[ODIN][INFO] : Checking directory permissions: "/home/steam/valheim"
[ODIN][INFO] : Checking directory permissions: "/home/steam/scripts"
[ODIN][INFO] : Checking file permissions: "/home/steam/.bashrc"
[ODIN][INFO] : Successfully written /home/steam/valheim/config.json
2024-05-18 21:03:55 - [Valheim][INFO]: Checking for TYPE flag
2024-05-18 21:03:55 - [Valheim][INFO]: Found Type BepInEx
2024-05-18 21:03:55 - [Valheim][INFO]: Running with BepInEx Valheim <3
2024-05-18 21:03:55 - [Valheim][INFO]: Installing BepInEx
2024-05-18 21:03:55 - [Valheim][INFO]: Fetching BepInEx download URL...
curl: (3) URL using bad/illegal format or missing URL
2024-05-18 21:03:55 - [Valheim][INFO]: Pulling BepInEx from 
[ODIN][INFO] : Installing 
[ODIN][ERROR]: Failed to download mod with invalid url: 
```

appmanifest:
```
"AppState"
{
	"appid"		"896660"
	"Universe"		"1"
	"name"		"Valheim Dedicated Server"
	"StateFlags"		"4"
	"installdir"		"Valheim dedicated server"
	"LastUpdated"		"1716076914"
	"LastPlayed"		"0"
	"SizeOnDisk"		"2346408748"
	"StagingSize"		"0"
	"buildid"		"14399912"
	"LastOwner"		"76561201559912837"
	"UpdateResult"		"0"
	"BytesToDownload"		"1229201520"
	"BytesDownloaded"		"1229201520"
	"BytesToStage"		"2346408748"
	"BytesStaged"		"2346408748"
	"TargetBuildID"		"14399912"
	"AutoUpdateBehavior"		"0"
	"AllowOtherDownloadsWhileRunning"		"0"
	"ScheduledAutoUpdate"		"0"
	"InstalledDepots"
	{
		"1006"
		{
			"manifest"		"4884950798805348056"
			"size"		"73781292"
		}
		"896661"
		{
			"manifest"		"3427869460738658349"
			"size"		"2272627456"
		}
	}
	"UserConfig"
	{
	}
	"MountedConfig"
	{
	}
}
```

docker compose:
```yaml
valheim-sha-54d9a4a:
    image: mbround18/valheim:sha-54d9a4a
    container_name: valheim-ashlands
    ports:
      - "2459:2459/udp"
    environment:
      - PORT="2459"
      - TYPE=Vanilla
      - NAME=Testing
      - WORLD=Testing
      - PASSWORD=Testing
      - TZ=America/Sao_Paulo
      - ENABLE_CROSSPLAY=0
      - PUBLIC=0
      - PRESET="Normal"
      - AUTO_UPDATE=1
      - AUTO_BACKUP=0
      - AUTO_BACKUP_SCHEDULE="0 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=2
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP=1
      - BETA_BRANCH=default_preal
    volumes:
      - ./valheim-sha-54d9a4a/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim-sha-54d9a4a/server:/home/steam/valheim
      - ./valheim-sha-54d9a4a/backups:/home/steam/backups
    restart: unless-stopped
```
