### DISCUSSION TITLE
Valheim Server Rasberry Pi 4 B

### DISCUSSION THREAD

**Discussion by ByronZA94** [mbround18/valheim-docker#891] [Q&A] [answered]
## System Information

Operating System: madhouse@madhouse:~ $ hostnamectl
 Static hostname: madhouse
       Icon name: computer
      Machine ID: ea0e1e0ffa0d439dbf21bb655bd5b983
         Boot ID: 6750b97f063f481eb62fb0f7dcee6697
Operating System: Debian GNU/Linux 12 (bookworm)  
          Kernel: Linux 6.6.31+rpt-rpi-v8
    Architecture: arm64

Docker Version: 20.10.24 build 297E128
Docker Compose Version: 1.29.2 build unknown
User & Group On Host: madhouse - assigned the docker group

## Issue Description

![image](https://github.com/mbround18/valheim-docker/assets/122814256/214aaa9e-f2a8-4f6d-a7e2-5a76d923af28)

![image](https://github.com/mbround18/valheim-docker/assets/122814256/33f5ab8a-0bc2-4a46-b411-78fceedd19d3)

version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Valheim Server on Docker"
      - WORLD="Dedicated"
      - PASSWORD="SuperSecurePass"
      - TZ=Africa/Johannesburg
      - PUBLIC=0
      - AUTO_UPDATE=0
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheimservices:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - $HOME/valheim-server/valheim.env
    restart: always
    
    
![image](https://github.com/mbround18/valheim-docker/assets/122814256/fc7b7ae7-1b2c-4a49-9685-b0e03d23228a)

I am not able to launch the server I get the error in the screenshot, perhaps you can mention where I need to change file paths or the compose file?

**Comment by ByronZA94** [comment]
@mbround18

Perhaps you could assist

**Reply by mbround18** [reply, marked as answer]
Change the service names to be unique

Docker doesnt allow two services to have the same name.

Invalid: 

```yaml
services:
  valheim:
  valheim:
```
Valid:

```yaml
services:
  valheim-0:
  valheim-1:
```

**Reply by ByronZA94** [reply]
![image](https://github.com/user-attachments/assets/7c1efdbd-7da0-43cf-9dd6-a79ddce64749)
Im using the same compose file though did the language update? Perhaps I need to find a newer compose file?

**Reply by mbround18** [reply]
For me, please paste ur compose file here lol, its hard to read and parse from an image.

Next to the compose file you need a folder called valheim, it looks like you have nested servers. try something like this 



```
.
├── docker-compose.yaml
├── server
│   ├── config
│   └── data
└── server-1
    ├── data
    └── saves

6 directories, 1 file

```


```yaml
version: "3"
services:
  valheim-1:
    image: mbround18/valheim:latest
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      - PORT=2456
      - NAME="Valheim Server on Docker"
      - WORLD="Dedicated"
      - PASSWORD="SecurePassWord"
      - TZ=Africa/Johannesburg
      - PUBLIC=0
      - AUTO_UPDATE=0
    volumes:
      - ./server-1/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./server-1/data:/home/steam/valheim
  valheim:
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - SYS_NICE
    volumes:
      - ./server/config:/config
      - ./server/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - ./server/valheim.env
    restart: always
    stop_grace_period: 2m
```
