### DISCUSSION TITLE
Can't connect

### DISCUSSION THREAD

**Discussion by JordanRhode** [mbround18/valheim-docker#894] [Help!]
Hello, I have the container running on my computer, TCPView shows the ports are in use. I have crossplay enabled, ports forwarded on my router, and I'm unable to connect directly to my public IP. I'm using the Xbox Game Pass version of the game. I did notice this in the logs, unsure if it's related: `New session server "Egg Boys" that has join code , now 0 player(s)`

![image](https://github.com/user-attachments/assets/74f0efdb-933f-4168-ae48-90e88ffb30b2)

Logs showing game server connected:
![image](https://github.com/user-attachments/assets/13475c3b-c2bc-4c19-a6da-280d6c09920f)

Outbound rule in my windows firewall:
![image](https://github.com/user-attachments/assets/6a60876e-cd7d-4f3a-8d61-d250dbf5749f)

Ports forwarded on my Google WiFi router:
![image](https://github.com/user-attachments/assets/79712e47-19a7-4558-913f-60ab59bff1aa)

My docker-compose file:
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PORT: 2456
      NAME: "Egg Boys"
      WORLD: "EggBoys"
      PASSWORD: ""
      TZ: "America/Chicago"
      PUBLIC: 1
      AUTO_UPDATE: 0
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      UPDATE_ON_STARTUP: 0
      ENABLE_CROSSPLAY: 1
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
```
