### DISCUSSION TITLE
New System PUID:GUID problem

### DISCUSSION THREAD

**Discussion by foolishrunner** [mbround18/valheim-docker#899] [Help!]
Hey, I've been using the image flawlessly for a while now and recently migrated my server to new hardware and ubuntu 22.04, from 20.04.  

After a system reboot the valheim servers constantly restart if I have the PUID: in the docker compose file set to 1000, my user.  I own all the files/dirs etc.  If I remove the PUID / GUID from the docker file it sets speech-dispatcher:x:111:29:Speech Dispatcher to all dirs/files, but it runs fine.

valheimServer01  | 0 1 * * * BASH_ENV=/env.sh /bin/bash /home/steam/scripts/auto_update.sh >> /home/steam/valheim/logs/auto-update.out 2>&1
valheimServer01  | chmod: changing permissions of '/home/steam/cron.d/auto-update': Operation not permitted
valheimServer01 exited with code 0

valheim_server.err
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 4 milliseconds to initialize
Setting breakpad minidump AppID = 892970
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  ### [API loaded no]
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.

If I run - docker compose up -d --force-recreate I can get the server to start up.

    environment:
      PUID: 1000
      PGID: 1000

Old system inside docker container /etc/passwd- steam:x:1000:65534::/home/steam:/bin/bash
New system inside docker container /etc/passwd - steam:x:111:1000::/home/steam:/bin/bash

Any ideas?

**Comment by foolishrunner** [comment]
Have pulled version 2.1.2 which is what I had last pulled on the previous hardware and it's working.

**Comment by foolishrunner** [comment]
> [v3.0.0](https://github.com/mbround18/valheim-docker/releases/tag/v3.0.0)
> 💥 Breaking Change
> 
>     rework shell and docker logic with reworked readme https://github.com/mbround18/valheim-docker/pull/846 ([@mbround18](https://github.com/mbround18))
> 
>     Note: this reworks the user permissions which had a major change in later versions of ubuntu. Expected PUID is 111 and GUID can be dynamic.

**Comment by foolishrunner** [comment]
Can anyone explain to me why or how to work around my local user for PUID 111 is speech-dispatcher?

**Reply by mbround18** [reply]
Set a group id to your local user id and use the same group id for the docker container

**Reply by mbround18** [reply]
1. **Create a new group named `valheim`:**

```bash
sudo groupadd valheim
```

2. **Add your current user to the `valheim` group:**

```bash
sudo usermod -a -G valheim $USER
```

3. **Verify that the group was created and your user was added successfully:**

```bash
groups $USER
```

4. **Find the group ID (GID) of the `valheim` group:**

```bash
getent group valheim
```

This command will output something like `valheim:x:1001:`, where `1001` is the GID.

5. **Set the permissions for the directories to be group writable, readable, and executable:**

```bash
sudo chown -R :valheim ./saves ./server ./backups
sudo chmod -R 775 ./saves ./server ./backups
```

6. **Update your `docker-compose.yml` file to set the PGID:**

Open your `docker-compose.yml` file in a text editor and modify it as follows:

```yaml
version: '3'
services:
  valheim:
    image: mbround18/valheim:latest
    container_name: valheim
    environment:
      - PGID=1001  # Replace with the actual GID from step 4
    volumes:
      - ./saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./server:/home/steam/valheim
      - ./backups:/home/steam/backups
    ports:
      - "2456-2458:2456-2458/udp"
    restart: unless-stopped
```

Replace `1001` with the actual GID you found in step 4. You can also dynamically set the PUID using the `id -u` command to get your current user ID.

7. **Restart your Docker Compose services to apply the changes:**

```bash
docker-compose down
docker-compose up -d
```

This will recreate the container with the new PGID settings.
