### DISCUSSION TITLE
PLAYER_EVENT_NOTIFICATIONS is not working

### DISCUSSION THREAD

**Discussion by ericjgoebel** [mbround18/valheim-docker#992] [Help!]
I don't see any messages for arrival or leaving for any players when setting this flag to 1 (and having a webhook url). 

I waited 11 minutes after logging in and did not see any messages in my discord.  What is the frequency that these messages are supposed to be sent? 

I actually have a scrappy version of this set up myself using powershell which basically reads the last 400 lines in the log every 30 seconds and if it finds a match for a player logging in it sends the player name with the local timestamp. It saves that timestamp and only reads lines in the next pass over the log that are newer than that timestamp as to not resend information. 

![image](https://github.com/user-attachments/assets/1507a1e5-abc1-453f-9456-f6aa51ecbf91)

Also, I recommend adding this to the example on the readme that is "Everything but the kitchen sink" 

My docker compose file
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    stop_signal: SIGINT
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      NAME: "Tacticals Realm"
      WORLD: "mysecretworldname"
      PASSWORD: "mysecretpassword"
      TZ: "America/New_York"
      PUBLIC: 1
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "*/15 * * * *"
      AUTO_UPDATE_PAUSE_WITH_PLAYERS: 1
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "0 */1 * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS: 0
      SCHEDULED_RESTART: 1
      SCHEDULED_RESTART_SCHEDULE: "30 4 * * *"
      UPDATE_ON_STARTUP: 1
      PLAYER_EVENT_NOTIFICATIONS: 1
      WEBHOOK_URL: https://discord.com/api/webhooks/mysecretwebhook
    volumes:
      - "S:\\Games\\Docker\\TacticalsRealm\\valheim\\saves:/home/steam/.config/unity3d/IronGate/Valheim"
      - "S:\\Games\\Docker\\TacticalsRealm\\valheim\\server:/home/steam/valheim"
      - "S:\\Games\\Docker\\TacticalsRealm\\valheim\\backups:/home/steam/backups"
```
