### ISSUE TITLE
Bug when starting 2 instances after restart

### ISSUE THREAD

**Issue by Devidian** [mbround18/valheim-docker#122]
Hey, i have running 2 container instances and after the auto update/restart one of the two instances is started twice - or better said one container is running the other containers game.

both use the same volume mounts with different environment variables.

```yaml
version: '3.8'

services:
  valheim:
    image: mbround18/valheim:latest
    container_name: valheim-docker-ds-02
    restart: unless-stopped
    ports:
      - target: 2466
        published: 2466
        protocol: udp
        mode: host
      - target: 2467
        published: 2467
        protocol: udp
        mode: host
      - target: 2468
        published: 2468
        protocol: udp
        mode: host
    environment: 
      NAME: "[DE] - DevidianATtwitch.de"
      WORLD: "OmegaWorld01"
      PORT: "2466"
      PASSWORD: "****"
      TZ: Europe/Berlin
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: 15 5 * * *
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: 15 * * * *
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
    volumes:
    - /appdata/valheim:/home/steam/valheim
    - /appdata/valheim-worlds:/home/steam/.config/unity3d/IronGate/Valheim
    - /appdata/valheim-backup:/home/steam/backups
```

```yaml
version: '3.8'

services:
  valheim:
    image: mbround18/valheim:latest
    container_name: valheim-docker-ds-01
    restart: unless-stopped
    ports:
      - target: 2456
        published: 2456
        protocol: udp
        mode: host
      - target: 2457
        published: 2457
        protocol: udp
        mode: host
      - target: 2458
        published: 2458
        protocol: udp
        mode: host
    environment: 
      NAME: "DudesOnStream"
      WORLD: "DOSUniverse"
      PORT: "2456"
      PASSWORD: "****"
      TZ: Europe/Berlin
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: 0 5 * * *
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: 0 * * * *
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
    volumes:
    - /appdata/valheim:/home/steam/valheim
    - /appdata/valheim-worlds:/home/steam/.config/unity3d/IronGate/Valheim
    - /appdata/valheim-backup:/home/steam/backups
```

every morning the `valheim-docker-ds-01` is running the game from `valheim-docker-ds-02`

**Comment by mbround18** [comment]
That would make sense, you have the same volume mounts in your host.

On each compose change the `/appdata/valheim` to be `/appdata/valheim-[instance number]`

Be sure to replace the instance number with a number and remove the brackets.

Example `/appdata/valheim-01`

**Comment by Devidian** [comment]
i wanted to reuse the binary files, as i do on other games. And the worlds are saved by worldname so when i startup everything is running fine, only on restart it looks like one container takes wrong parameters.

i could merge them but i like to have them seperate to quickly clone and deploy another instance on demand.

**Comment by Devidian** [comment]
Looks like the settings are saved in the binary directory `config.json` is this a game or an odin file created for restart? in the latter it could use the env to suffix or prefix the filename.

**Comment by mbround18** [comment]
I think I see the issue, good call out! The issue might be with Odin.


 Just got off a 13 hour shift and will have to take a look at this tomorrow ❤️


As a temporary fix, I know it will take up more space, change the root directory of the Valheim server installation. The issue might lie with the `config.json` for odin but I want to do a root cause analysis.

**Comment by Devidian** [comment]
![image](https://user-images.githubusercontent.com/10413872/108172811-96902d00-70fd-11eb-9e82-0568a72166cf.png)

never got into rust yet but might be this method ?

**Comment by mbround18** [comment]
Close, it's with the parsing of that file. The fix I would like to implement is changing the expected read and write of that file to be an array of configs or Valheim arguments. Which would be keyed by the world name because all the other variables are relatively ephemeral but the world name is what Valheim needs to match.

**Comment by Devidian** [comment]
Got it working!

```yaml
    environment: 
      NAME: "DudesOnStream"
      WORLD: "DOSUniverse"
      PORT: "2456"
      PASSWORD: "letmeinplz"
      TZ: Europe/Berlin
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: 0 5 * * *
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: 0 * * * *
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      ODIN_CONFIG_FILE: "config-01.json" <---- this line does the trick
```
