### ISSUE TITLE
ability to change steam userid

### ISSUE THREAD

**Issue by Fabiryn** [mbround18/valheim-docker#16]
Seems like the docker user and the environment puid pgid are ignored.

```
services:
  valheim:
    image: mbround18/valheim:latest
    restart: unless-stopped
    user: 1001:1001
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PUID: 1001
      PGID: 1001
      ....
```

currently I can only manage to run the container if I grant 777 access to the mounted volume.
