### ISSUE TITLE
[Bug] Docker Container crashes on entrypoint.sh

### ISSUE THREAD

**Issue by michaelgrosser** [mbround18/valheim-docker#170]
## System Information

Operating System: Amazon Linux 2
Docker Version: 19.03.13-ce, build 4484c46
Docker Compose Version:  1.28.4, build cabd5cfb
User & Group On Host: ec2-user/ec2-user 1000:1000 (non-root)
Are you running with BepInEx? No

## Issue Description

The Valheim server crashes on entrypoint.sh. The following is the entirety of the logfile from the Valheim container

```
valheim_1  | /entrypoint.sh: line 2: $'\r': command not found
valheim_1  | /entrypoint.sh: line 8: $'\r': command not found
valheim_1  | /entrypoint.sh: line 11: $'\r': command not found
valheim_1  | /entrypoint.sh: line 18: syntax error near unexpected token `$'{\r''
'alheim_1  | /entrypoint.sh: line 18: `log() {
```

This my Docker compose file:

```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Created With Valheim Docker"
      - WORLD="[REDACTED]"
      - PASSWORD="[REDACTED]"
      - TZ="America/Chicago"
      - PUBLIC=1
      - AUTO_UPDATE=0
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim

```

I have tried creating the /saves and /server dirs as the ec2-user to rule out any issues with that.
