### ISSUE TITLE
World Save on shutdown [Windows, Docker Desktop]

### ISSUE THREAD

**Issue by ExQDev** [mbround18/valheim-docker#625]
Hello!
I've got a problem, that world never saves. There is no .db file in worlds folder, it never been created or updated if I put it by myself.
Every container startup it generates world again and again, telling me that no .db file was found:
`missing /home/steam/.config/unity3d/IronGate/Valheim/worlds_local/StEvilOnline.db`

I tried to find solution of this problem, but nothing found.
All rights for Valheim folder are correct, belongs to "steam" user with r/w rights.

**Comment by spannerman79** [comment]
Modded?

Give `docker-compose.yml` - use markdown.

**Comment by ExQDev** [comment]
```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="StEvilOnline"
      - WORLD="StEvilOnline"
      - PASSWORD="ForMyPussies"
      - TZ=Europe/Kyiv
      - PUBLIC=1
      - AUTO_UPDATE=0
      - UPDATE_ON_STARTUP=0
      - TYPE=BepInExFull
      - AUTO_BACKUP=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - WEBHOOK_URL=https://discord.com/api/webhooks/1039030514402742373/BviNPMDQ_zsiUWZWUep3PBObQ7b64PFpusWKaYfY2vD0mnT7IZytW_XokmOE91IcspvA
      - WEBHOOK_BROADCAST_MESSAGE=
      - WEBHOOK_INCLUDE_PUBLIC_IP=1
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
      - ./valheim/logs:/home/steam/valheim/logs
```
