### ISSUE TITLE
Error starting docker container

### ISSUE THREAD

**Issue by patelneel4** [mbround18/valheim-docker#70]
Hi,

I'm having some trouble getting the docker container up and running. Below is my logs below once the container has been started.

Can you please shed some light as what the problem might be?

```
[Valheim][root] : ###########################################################################


[Valheim][root] : Valheim Server - Sat Feb 13 21:05:39 AEDT 2021


[Valheim][root] : Initializing your container...


[Valheim][root] : ###########################################################################


[Valheim][root] : Switching UID and GID


usermod: no changes


[Valheim][root] : 


[Valheim][root] : 


[Valheim][root] : Auto Update Enabled...


[Valheim][root] : Schedule: 0 1 * * *


[Valheim][root] : Setting up file systems


[Valheim][root] : Launching as steam...


[Valheim][steam]: ###########################################################################


[Valheim][steam]: Valheim Server - Sat Feb 13 21:05:46 AEDT 2021


[Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000


[Valheim][steam]: Installing Valheim via Odin...


[Valheim][steam]: ###########################################################################


[Valheim][steam]: Variables loaded.....


[Valheim][steam]: 


Port: 2456


Name: "Test Server"


World: "Dedicated"




1


Password: (REDACTED)




[Valheim][steam]: Running Install...


[ODIN][INFO]  - Installing 896660 to /home/steam/valheim


[ODIN][ERROR] - Failed to find steamcmd in path


[ODIN][ERROR] - Checking for script under steam user.


[ODIN][INFO]  - Executing: /home/steam/steamcmd/steamcmd.sh .....


[ODIN][INFO]  - Using steamcmd script at /home/steam/steamcmd/steamcmd.sh


WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.


Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'


[  0%] Checking for available updates...


[----] Verifying installation...


[  0%] Downloading update...


[  0%] Checking for available updates...


[----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.


src/tier0/threadtools.cpp (3553) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x571a28f0/0x0xf7c0eb'


[ODIN][INFO]  - Exited with status code: 254


[Valheim][steam]: Herding Cats...


[Valheim][steam]: Starting server...


[ODIN][INFO]  - Setting up start scripts...


[ODIN][INFO]  - Looking for burial mounds...


[ODIN][INFO]  - Successfully written /home/steam/valheim/start_server_rusty.sh


[ODIN][INFO]  - Created the /home/steam/valheim/start_server_rusty.sh script successfully!


[ODIN][INFO]  - Successfully set /home/steam/valheim/start_server_rusty.sh to executable


[ODIN][INFO]  - Successfully set /home/steam/valheim/start_server_rusty.sh to executable!


[ODIN][ERROR] - Could not find server executable! Please install the server!


[Valheim][steam]: ###########################################################################


[Valheim][steam]: Valheim Server - Sat Feb 13 21:06:28 AEDT 2021


[Valheim][steam]: STEAM_UID 1000 - STEAM_GUID 1000


[Valheim][steam]: 


Valheim Server Started...




Keep an eye out for 'Game server connected' in the log!


(this indicates its online without any errors.)




[Valheim][steam]: ###########################################################################

```

**Comment by patelneel4** [comment]
Incase you needed it, here's the docker.yml file
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="Test Server"
      - WORLD="Dedicated"
      - PASSWORD="testServer123"
      - TZ=Australia/Sydney
      - PUBLIC=1
      - AUTO_UPDATE=0
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
```
