### ISSUE TITLE
World save is not triggered on container stop

### ISSUE THREAD

**Issue by guyspr** [mbround18/valheim-docker#732]
I've noticed that, when restarting/stopping the server running this docker container. Then the world is not saved, and any built object will disappear since last save (which can be 30 minutes ago). It seems like the shutdown process does not force a world save which can cause data-loss.

**Comment by mbround18** [comment]
@guyspr  this has been resolved before, please add this to your docker compose   for the service 

stop_grace_period: 2m


if it still occurs consider expanding the stop_grace_period. Larger worlds will take longer to save.

**Comment by guyspr** [comment]
> @guyspr this has been resolved before, please add this to your docker compose for the service
> 
> stop_grace_period: 2m
> 
> if it still occurs consider expanding the stop_grace_period. Larger worlds will take longer to save.

Thanks for your reply, I will be testing if this resolved the issue for me :)

**Comment by mbround18** [comment]
any updates @guyspr ?

**Comment by guyspr** [comment]
@mbround18 It still doesn't seem to trigger the save on shutdown with the added setting. I test it by building something new in the world, then stopping and starting the container. The placed item will disappear. I do make sure to do a manual save now (using the console) before shutting down.

**Comment by mbround18** [comment]
Can you drop your docker-compose? Omitting any passwords ofc

**Comment by guyspr** [comment]
Here's the compose file I'm using:

```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    stop_signal: SIGINT
    stop_grace_period: 2m
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    environment:
      PORT: 2456
      NAME: "*****"
      WORLD: "*****"
      PASSWORD: "****"
      TZ: "Europe/Amsterdam"
      PUID: 1000
      GUID: 1000
      PUBLIC: 0
      AUTO_UPDATE: 0
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/15 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 7
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
#      TYPE: Vanilla
      TYPE: BepInEx
    volumes:
      - ./saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./server:/home/steam/valheim
      - ./backups:/home/steam/backups
```
