### ISSUE TITLE
Log is beeing flooded

### ISSUE THREAD

**Issue by MrFr33man123** [mbround18/valheim-docker#805]
The Server runs but floods the log with assembly beeing unable to be loaded.

I am running the server with BepInEx enabled only one mod, devcommands.

```
{"log":"TypeLoadException: Failure has occurred while loading a type.\n","stream":"stdout","time":"2024-04-20T06:44:13.139357048Z"}
{"log":"  at (wrapper dynamic-method) Chat.DMD\u003cChat::Update\u003e(Chat)\n","stream":"stdout","time":"2024-04-20T06:44:13.139379278Z"}
{"log":"\n","stream":"stdout","time":"2024-04-20T06:44:13.139402045Z"}
{"log":"04/20/2024 08:44:13: Console: [Error  : Unity Log] TypeLoadException: Failure has occurred while loading a type.\n","stream":"stdout","time":"2024-04-20T06:44:13.171196061Z"}
{"log":"Stack trace:\n","stream":"stdout","time":"2024-04-20T06:44:13.171323438Z"}
{"log":"(wrapper dynamic-method) Chat.DMD\u003cChat::Update\u003e(Chat)\n","stream":"stdout","time":"2024-04-20T06:44:13.171349917Z"}
{"log":"\n","stream":"stdout","time":"2024-04-20T06:44:13.17147034Z"}
{"log":"TypeLoadException: Failure has occurred while loading a type.\n","stream":"stdout","time":"2024-04-20T06:44:13.17149641Z"}
{"log":"  at (wrapper dynamic-method) Chat.DMD\u003cChat::Update\u003e(Chat)\n","stream":"stdout","time":"2024-04-20T06:44:13.171518424Z"}
{"log":"\n","stream":"stdout","time":"2024-04-20T06:44:13.171540803Z"}
```

I tried to remove everything an pulled the image again same problem.

this is my config:

```
version: "3"
services:
  valheim:
    container_name: valheim-valheim-1
    image: mbround18/valheim:latest
    restart: always
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
      - 6660:6660/tcp
    environment:
      PORT: 2456
      NAME: "Rick_and_Morty_Dimension"
      WORLD: "xxxx"
      PASSWORD: "xxxxxx"
      TZ: "Europe/Berlin"
      PUBLIC: 1
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 1 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "*/30 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 2
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS: 1
      #WEBHOOK_URL: "http://192.168.178.3:1880/valheim"
      UPDATE_ON_STARTUP: 1
      HTTP_PORT: 6660
      TYPE: "BepInEx"
      MODS: "https://thunderstore.io/package/download/JereKuusela/Server_devcommands/1.74.0/"
    volumes:
      - /home/tiny/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /home/tiny/valheim/server:/home/steam/valheim
      - /home/tiny/valheim/backups:/home/steam/backups
```

Let me know if I am doing something wrong, it worked perfectly fine till the last update.
